### ISSUE TITLE
Rebuild conda recipes to include pytables and numexpr.

### ISSUE THREAD

**Issue by danielballan** [soft-matter/trackpy#175]
These are optional deps of pandas. They enable trackpy's `PandasHDFStore` and `DataFrame.query`, respectively, both of which are very handy.

**Comment by danielballan** [comment]
@tacaswell In #135 you objected to bundling pytables into the conda package because you thought it conflicted with pytables. We have since figured out that it does not conflict anymore. That is,

    conda install h5py pytables

creates no problems. Are you OK with bundling pytables?

**Comment by tacaswell** [comment]
The conflicts are at runtime and it relies on having new enough version of h5py, hdf5, and pytables.  I _think_ conda has up-to-date enough everything.

**Comment by danielballan** [comment]
Can you find a link for this? It would be good to know the version number and comment on this in the meta.yml.

**Comment by tacaswell** [comment]
https://github.com/h5py/h5py/issues/390  Looks like the stock images from anaconda still have issues

**Comment by danielballan** [comment]
Thanks. I'll leave this open and we'll circle back later once that is sorted out.

**Comment by danielballan** [comment]
Evidently, this has been fixed. @tacaswell do you know how to test, so we can be sure?

**Comment by tacaswell** [comment]
Import both and see if it blows up?

**Comment by danielballan** [comment]
I guess my question is, is (was) it an import-time issue?

**Comment by danielballan** [comment]
OK, I satisfied myself that this issue is solved. I can import both and export data using hdf5 and pandas.HDFStore in the table IPython session. No problems.
