### ISSUE TITLE
Preserve documentation for previous releases

### ISSUE THREAD

**Issue by nkeim** [soft-matter/trackpy#182]
Past versions of the [published documentation](http://soft-matter.github.io/trackpy/) should be available under "permanent" stable URLs. For practical reasons this policy should begin with documentation for the final v0.2 release.

@danielballan has suggested we look to the matplotlib project for a solution.

This issue comes from the discussion in https://github.com/soft-matter/trackpy-examples/pull/14#issuecomment-66544495

**Comment by danielballan** [comment]
I have to figure this out for scikit-xray, so I can take care of this from trackpy as well, probably next week.

**Comment by danielballan** [comment]
Above @nkeim wrote

> Past versions of the published documentation should be available under "permanent" stable URLs. For practical reasons this policy should begin with documentation for the final v0.2 release.

The target release for the revamped docs has been v0.3. Is it OK with everyone if we start with that, later branching the docs for v0.4.x?

**Comment by tacaswell** [comment]
We should still build and publish the old docs.

**Comment by danielballan** [comment]
Hark! Was that the sound of someone volunteering to help me deploy multiple versions of sphinx docs?

**Comment by tacaswell** [comment]
Sure, the way we do it for mpl is to have sub folders and link to their
index.html files from the main page (ex http://matplotlib.org/1.2.1/ is the
oldest mpl docs).

**Comment by danielballan** [comment]
Thanks buddy. :- )

**Comment by danielballan** [comment]
I'm removing this from the v0.3.0 milestone with @tacaswell's blessing. There is no reason we can't do this after we tag v0.3.0.
