### ISSUE TITLE
Revisit numba code to take advantage of updates to numba

### ISSUE THREAD

**Issue by danielballan** [soft-matter/trackpy#190]
There may be more datatype flexibility as [@nkeim mentioned](https://github.com/soft-matter/trackpy/issues/135#issuecomment-67681153) and there may be ways to get additional performance gains. If such changes require dropping support for older versions of numba, that is OK.

**Comment by nkeim** [comment]
The refactor in #217 (possibly combined with newer versions) has made the code faster and more datatype-agnostic, while being less reliant on numba's "magic" features. Closing…for now.
