### ISSUE TITLE
GOOD_ENOUGH_THRESH different for numba and not-numba

### ISSUE THREAD

**Issue by RebeccaWPerry** [soft-matter/trackpy#191]
In feature.py, the GOOD_ENOUGH_THRESH is different for the numba version and the not numba version:

line 199, thresh is set to 0.005 (was previously 0.01 back in February, changed in commit f963d4)
line 303, thresh is set to 0.01

Is this difference intentional?

**Comment by nkeim** [comment]
Weird. If anything, the *numba* algorithm should be seeking better convergence than pure-Python, because loops are so cheap. This was @danielballan's commit. Dan, can you remember your/our reasoning?

**Comment by danielballan** [comment]
I remember that reducing pure Python's GOOD_ENOUGH_THRESH to 0.005 improved its performance on the tests in the test suite, but reducing numba's GOOD_ENOUGH_THRESH to 0.005 caused it to perform *worse*. More tests would be need to understand why and to check that the problem isn't specific to those tests.

There is an implementation difference as noted in [this comment](https://github.com/soft-matter/trackpy/blob/master/trackpy/feature.py#L383). It may be easier to complete the implementation using current numba. At the time, we were all working on different fronts to merge my fork and Nathan's fork satisfactorily, and this detail didn't get as much attention as it may have deserved. It performed well enough for us to get our science done.

As we add more detailed logging, let's try to understand exactly what is happening here.

**Comment by danielballan** [comment]
I wonder if it's possible to make calls to `logger` from within numba without leaving nopython mode? There must be *some* way to debug numba code....

**Comment by nkeim** [comment]
Inspired by https://github.com/soft-matter/trackpy/pull/184#issuecomment-69503525 :

If a debug flag is set, we could have the numba code allocate an N x m array, returning *m* pieces of debug info for each particle. (In this case just the number of refine steps, so m=1?) If the debug flag is clear, it would just return a dummy 1 x 1 array instead. The debug info could be included in the features DataFrame. It wouldn't use `logger`, but the performance cost would be negligible.

**Comment by danielballan** [comment]
I think [Jaqaman et. al](http://www.nature.com/nmeth/journal/v5/n8/abs/nmeth.1237.html) collect this kind of information in their results as well. If adaptive search is being used, perhaps the results DataFrame should include this information. I'm not sure we even need to give the users a way to turn it off -- debug flag or no.

**Comment by tacaswell** [comment]
If it is in the data frame users can 'turn it off' by dropping the column ;).

**Comment by danielballan** [comment]
Right.
