### ISSUE TITLE
Should we release a 0.2.5 to better support latest deps?

### ISSUE THREAD

**Issue by danielballan** [soft-matter/trackpy#197]
On numpy 1.9, the test suite passes locally, but it issues so many warnings (> 4MB of logs!) that [Travis declares it broken](https://api.travis-ci.org/jobs/47066968/log.txt?deansi=true).

Worse, I discovered a problem with numba 0.16 after all. Trackpy works with python 2.7 + numba 0.16 -- and on all platforms, as mentioned in #135. But it fails badly with python 3.4 + numba 0.16. I did not see that one coming.

I don't expect we'll be tagging 0.3 very soon, so I think I will try to address these issues and cherry-pick commits for a 0.2.5 release. To be clear, that release will not include the other changes to the code currently in master. Good idea?

**Comment by nkeim** [comment]
Yes. v0.3 is going to bring some changes that are possibly disruptive and/or buggy, plus it is a couple weeks away (just my guess). It would be helpful to release a v0.2.x that's likely to be easy to install and use for at least a few more months. *But* I would say that it's more important to fix the numba issues in v0.2.5; I think that numpy warnings and failing travis are acceptable sacrifices, considering that there will be no further development on the v0.2.x series. Lastly, chances are that the numba changes will be easier to apply backward or forward — our numba code hasn't changed much recently.

Regarding v0.3:

- A final #192 (adaptive search) should be ready within a couple weeks, though I say that without having benchmarked it yet.
- I'd say #184 (logging) should be marked for v0.3. We still have to figure out the debug API, which may involve the elimination of `quiet()`. (Though that could happen in a separate PR.)
- #196 (3D plotting) is a good idea for v0.3, though it could be pushed back to v0.3.1 if there's an unexpected issue.

Should I go ahead and mark those for v0.3? Those are the big feature PRs, but there are other minor ones that I'm unclear on, especially as these numpy and numba issues have arisen.

**Comment by danielballan** [comment]
Yes please.

**Comment by danielballan** [comment]
Backporting is hard. But I still think we should do this if it's feasible. @tacaswell, how does this work tagging-wise?

**Comment by tacaswell** [comment]
We are too small to do excessive back support, if someone really wants it they can offer to do the backport.

I suggest you watch http://pyvideo.org/video/3764/contributors-colleagues-clients-customers-su to get some background on what is pushing my thinking on that position.  I have been thinking about this for a while, but that talk does a very good job of articulating it.

**Comment by danielballan** [comment]
Good enough for me. I leave it to @nkeim to close if he is also persuaded.

**Comment by nkeim** [comment]
Agreed. This was a good idea when first proposed, but as time has passed it's become both more difficult and less compelling. If someone needs to reproduce results from an old version of trackpy, it's no problem as long as they're careful about dependency versions. That would always be true to some extent. And we can offer some guidance as needed. Thank goodness for conda.

Passing thought: I wonder if we should be identifying a known-good version of Anaconda in each trackpy version's release notes.
