### ISSUE TITLE
Selling trackpy on the homepage

### ISSUE THREAD

**Issue by nkeim** [soft-matter/trackpy#205]
trackpy has many important strengths, and we pride ourselves on the overall quality and design of the code. However, there is a subset of those strengths that one might call "killer" features — ones that are sufficiently impressive that they could grab attention and/or convince someone to switch from an already-working solution. I can think of a few possible examples:

- Running on Python (but that's hard to miss)
- Anisotropic 3D support, which will be a major improvement in v0.3
- Handling of arbitrarily long movies in many formats
- Attractive built-in plotting
- More?

When one Googles "trackpy," the top result is the GitHub page. If we start the stopwatch when someone clicks on that link, how long until they discover one or more of these features? What could we do to shorten this time?

- Should these marquee features be listed on the documentation front page? The GitHub README?
- Should one of the banner images on the documentation front page represent 3D data?
- Should there be a tutorial on anisotropic 3D features? ( @caspervdw ?)

This was prompted by a person who, after looking briefly at the documentation, had the impression that trackpy does not support 3D.

**Comment by caspervdw** [comment]
Good that you mention it, I will finish the tutorial this weekend.

**Comment by nkeim** [comment]
As far as I'm concerned, this issue was adequately addressed by @caspervdw . Onward to v0.3!
