### ISSUE TITLE
diag.dependencies() availability? vs documentation

### ISSUE THREAD

**Issue by apiszcz** [soft-matter/trackpy#213]
The documentation states there is a diag.dependencies()  in the section. 

Diagnostic functions
diag.performance_report()	Display summary of which optional speedups are installed/enabled
diag.dependencies()	Give the version of each of the dependencies – useful for bug reports.
However the function does not appear to be int eh diag.py module.

(Pdb) pprint.pprint(dir(tpdiag))
['__builtins__',
 '__doc__',
 '__file__',
 '__name__',
 '__package__',
 '__version__',
 'absolute_import',
 'division',
 'performance_report',
 'preprocessing',
 'print_function',
 'six',
 'try_numba',
 'unicode_literals']
(Pdb) tp.__version__
'0.2.4'

**Comment by danielballan** [comment]
The (greatly expanded) documentation is a recent addition to trackpy, and
it describes version 0.3, which is still in development, to be released in
a month or two. From the release of 0.3 onward, we will be maintain
separate documentation for each version, but we don't have the manpower to
write docs for the current stable release, 0.2.x, retroactively.

If you like, see the installation instructions to install the development
version, which includes the feature you want. I will add a note to the docs
to make it clear that the docs are targeting 0.3, not the current stable
release. Sorry for the time you lost wondering about this!

Dan

**Comment by apiszcz** [comment]
Thank you.
I'm am interested in some other features apparently coming in 0.3, link_df
adaptive search may help me out. I check the installation documentation but
did not see any 0.3 reference. FYI: I package the capability without
pip/easy... etc, by creating a standalone folder 'lib' with all
dependencies so no special installation is needed. (Windows 64 bit). numba
is providing about 2x speedup for some initial tests. I'm also trying to
use link_df_iter with a predictor, not sure the documentation and the 0.2.4
release I'm using is in sync.
Thanks again for replying.

**Comment by danielballan** [comment]
The prediction feature was [added in 0.2.0 and refined in 0.2.1](https://github.com/soft-matter/trackpy/releases), and I don't think that has been specifically altered or updated since.

To install the version under development, which we plan to release as v0.3, see [this section of the installation instructions](http://soft-matter.github.io/trackpy/installation.html#latest-version-under-development).

Be advised that we have made several important changes to feature-finding and trajectory-linking, so analysis performed with this updated code will give different results. They are better, more accurate results, and very similar results in many cases, but it's important to keep this in mind if you switch. Trackpy releases abide by [semantic versioning](http://semver.org/); while results from any v0.2.x release should be consistent, results from v0.3 will not be.

**Comment by apiszcz** [comment]
Thank you

I'm still having issues locating the package.
Concerning predict, understand, I should have said 'adaptive' is not in
0.2.4, appears to be a 0.3 capability.

FAIL
1) git clone https://github.com/soft-matter/channel/dev/trackpy
fatal: repository 'https://github.com/soft-matter/channel/dev/' not found

FAIL
2) ap@ubuntu:~/anaconda$ bin/conda install -c soft-matter/channel/dev
trackpy
Fetching package metadata: ....Could not connect to
https://conda.binstar.org/soft-matter/channel/dev/linux-64/
Could not connect to http://repo.continuum.io/pkgs/pro/linux-64/
Could not connect to https://conda.binstar.org/soft-matter/linux-64/
Could not connect to http://repo.continuum.io/pkgs/free/linux-64/

Error: No packages found in current linux-64 channels matching: trackpy

You can search for this package on Binstar with

    binstar search -t conda trackpy

You may need to install the Binstar command line client with

    conda install binstar
ap@ubuntu:~/anaconda$ binstar search -t conda trackpy
binstar: command not found

**Comment by caspervdw** [comment]
I recently installed the dev version using the following (assuming you have `pip`, otherwise do `conda install pip` before):

    pip install http://github.com/soft-matter/trackpy/zipball/master

Could you try this?

**Comment by danielballan** [comment]
In your first approach, the git install, that URL isn't quite right. "Channels" are a conda thing, not a github thing. As per [this section of the docs](http://soft-matter.github.io/trackpy/installation.html#more-information-for-experienced-python-users), use

    git clone https://github.com/soft-matter/trackpy
    pip install -e trackpy

The `pip install http://...` method is a good alternative. But I would like to get that conda installation working reliably, as I think it's the easiest and least likely to create confusing problems. If you have the time to help us debug it:

I see the line

    Could not connect to https://conda.binstar.org/soft-matter/channel/dev/linux-64/

in the error. But I can open that URL in my browser, and I see a list of trackpy packages. Could you have had Internet connectivity problems at the time? Would you try that again?

**Comment by tacaswell** [comment]
That clone command is wrong, it should be 

```
 git clone https://github.com/soft-matter/trackpy.git
```

For the second, it looks like you are having general connectivity issues as the errors are that conda can not connect to the servers.

**Comment by danielballan** [comment]
@tacaswell and I are in sync today I guess.

**Comment by apiszcz** [comment]
Thank you for the replies.
Your suggested command works. I did find this line in the instillation
documentation page.

git clone https://github.com/soft-matter/trackpy.git

In my packaging case I like to get the pure python files/folders copy
them to the a 'lib' folder, sys.path.insert(0,'lib') to use. So
installing on a platform is not really what was looking for conda/pip,
though i can usually locate the site-package and copy. git clone is
good. I notice that there is no __version__ explicit in the files
until setup.py is run and versioneer is involved.

So when I copy over the trackpy from git, WITHOUT running setup.py I
get the following for the version.

(Pdb) trackpy.__version__
'unknown'

Thanks for all the replies.

I should look into the CONDA install again, with fewer firewalls.

**Comment by apiszcz** [comment]
Another update, conda install with firewall off: (success) looks like I 0.3
installed on this test.

I see 'unknown' which may be correct == 0.3.

I see diag has dependencies which Dan told me is a 0.3 capability.


ap@ubuntu:~/anaconda$ bin/python
Python 2.7.9 |Anaconda 2.1.0 (64-bit)| (default, Dec 15 2014, 10:33:51)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import trackpy
>>> trackpy.__version__
'unknown'
>>>


On Wed, Mar 4, 2015 at 10:56 AM, Dan Allan <notifications@github.com> wrote:

> @tacaswell <https://github.com/tacaswell> and I are in sync today I guess.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/soft-matter/trackpy/issues/213#issuecomment-77184168>.
>

root@ubuntu:~/anaconda# bin/conda install -c soft-matter/channel/dev trackpy
Fetching package metadata: ....
Solving package specifications: ...................
Package plan for installation in environment /home/ap/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cairo-1.12.18              |                0         593 KB
    conda-3.9.1                |           py27_0         164 KB
    conda-env-2.1.3            |           py27_0          15 KB
    matplotlib-1.4.0           |       np18py27_0        44.7 MB
    numba-0.13.4               |       np18py27_0         689 KB
    numpy-1.8.2                |           py27_0         7.3 MB
    openssl-1.0.1k             |                0         2.6 MB
    pandas-0.14.1              |       np18py27_0         9.0 MB
    pillow-2.7.0               |           py27_0         771 KB
    pims-0.2.2                 |           py27_0          40 KB
    py2cairo-1.10.0            |           py27_2          36 KB
    python-2.7.9               |                1        13.4 MB
    pytz-2014.9                |           py27_0         175 KB
    requests-2.5.3             |           py27_0         593 KB
    scikit-image-0.10.1        |       np18py27_0        21.3 MB
    scipy-0.14.0               |       np18py27_0        29.6 MB
    setuptools-12.3            |           py27_0         435 KB
    six-1.9.0                  |           py27_0          17 KB
    tifffile-0.3.1             |       np18py27_0         114 KB
    trackpy-v0.2.4.post93      |93_gcfe946d_py2.7         884 KB
    zlib-1.2.8                 |                0         100 KB
    ------------------------------------------------------------
                                           Total:       132.5 MB

The following NEW packages will be INSTALLED:

    conda-env:    2.1.3-py27_0                   
    pillow:       2.7.0-py27_0                   
    pims:         0.2.2-py27_0                   
    tifffile:     0.3.1-np18py27_0               
    trackpy:      v0.2.4.post93-93_gcfe946d_py2.7

The following packages will be UPDATED:

    cairo:        1.12.2-2          --> 1.12.18-0
    conda:        3.7.0-py27_0      --> 3.9.1-py27_0                   
    matplotlib:   1.4.0-np19py27_0  --> 1.4.0-np18py27_0               
    openssl:      1.0.1h-1          --> 1.0.1k-0                       
    pandas:       0.14.1-np19py27_0 --> 0.14.1-np18py27_0              
    py2cairo:     1.10.0-py27_1     --> 1.10.0-py27_2                  
    python:       2.7.8-1           --> 2.7.9-1                        
    pytz:         2014.7-py27_0     --> 2014.9-py27_0                  
    requests:     2.4.1-py27_0      --> 2.5.3-py27_0                   
    scikit-image: 0.10.1-np19py27_0 --> 0.10.1-np18py27_0              
    scipy:        0.14.0-np19py27_0 --> 0.14.0-np18py27_0              
    setuptools:   5.8-py27_0        --> 12.3-py27_0                    
    six:          1.8.0-py27_0      --> 1.9.0-py27_0                   
    zlib:         1.2.7-0           --> 1.2.8-0                        

The following packages will be DOWNGRADED:

    numba:        0.14.0-np19py27_0 --> 0.13.4-np18py27_0              
    numpy:        1.9.0-py27_0      --> 1.8.2-py27_0                   

Proceed ([y]/n)? y

Fetching packages ...
cairo-1.12.18- 100% |##################################################################| Time: 0:00:00   2.78 MB/s
conda-3.9.1-py 100% |##################################################################| Time: 0:00:00   1.32 MB/s
conda-env-2.1. 100% |##################################################################| Time: 0:00:00   1.87 MB/s
matplotlib-1.4 100% |##################################################################| Time: 0:00:08   5.68 MB/s
numba-0.13.4-n 100% |##################################################################| Time: 0:00:00   2.81 MB/s
numpy-1.8.2-py 100% |##################################################################| Time: 0:00:01   6.88 MB/s
openssl-1.0.1k 100% |##################################################################| Time: 0:00:00   6.45 MB/s
pandas-0.14.1- 100% |##################################################################| Time: 0:00:01   6.03 MB/s
pillow-2.7.0-p 100% |##################################################################| Time: 0:00:00   5.78 MB/s
pims-0.2.2-py2 100% |##################################################################| Time: 0:00:00   2.06 MB/s
py2cairo-1.10. 100% |##################################################################| Time: 0:00:00   2.19 MB/s
python-2.7.9-1 100% |##################################################################| Time: 0:00:02   6.54 MB/s
pytz-2014.9-py 100% |##################################################################| Time: 0:00:00   2.98 MB/s
requests-2.5.3 100% |##################################################################| Time: 0:00:00   4.67 MB/s
scikit-image-0 100% |##################################################################| Time: 0:00:03   7.39 MB/s
scipy-0.14.0-n 100% |##################################################################| Time: 0:00:04   7.00 MB/s
setuptools-12. 100% |##################################################################| Time: 0:00:00   1.97 MB/s
six-1.9.0-py27 100% |##################################################################| Time: 0:00:00   2.03 MB/s
tifffile-0.3.1 100% |##################################################################| Time: 0:00:00   4.41 MB/s
trackpy-v0.2.4 100% |##################################################################| Time: 0:00:00   7.64 MB/s
zlib-1.2.8-0.t 100% |##################################################################| Time: 0:00:00   2.36 MB/s
Extracting packages ...
[      COMPLETE      ] |####################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ] |####################################################################################| 100%
Linking packages ...
[      COMPLETE      ] |####################################################################################| 100%

**Comment by nkeim** [comment]
@apiszcz , consider using the `-e` ("editable") option for `pip`, which leaves the source code where you put it.

```
pip install -e [directory into which you cloned the git repo]
```

**Comment by danielballan** [comment]
Looks like conda worked in the end. The version string isn't turning out right, but that's a known issue to be tackled at release time.

**Comment by apiszcz** [comment]
Dan: I did not use conda, thought I installed it. Instead I grabbed the
source only, created a lib\trackpy folder and used it in that form.
Concerning the version number, i'm living it with whatever is in there,
later with 0.3 hits, I'll set it if not correct. I'm starting to get some
yield from trackpy, I'll some questions later about he prediction piece. in
particular it seems like the velocity prediction is group or neighbors
travelling same direction. I'm curious if anyone is working on particles
from orthogonal and colliding approaches (all directions).

Thank

**Comment by nkeim** [comment]
I'm not sure I understand. `NearestVelocityPredict` is supposed to use each particle's own distinct velocity (unless the particle is new). The velocity of other, nearby particles should be irrelevant.

**Comment by apiszcz** [comment]
thanks will give it some time and test.






On Mar 18, 2015, at 18:59, Nathan Keim <notifications@github.com> wrote:

I'm not sure I understand. NearestVelocityPredict is supposed to use each
particle's own distinct velocity (unless the particle is new). The velocity
of other, nearby particles should be irrelevant.

—
Reply to this email directly or view it on GitHub
<https://github.com/soft-matter/trackpy/issues/213#issuecomment-83218600>.
