### ISSUE TITLE
linking.py time display to standard output

### ISSUE THREAD

**Issue by apiszcz** [soft-matter/trackpy#223]
Thoughts

1) Time status of linking, (including elapsed?)

At a minimum
Line 588,729 add timestamp, i'm noticing considerable pauses and monitoring the time between frame links is useful:

msg = "%s> Frame %d: %d trajectories present" % (datetime.datetime.now().isoformat(), frame_no, len(labels))

 2) Add a flag to supress these messages? or return the result set in a dictionary post run?
link_df(frame_diagnostic_stdout=False,frame_diagnostic_dictionary)

3) These topics may be addressed elsewhere, I have not reviewed the diagnostics capability.

**Comment by danielballan** [comment]
We are in the process of rethinking logging and diagnostics. Thanks for these suggestions. If you have time to read up on #183 and #184 we would welcome your thoughts on that work in progress.

**Comment by danielballan** [comment]
Closed by #184. Point (1) above doesn't need trackpy; users can customize logging however they want using the Python logging framework.
