### ISSUE TITLE
trackpy announcement mail list ?

### ISSUE THREAD

**Issue by apiszcz** [soft-matter/trackpy#225]
Is there a trackpy announcement list? (announces when a new release or minor release is available?)

**Comment by danielballan** [comment]
Not yet. In the past we have announced releases on GitHub issues. As our userbase is growing, maybe it's good time to start one.

**Comment by nkeim** [comment]
Don't forget [the Google group](https://groups.google.com/forum/#!forum/softmattersoftware). That was meant to be a low-volume way to announce major releases and events.
