### ISSUE TITLE
PANDAS warning using pred.link_df_iter()

### ISSUE THREAD

**Issue by apiszcz** [soft-matter/trackpy#231]
I am getting the warning below when calling pd.concat(pred.link_df...)

pred=trackpy.predict.NearestVelocityPredict(span=ld['velspan'])
f_iter=(frame for fnum, frame in df.groupby('frame'))
dft=pd.concat(pred.link_df_iter(f_iter, search_range=ld['d'], memory=ld['m'],adaptive_stop=ld['astop'],adaptive_step=ld['astep']
 ))

elsewhere I use df.is_copy = False to disable this warning. Is there any advice to eliminate this warning when calling pd_concat? 

C:\p\lib\pandas\core\frame.py:2513: SettingWithCopyWarning: esent
A value is trying to be set on a copy of a slice from a DataFrame
See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  **kwargs)

Thank you for any advice.

**Comment by nkeim** [comment]
I can't seem to reproduce this. It might help to have a stack trace. Try something like

```
import warnings
with warnings.catch_warnings():
    warnings.simplefilter('error')
    (your code...)
```

Your pandas and trackpy versions could be helpful too. Thanks!

**Comment by apiszcz** [comment]
trackpy is pre3.0
pandas 0.16
That is the full trace I see, for now I'm disabling with -Wignore, but it
may be nice to understand the issue.
​

**Comment by apiszcz** [comment]
import warnings
                    with warnings.catch_warnings():
                        warnings.simplefilter('error')
                    oL.logDisplay("%s> %s APTrack:run velocity prediction
search\n"%(oU.time_stamp(),src))

pred=trackpy.predict.NearestVelocityPredict(span=ld['velspan'])
                    f_iter=(frame for fnum, frame in df.groupby('frame'))
                    #df.is_copy=False
                    dft=pd.concat(pred.link_df_iter(f_iter,
                                                    search_range=ld['d'],
                                                    memory=ld['m'],

adaptive_stop=ld['astop'],

adaptive_step=ld['astep']
                                                    ))


C:\p\lib\pandas\core\frame.py:2513: SettingWithCopyWarning: esent
A value is trying to be set on a copy of a slice from a DataFrame
See the the caveats in the documentation:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  **kwargs)
C:\p\lib\trackpy\predict.py:136: UserWarning: Could not generate velocity
field for prediction: no tracks
  warn('Could not generate velocity field for prediction: no tracks')​

**Comment by nkeim** [comment]
Your code needs to be at the same indentation level as `simplefilter` (i.e. inside the `with`).

I'll be interested to see if the warning is still there once #221 is merged.

Thanks!

**Comment by apiszcz** [comment]
​Oops, thanks.

20150410T054636.633000> velocity prediction search
Traceback (most recent call last):000001: 000003 trajectories present
  File "lib\tapp\tapp.py", line 3264, in <module>
    main()
  File "lib\tapp\tapp.py", line 3247, in main
    if 'track' in modes: oAPT.run(oC,oG,oL,oU,oV,modes,src)
  File "lib\tapp\tapp.py", line 963, in run
    adaptive_step=ld['astep']
  File "C:\p\tapp\lib\pandas\tools\merge.py", line 754, in concat
    copy=copy):
  File "C:\p\tapp\lib\pandas\tools\merge.py", line 785, in __init__
    objs = [obj for obj in objs if obj is not None ]
  File "C:\p\tapp\lib\trackpy\predict.py", line 53, in link_df_iter
    self.observe(frame)
  File "C:\p\tapp\lib\trackpy\predict.py", line 128, in observe
    dt, positions, vels = self._compute_velocities(frame)
  File "C:\p\tapp\lib\trackpy\predict.py", line 99, in _compute_velocities
    vels.rename(columns=lambda n: n[:-6], inplace=True)
  File "C:\p\tapp\lib\pandas\core\frame.py", line 2513, in rename
    **kwargs)
  File "C:\p\tapp\lib\pandas\core\generic.py", line 588, in rename
    self._update_inplace(result._data)
  File "C:\p\tapp\lib\pandas\core\generic.py", line 1630, in _update_inplace
    self._maybe_update_cacher(verify_is_copy=verify_is_copy)
  File "C:\p\tapp\lib\pandas\core\generic.py", line 1162, in
_maybe_update_cacher
    self._check_setitem_copy(stacklevel=5, t='referant')
  File "C:\p\tapp\lib\pandas\core\generic.py", line 1298, in
_check_setitem_copy
    warnings.warn(t, SettingWithCopyWarning, stacklevel=stacklevel)
pandas.core.common.SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame
See the the caveats in the documentation:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

**Comment by nkeim** [comment]
Thanks, this is very helpful! I'll have a look, though it might not be for a week or two. Let me know if this becomes more urgent.

**Comment by apiszcz** [comment]
That is fine (two weeks, etc.), appreciate it, I'm using -Dignore for now.
Again from what I learned PANDAS proper way is to use a different index
mode for assignment or ​to do this (which you can set prior to each
instance of the situation)
df.is_copy=False

**Comment by nkeim** [comment]
See #236 for a fix. I was able to reproduce this condition only once as a user (there may be a random aspect as to whether a given Pandas operation creates a copy or not). But I could make it happen every time by setting editing the trackpy code to set `is_copy = True` on the DataFrame in question.
