### ISSUE TITLE
linking.py:Linker? search_range

### ISSUE THREAD

**Issue by apiszcz** [soft-matter/trackpy#232]
The Search range comment in Linker indicates the type is integer, I have been using floating point values less than 1.0 for the coordinate reference and distance measures and getting results. Generally trackpy 'seems to be' addressing pixel space coordinates, I'm interested to understand why I'm seeing reasonable results with search_range < 1.0 (.e.g. 0.05, 0.005, etc.)

    search_range : integer
        the maximum distance features can move between frames

**Comment by apiszcz** [comment]
Elsewhere in the documentation , it references floating point values for search range.

http://soft-matter.github.io/trackpy/tutorial/adaptive-search.html

**Comment by danielballan** [comment]
The docstring is incorrect. Would you be willing to make a PR to fix it? It occurs in a couple places in that file.
