### ISSUE TITLE
Observation/question: linking.py, memory>0

### ISSUE THREAD

**Issue by apiszcz** [soft-matter/trackpy#234]
Version 0.3dev, Pandas 0.16, Python 2.79
linking setup is adaptive with velocity prediction.
It seems that I am seeing linking to points beyond the search range and even beyond m*search_range.

If memory=5 and search_range is 1.0, will the maximum possible distance for a link association be 5.0?

**Comment by nkeim** [comment]
The maximum possible linking distance in that case should be 5 * (last known particle velocity) + 1.0.
