### ISSUE TITLE
supress output?

### ISSUE THREAD

**Issue by mmdriscoll** [soft-matter/trackpy#241]
Is it possible to add a kwarg to suppress the output of locate and track?  (by output, I refer to the frame-by-frame update of the number particles/tracks found)  I looked through the code, and it did not seem like this option is currently available.

**Comment by nkeim** [comment]
Hi! It's coming… see #184 . A [recent comment by Dan](https://github.com/soft-matter/trackpy/pull/184#issuecomment-97172654) summarizes the current plan. See also #235, which suggests a related feature. If you can take a couple minutes to weigh in on these, it would be very welcome.
