### ISSUE TITLE
Clean up *_THRESH magic numbers.

### ISSUE THREAD

**Issue by danielballan** [soft-matter/trackpy#246]
Make SHIFT_THRESH and GOOD_ENOUGH_THRESH optional arguments of the refine functions and document them. Thanks @sciunto for catching this.

**Comment by nkeim** [comment]
This would also partly address issue #191, pointed out by @RebeccaWPerry

**Comment by danielballan** [comment]
This can be addressed when we rework at the feature-finding API, #257.
