### ISSUE TITLE
doc on readthedoc

### ISSUE THREAD

**Issue by sciunto** [soft-matter/trackpy#248]
Hi,

the page on https://trackpy.readthedocs.org/en/latest/# is not updated any more. Since it seems to be replaced by https://soft-matter.github.io/trackpy/, I think it's less confusing if readthedoc is deleted :)

**Comment by tacaswell** [comment]
Indeed!

It _is_ trying to update, but we have picked up too many dependencies that they do not support so we have like 200 failed documentation builds!

I tried to make all of the docs over there inactive/private, but that doesn't seem to be working.

I am :+1: on deleting readthedocs, but don't want to unilaterally do it.

**Comment by nkeim** [comment]
I'm for it too. For a project the size of trackpy, one documentation website is enough!

**Comment by danielballan** [comment]
Agree

**Comment by tacaswell** [comment]
Deleted. @sciunto Thanks for kicking us to do something about this.
