### ISSUE TITLE
DOC: Some functions not rendered as hyperlinks

### ISSUE THREAD

**Issue by nkeim** [soft-matter/trackpy#255]
On the [API reference](http://soft-matter.github.io/trackpy/api.html) page, function names embedded in the text (such as `link_df()` and `link_df_iter()` at the top of the page) do not work as hyperlinks to the detailed documentation.

**Comment by danielballan** [comment]
Piggybacking on this issue, I also noticed that the "Motion Analysis" section of the docs is completely empty. Must be a sphinx error crept in. I'll try to fix this today.

**Comment by danielballan** [comment]
We are not alone here, it turns out. This is a major bug that was introduced in sphinx. See shoyer's comment: https://github.com/sphinx-doc/sphinx/pull/1828#issuecomment-110239004

**Comment by danielballan** [comment]
OK, the sphinx bug has been fixed but not yet released. Use sphinx v1.2.3 to build our docs until a version greater than 1.3.1 is available.

Docs have been fixed and uploaded.
