### ISSUE TITLE
Drift command and trjectory plotting

### ISSUE THREAD

**Issue by fayazr** [soft-matter/trackpy#258]
In trackpy I am unsure of the use of the tp.compute_drift(t) command, I am calculating the trajectory for a rotating object using the bubble track tutorial. However, the x,y values are fluctuating and the drift values are similar to the values I need. After subtraction of the drift, the original trajectory disappears and I get some random motion.

**Comment by danielballan** [comment]
> the drift values are similar to the values I need

Do you mean that, in your case, the coordinated motion -- the motion extracted by `compute_drift` -- is the motion of interest?

**Comment by fayazr** [comment]
The rotation you see in a sinusoid all motion in a part of the disc. The motion increases to a maximum and decreases to zero in one direction and then the same motion in opposite direction. I wanted to know the velocity dx and dy, but unfortunately it gives wrong values. But the drift values agree to the sinusoid all wave pattern of velocity variation. So I wanted to know how the drift was calculated and if there is any way to rectify the fx and ft values from being incorrect.

**Comment by fayazr** [comment]
Sorry not fx and dt, dx and dy values,

Thanks!!!!

**Comment by danielballan** [comment]
The drift calculation assumes uniform translation -- no rotation and no
stretching. If you are interested in extending it to cope with rotation, I
think that would be useful to others as well. (I could have used this in my
grad work, but I never got around to it.)

The relevant code is here:
https://github.com/soft-matter/trackpy/blob/master/trackpy/motion.py#L134

**Comment by fayazr** [comment]
Thanks, I am trying to understand the methods implemented in trackpy, it will take sometime. I will try to make contributions once I have a complete picture.. You guys have done a great job!.. :)

**Comment by fayazr** [comment]
Is there any publication of the Crocker–Grier algorithm?

**Comment by danielballan** [comment]
http://physics.nyu.edu/grierlab/methods3c/
