### ISSUE TITLE
Are we ready to tag v0.3.0rc1?

### ISSUE THREAD

**Issue by danielballan** [soft-matter/trackpy#266]
There are a few outstanding items on the v0.3 milestone, but they all relate to build issues (conda), docs, and trackpy-examples. How do we feel about a release candidate this weekend, aiming to tag the final v0.3.0 by mid-September?

I'm not forgetting the discussion around a minor tweak to logging, which could sneak in before the final v0.3.0 or go into v0.3.1. I also want to look at `GOOD_ENOUGH_THRESH` in light @caspervdw's fix to the test suite, but I think that could wait for v0.3.1 as well.

I am hopeful that trackpy will follow the general trend in the scientific Python community toward more frequent minor releases. Conda and versioneer make this less time-consuming than it used to be.

Thoughts?

**Comment by nkeim** [comment]
I heartily agree. The major changes that break API compatibility or significantly change output are all in place, so what's left in the pipeline can wait until v0.3.1 — unless `GOOD_ENOUGH_THRESH` is a trivial fix, in which case it should go in now because it does affect output.

More frequent *major* releases seem appropriate to me, if we keep having good science ideas like the ones in v0.3. I think that we could justify being on v0.5 or v0.6 at this point. So if something's standing in the way of making that painless, we should be sure to identify it.

**Comment by danielballan** [comment]
Tagged! The release candidate is available on pip:

```
pip install trackpy==0.3.0rc1
```

and conda, built for Python 2.7 and 3.4:

```
conda config --add channels soft-matter  # so that conda finds pims in the main channel
conda install -c soft-matter/channel/dev trackpy python=3.4  # or 2.7
```

Let's not announce widely ("soft matter software" mailing list, Twitter, etc.) until the docs and examples are fixed up a little more.

**Comment by danielballan** [comment]
P.S. @nkeim I agree. I think the main barrier is deciding how to group changes that break user code and then writing release notes. Tagging the RC, building, and pushing just took me about 45 minutes.

**Comment by nkeim** [comment]
Thanks. Perhaps we should start requiring that pretty much any PR add a bullet point at the top of the release notes? Not only will it give the release-tagger a head start, but it will help us to decide whether it's time for a new release.

**Comment by danielballan** [comment]
I like that policy. Pandas generally insists on that. And when it seems a
bit onerous (say, a novice user's first contribution, or a fly-by
contribution from someone who we don't want to pester) whoever merges it
can just add a commit locally and push.

**Comment by nkeim** [comment]
OK, I'm on board. I'm counting on the other core devs to hold me to it!
