### ISSUE TITLE
User "census"?

### ISSUE THREAD

**Issue by nkeim** [soft-matter/trackpy#271]
For most if not all of the core contributors, trackpy can be considered part of our professional output, which means that measuring its impact helps justify our efforts. Especially for assistant professors. A [Google Scholar search](https://scholar.google.com/scholar?hl=en&q=%22trackpy%22&btnG=&as_sdt=1%2C5&as_sdtp=) turns up 11 results, which is pretty good! (The core contributors are authors on just 5 of those papers, in case you were curious.) However, I suspect there is more usage that we're not seeing — work where trackpy went uncited, work in preparation, uses outside of research, etc. Since trackpy is such a young project, it seems important to consider these users as well.

As we prepare to announce v0.3, would it be worthwhile to attempt a census of trackpy users? Something like

> This release represents a tremendous amount of effort by several developers over the past year (thanks!). For the core developers especially, trackpy is a professional activity, and we hope it can stay that way. So we need to keep track of the impact trackpy is having. Citations measure only part of this impact, so **if you consider yourself a trackpy user, please take 15–60 seconds to let us know!**

And there would be a link to a Google form (or whatever) asking for

- Affiliation
- Name
- How are you using trackpy?
- Do you have any publications or conference presentations that used trackpy?
- Do you have any general comments or feedback for the trackpy developers? (Please note: this is not the place to request a specific feature or report a bug. Instead, create an issue on github.)

The form can stress that **all fields are optional** except the first, and that we'll publicly use this information only in the aggregate (as in, "trackpy is used by at least N researchers at M different organizations").

What do you think? Too much? Is there a better channel? Or should we just keep pushing for more citations?

**Comment by tacaswell** [comment]
:+1: for including a survey in the announcement.  I would also include a python version and install vector questions.

I think all of the fields can be optional.  We should run the form by @doraf before we send it out as she has experience designing this sort of thing?

**Comment by danielballan** [comment]
Good ideas all around. This reminds me that IPython may soon give a us a
way to collect more detailed usage info (opt-in, of course). But we
shouldn't wait for that.

**Comment by caspervdw** [comment]
I completely agree with your ideas. A google doc seems the easiest way to go, I guess we can analyze them by hand.

**Comment by ghattab** [comment]
Which brings us to the question of how to cite it in a scientific paper..
I guess then one cites the original IDL paper and refers to the trackpy module implementation / GitHub link ?!

Such as for the Bubble tracking in 2D foams [example](https://soft-matter.github.io/trackpy/tutorial/custom-feature-detection.html) for which consistency can then be problematic.

An explicit mention of trackpy is only present in ref. \[5\]: ```51D. B. Allan, T. A. Caswell, and N. C. Keim, “Trackpy v0.2,” (2014), doi:10.5281/zenodo.9971, https://github.com/soft-
matter/trackpy.```

**Comment by danielballan** [comment]
In case you haven't already discovered it, see [citing trackpy](http://soft-matter.github.io/trackpy/introduction.html#citing-trackpy) in our documentation.

Citing open software is an unsolved problem. For reproducibility, it's best to cite the individual versions, and this is what we are currently asking people to do. For author credit, it would be nice if these citations could somehow be cumulative; this is a problem that citation counting systems will have to address some day.

I encourage you to also cite the Crocker-Grier IDL paper.

**Comment by ghattab** [comment]
Indeed, just desired to mention it. It's always better to have more than not enough citations.

**Comment by nkeim** [comment]
Follow-up: We got 2 responses from core contributors, and 2 responses from users previously unknown (to me, at least). As a reminder to those following this project: you can go to [this Google form](https://docs.google.com/forms/d/1QqneHh1r_8O90so-LbITUVY--3Xen8tfKcc-2AYf6Oo/viewform) and just fill out your name and organization, or even just your organization. The more people we know use trackpy, the more we can all work on it!
