### ISSUE TITLE
Warning when using `tp.subpx_bias`

### ISSUE THREAD

**Issue by caspervdw** [soft-matter/trackpy#273]
Something with pandas and plotting, we should fix the warning message when you use `tp.subpx_bias`

`C:\Anaconda3\lib\site-packages\pandas\tools\plotting.py:3227: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "is being cleared", UserWarning)`

**Comment by tacaswell** [comment]
Because you shouldn't be using pandas plotting at all :wink:
