### ISSUE TITLE
__version__ on Windows returning 0+unknown

### ISSUE THREAD

**Issue by apiszcz** [soft-matter/trackpy#276]
If I perform the following steps in Linux the version is correctly reported as 0.3rc1.
git clone https://github.com/soft-matter/trackpy
pip install -e trackpy

When I copy the trackpy folder to a windows system an import trackpy I get 0+unknown.

Reviewing _version.py it seems a .git folder is required to locate the version in git_versions_from_keywords.

**Comment by tacaswell** [comment]
What do you mean by 'copy the trackpy folder to a windows system'?

**Comment by apiszcz** [comment]
I copied the trackpy folder (installed on linux) to a windows 7 system. I
perform import trackpy and 0.3rc1 works for my application, except
trackpy.__version__ returns 0+uknown.

**Comment by tacaswell** [comment]
Don't do that, or at least make sure you copy the hidden folders as well.  It might work better if you don't use `-e` which installs and editable version (so soft links).

The simplest solution is to just clone it on the windows side as well.

**Comment by apiszcz** [comment]
Thanks.
If I copy the entire folder over I end up with 116MB and 163 files instead of ~238KB and 19 files, however it reports the version correctly 0.3.0rc1. It seems like a lot of extra space (~500x) and files to obtain the version which is not an execution path of the primary codes purpose.

**Comment by tacaswell** [comment]
That size in primarily in the test images, and the history there of.  

Closing as this isn't a trackpy bug.

**Comment by apiszcz** [comment]
The .git/objects/pack/pack-* files are 98MB and required for the trackpy.__version__ to be reported correctly. If the either of these files are removed the unknown result is returned for the version.

![capture](https://cloud.githubusercontent.com/assets/1430861/9981756/fec088c4-5f93-11e5-9feb-572a82f74de3.JPG)

**Comment by nkeim** [comment]
Noted. The only solution I see, and a pretty radical one, is to erase those files from history.

**Comment by tacaswell** [comment]
We went through this discussion before and decided to accept that we have some large binaries in our past but the cost of re-writing history to remove them is too high to justify doing it.

I am not surprised that removing any of them breaks git as those files are git's internal data storage.  I suspect that _all_ of the history data is actually contained in that file.

**Comment by apiszcz** [comment]
Concur, this time I verified it file by file. For some situations carrying
around 100MB (uncompressed) may not be worth the version number. I am
'guessing' nothing else will be affected by dropping the .git folder. It is
the first package I have used that requires .git files.
​

On Mon, Sep 21, 2015 at 11:12 AM, Thomas A Caswell <notifications@github.com

**Comment by tacaswell** [comment]
It only requires them you do a source install, if you do a normal install (`pip install .`) it will extract the version information once and then you will not need the VC information.
