### ISSUE TITLE
FYI: Pandas 0.17rc1 warnings with trackpy 0.30rc1

### ISSUE THREAD

**Issue by apiszcz** [soft-matter/trackpy#282]
C:\p\lib\trackpy\trackpy\linking.py:748: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  features.sort('particle', inplace=True)

**Comment by nkeim** [comment]
Thanks for reporting this! `sort_values` is not even in Pandas 0.16.2, so we cannot truly "fix" this without dropping compatibility with the current stable release.

If it turns out that Pandas can be instructed to suppress these warnings (except during testing), would that be wise?

**Comment by nkeim** [comment]
If you want to see the changes required to get zero `FutureWarning`s from [Pandas 0.17.0rc1](http://pandas.pydata.org/#release-candidate-september-11-2015), see https://github.com/nkeim/trackpy/tree/pandas-0.17-future

**Comment by apiszcz** [comment]
Thanks, Pandas 0.17rc1 deprecates a few areas, and I've add similar if
statements for initial testing. I can probably start testing this branch at
some point.

https://github.com/soft-matter/trackpy/compare/master...nkeim:pandas-0.17-future
​

**Comment by apiszcz** [comment]
I copied over your changes for the 5 file, initial test is good with pandas 0.17rc1. Is there a way I can monitor your pandas 0.17 branch for future updates?

**Comment by nkeim** [comment]
There may be a way to do that on Github. I myself don't plan on updating that branch at all until we're comfortable dropping Pandas 0.16, which I would guess is roughly a year from now.

**Comment by apiszcz** [comment]
Thanks, this page has a list of 0.17 api conversion issues:
http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#backwards-incompatible-api-changes
​

**Comment by apiszcz** [comment]
Note I've switched to 0.17 and will provide feedback as out on the edge. ​

**Comment by danielballan** [comment]
Thanks, @apiszcz.
