### ISSUE TITLE
Increase Penalty for Creating New Tracks

### ISSUE THREAD

**Issue by pfigliozzi** [soft-matter/trackpy#283]
I was wondering if there is any option to increase the penalty for creating new tracks when linking particles together. I am trying to link particles together that rotate around in a ring however, sometimes the leading particle will be flagged as a 'new track' while the trailing particles take the identity of the particles in front of it. The frames where this issue arises each have the same number of particles so ideally each particle moves to a candidate in the next frame.

I have written a custom prediction function (one that will predict the next position of a particle based on some user defined angular velocity) but I still sometimes encounter the issue of new tracks being created.

**Comment by tacaswell** [comment]
The penalty for making a new track is tightly linked to the maximum search range, just pushing that up (and maybe using the adaptive logic?) would help.

Is the ring fixed in the image?  It might be worth doing some pre-processing to covert your `(x, y, t) -> (\theta, t)`.  If there are multiple rings of particles moving around it might be worth doing a clustering step to find the rings, track _those_, and then just track the particles in a single cluster which is (hopefully) small enough you can make the search range huge and just brute force the problem.

Also, my standard-non-helpful answer to bad tracking, take frames twice as fast :stuck_out_tongue_winking_eye: .

**Comment by nkeim** [comment]
Very interesting idea! Gaining particles is not penalized at all, but losing a particle is. The size of this penalty is `search_range`. You can read the Crocker & Grier paper cited in the documentation for details, but my understanding is that the penalty is as large as it needs to be; increasing it will not change the behavior of the algorithm. More concretely, the algorithm evaluates a set of possible links as determined by `search_range`; if the link that you want is not among the possible links (i.e. a distance greater than `search_range`), simply increasing the penalty will not fix the problem.

My advice is to follow @tacaswell 's advice :smile:.

An interesting theoretical question: If the number of particles is truly conserved *and* feature identification is perfect, is Crocker-Grier the best algorithm?

**Comment by pfigliozzi** [comment]
Thanks for the tips! I will try some of those things out!

**Comment by tacaswell** [comment]
Another interesting thing would be to run the tracking on your frames _backwards_.  @nkeim is pointing out an asymmetry I was completely glossing over.

I think making the penalty for losing a particle bigger without increasing the search range would break things as there could be a particle in your data set, but outside of the neighborhood considered which would lead to a better link configuration than the selected on  (but I am getting a bit tied up trying to work through that logic yay combinatorics!).

**Comment by tacaswell** [comment]
ps can we see and image? :8ball:

**Comment by pfigliozzi** [comment]
I wrote a function to help me visualize the tracked trajectories. The colors represent a unique track, red circles are particle locations, the green circle is a particle location that is new/of interest. This is an example of they type of issues I am trying to solve. For this data search_range = 100, memory = 1. The size of the pixels in the image is the same as the raw data.

[View Gallery Here](http://imgur.com/a/TGIef)

**Comment by nkeim** [comment]
Thanks. If you have only 5–10 particles, you can make `search_range` arbitrarily large and still get good performance. Especially if your Python distribution includes numba.
