### ISSUE TITLE
ENH/API: Assign integer particle IDs.

### ISSUE THREAD

**Issue by nkeim** [soft-matter/trackpy#296]
trackpy currently assigns particle IDs during linking as floats. As per @caspervdw in #293, it would be better to use integers for semantic reasons (and to accommodate 10^19 unique particles?). This would involve changing ~1 line of code in `link_df` and `link_df_iter`.

I think of this as an API change; there is conceivably code out there that this would break. So I'm creating this with a target of v0.4.

**Comment by danielballan** [comment]
:+1:

**Comment by caspervdw** [comment]
Just wanted to mention #330 here. We should adapt the tests in `test_motion` too when we change this.

**Comment by caspervdw** [comment]
This is done and tested in the new linking implementation. Closing
