### ISSUE TITLE
ENH: Add least-squares feature identification

### ISSUE THREAD

**Issue by nkeim** [soft-matter/trackpy#297]
This is more of a long-term goal. It is possible to refine feature locations not by weighted averaging, but by least-squares fitting with a model of how all _n_ particles should appear. This was developed by Mark Shattuck's group for close granular packings; there is a tutorial (and Matlab code) [here](http://gibbs.engr.ccny.cuny.edu/technical/Tracking/ChiTrack.php). And you can also check out a [paper](http://link.aps.org/doi/10.1103/PhysRevE.75.051311) that uses the technique successfully.

I wanted to create an issue because I hope that someday a user will contribute this to trackpy. Maybe you!

**Comment by caspervdw** [comment]
This would be a great addition! I already have a python code that uses `scipy.optimize.curve_fit` to fit a sum of N gaussians, using masking just as trackpy does. This works nicely for clusters of gaussian-like features (tested for N < 10).

A similar method called SFF: [article](http://www.sciencedirect.com/science/article/pii/S0001868607001200)
