### ISSUE TITLE
RLS: Time to release v0.3?

### ISSUE THREAD

**Issue by nkeim** [soft-matter/trackpy#301]
It's been two months since v0.3rc1. The only open issues tagged for v0.3 are #200 and #286, both of which can be easily moved to v0.3.1. Are we ready to go?

If so, we have to 

- [x] Polish the release notes
- [x] Write a mailing list announcement and post it here (including a part for #271)
- [x] Set up versioned sphinx docs on Github pages (#182)
- [x] Follow the rest of the [checklist](https://github.com/soft-matter/trackpy/wiki/Release-Checklist)

I think @danielballan knows more about the versioned docs. I *might* have time to do the rest in the next several days.

**Comment by danielballan** [comment]
Sounds good to me. I don't have a clear plan for versioned docs yet, but
maybe we can postpone that for 0.3.1 as well. The current docs are aimed at
0.3.0.

**Comment by caspervdw** [comment]
Agreed, let's put it out. Only thing that I would like to add:

- [ ] Release PIMS 0.3.2

**Comment by nkeim** [comment]
Here's a draft of the announcment. Release notes revisions pending.

*Subject:* ANNOUNCE: trackpy and pims releases

We're pleased to announce a major release of trackpy (v0.3), and a minor release of the movie-reading package pims (v0.3.2). The trackpy release is strongly recommended for all users, as it brings major improvements in speed and 3D feature-finding, and many other functionality and accuracy improvements.

### Survey

This release represents a tremendous amount of work by several contributors over the past year. For the core contributors especially, trackpy is a professional activity. We hope it can stay that way, so we need to gauge the impact of trackpy. If you consider yourself a trackpy user, please take 15–60 seconds to let us know by going to http://bit.ly/1Q2xTfg 

### Upgrading

Please be sure to read the [trackpy release notes](http://soft-matter.github.io/trackpy/whatsnew.html) before upgrading, especially the item under "Enhancements" about calculating masses. You may have to make minor edits to your scripts and notebooks to use them with v0.3.

Finally, if you have not been keeping up with pims, the v0.3.x series brings enhancements to 3D, features for slicing and processing movies, and a new reader for the StreamPix format.

If you are an Anaconda user, upgrading is as simple as "conda update -c soft-matter trackpy". Other methods are shown on the [installation page](http://soft-matter.github.io/trackpy/installation.html). The source for both packages is available on github (https://github.com/soft-matter).

------------

As always, the "soft-matter" [GitHub site](https://github.com/soft-matter) is the place to report bugs and ask questions about these projects.

Best wishes,
The Trackpy Contributors
(Including Dan Allan, Thomas Caswell, Nathan Keim, and Casper van der Wel.)

**Comment by danielballan** [comment]
Looks good. Maybe link, with thanks, to the full list of contributors,
which github maintains for us:
https://github.com/soft-matter/trackpy/graphs/contributors

**Comment by caspervdw** [comment]
Looks good, may want to mention the Bioformats addition for pims, many microscopy users will want to use that.

**Comment by caspervdw** [comment]
Shall we fix the pims dependency to >=0.3.2? I am not sure what will break if people use pims 0.2, and it is untested.

**Comment by danielballan** [comment]
I think so. In order to not interfere with modern numpy/numba, I will upload the first round of pims v0.3.2 conda packages without tifffile and PyAV built in. I'll add them back once they are built, advancing the conda build number but not the version number.

**Comment by danielballan** [comment]
We are closing in! No open issues are awaiting a PR. I marked many minor PRs for 0.3.0 just now.

@nkeim, would you have time to do this honors this weekend? I'll make the conda packages if you make the PyPI distribution. Deal?

**Comment by nkeim** [comment]
@danielballan Hooray! But my time will be scarce this weekend, so I won't be able to put out any fires should the need arise. Today, tomorrow, or Monday are actually more realistic.

**Comment by danielballan** [comment]
I'm fine with today or tomorrow. We are ready.

And if something goes wrong it wouldn't be the first time we cranked out
emergency micro-release(s). The real cost of a release is coordinating API
breakages and release notes. Outside of that, it's not so bad.

Ping me when PyPI is done, and let me get the versioned docs and the conda
packages straightened out before you send the poll to the mailing list.

**Comment by danielballan** [comment]
P.S. Did you catch @tacaswell's suggestion to use twine in place of python setup.py sdist upload? I have no experience with it so I did not add that to the release checklist. Up to you whether to try it out.

**Comment by nkeim** [comment]
Looks like twine is worth a try. I've added it to the checklist so I don't forget.

I ran `nosetests` one more time before proceeding and it failed. Working on that…

**Comment by tacaswell** [comment]
I just did a MPL release so all of that is fresh in my head.  I can do the incantations to facilitate the release if you all do the hard work of sorting out what needs to be done code wise :smiling_imp:

**Comment by danielballan** [comment]
@nkeim Make sure you have pillow < 3.

**Comment by nkeim** [comment]
Yes, pillow 3.0.0 was the problem. But since `conda create -n testanaconda python=3 anaconda pims` gets me pillow 3.0.0, won't this be a problem for lots of users?

**Comment by danielballan** [comment]
The conda-recipe for pims does not pin pillow. I will revise that and then
rebuild the pims packages before I build the new trackpy packages.

**Comment by caspervdw** [comment]
We should also document the incompatibility with pillow < 3 in the 'known issues' section. I will make a PR

**Comment by nkeim** [comment]
Thanks! Sorry for not catching that earlier.

**Comment by caspervdw** [comment]
See #322  and also https://github.com/soft-matter/pims/pull/200

**Comment by nkeim** [comment]
Thanks for the offer, @tacaswell ! But since it's quitting time on the East Coast, I'm going to go ahead unless you jump in right now.

**Comment by nkeim** [comment]
OK, PyPI is updated; `pip install trackpy` gets v0.3.0 and tests pass. conda away!

Also [published the release on GitHub](https://github.com/soft-matter/trackpy/releases/tag/v0.3.0). Feel free to edit the description.

I updated the URLs in the announcement to point to the "0.3.0" docs, in anticipation of the final docs build.

- [ ] Rebuild docs and file under "0.3.0"
- [ ] Tag 0.3.0 release of trackpy-examples

**Comment by danielballan** [comment]
Excellent! I will do my part with a clear head tomorrow.

**Comment by tacaswell** [comment]
:+1: everyone.

**Comment by danielballan** [comment]
Docs are up. /trackpy/ redirects to /trackpy/stable (likewise for pims) and full paths for dev/... stable/... and 0.3.0/... are all resolved correctly. I think /stable should probably be the recommended path for sharing links.

**Comment by danielballan** [comment]
Conda packages are up, including new ones for pims that pin pillow < 3.

```
$ conda create -n trackpy3 -c soft-matter trackpy
Fetching package metadata: ......
Solving package specifications: .......................
Package plan for installation in environment /Users/dallan/miniconda/envs/trackpy3:

The following NEW packages will be INSTALLED:

    cycler:          0.9.0-py35_0      
    decorator:       4.0.4-py35_0      
    freetype:        2.5.5-0           
    jpeg:            8d-1              
    libpng:          1.6.17-0          
    libtiff:         4.0.2-1           
    matplotlib:      1.5.0-np110py35_0 
    networkx:        1.10-py35_0       
    numpy:           1.10.1-py35_0     
    openssl:         1.0.2d-0          
    pandas:          0.17.0-np110py35_0
    pillow:          2.9.0-py35_0      
    pims:            0.3.2-py35_2      
    pip:             7.1.2-py35_0      
    pyparsing:       2.0.3-py35_0      
    pyqt:            4.11.4-py35_0     
    python:          3.5.0-1           
    python-dateutil: 2.4.2-py35_0      
    pytz:            2015.7-py35_0     
    pyyaml:          3.11-py35_1       
    qt:              4.8.7-1           
    readline:        6.2-2             
    scikit-image:    0.11.3-np110py35_0
    scipy:           0.16.0-np110py35_1
    setuptools:      18.4-py35_0       
    sip:             4.16.9-py35_0     
    six:             1.10.0-py35_0     
    slicerator:      0.9.4-py35_0      
    sqlite:          3.8.4.1-1         
    tk:              8.5.18-0          
    trackpy:         0.3.0-py35_1      
    wheel:           0.26.0-py35_1     
    xz:              5.0.5-0           
    yaml:            0.1.6-0           
    zlib:            1.2.8-0    
```

**Comment by nkeim** [comment]
Splendid!! OK to send the announcement?

**Comment by danielballan** [comment]
Yeah, only the zenodo thing is left to do. Send it!

**Comment by caspervdw** [comment]
Great work! 

The zenodo thing should work, there should be a setting inside zenodo so that catches every release. Also it should be configured as a webhook at the github repo.

There is something wrong in de plotting api reference, I thought I solved that in #322... You sure you have that commit @danielballan?

**Comment by danielballan** [comment]
Yeah, I'm all synced up. I thought of that in particular before I rebuilt
the docs. I'll look into it.

Zenodo has worked previously, so maybe it just takes a little time to
register.

**Comment by caspervdw** [comment]
Thought so, just checking :) I have a weekend full of rehearsals so I wont have time this weekend to check on it.

**Comment by nkeim** [comment]
Unless there are objections, I'm going to wait until Monday morning to send the announcement. Friday evening seems like a bad time to ask people to fill out a survey…

**Comment by danielballan** [comment]
Haha, good call. And that gives the whole weekend to discover any dumb
deployment-related mistakes.

**Comment by caspervdw** [comment]
The Zenodo things seem to be all right, only at https://pypi.python.org/pypi/trackpy there is still an old badge. Can somebody with rights on pypi change this?

**Comment by nkeim** [comment]
Fixed. I also fixed some RST formatting and removed the Travis badge. Sorry to have been hasty about that earlier.

**Comment by nkeim** [comment]
Well, I think that wraps up v0.3. Congratulations and thanks, everyone!!
