### ISSUE TITLE
FFTW ?

### ISSUE THREAD

**Issue by apiszcz** [soft-matter/trackpy#302]
In the past enabling the diagnostic displayed numba and fftw information.
I'm testing with Python 3.5, see numba, but not fftw. I am probably missing a library, scikit-image, pyfftw is available.

Yes, but could it be faster?
FAST: numba is available and enabled (fast subnets and feature-finding).

**Comment by nkeim** [comment]
FFTW is no longer relevant to most users. See the release notes and #219.
