### ISSUE TITLE
Documentation/link issue

### ISSUE THREAD

**Issue by apiszcz** [soft-matter/trackpy#303]
Referenced from: http://soft-matter.github.io/trackpy/tutorial/walkthrough.html#optional-high-performance-components-numba-and-fftw

LINK missing
https://trackpy.readthedocs.org/en/latest/reference/trackpy.feature.html

**Comment by nkeim** [comment]
Thanks. See also @RobWardNZ 's comment in #298. Flagging this as a v0.3 issue.
