### ISSUE TITLE
FYI: PANDAS and 'autoload', and identified problem with numexpr 2.4.4 on Windows

### ISSUE THREAD

**Issue by apiszcz** [soft-matter/trackpy#307]
I had a recent issue that took some time to track down. In case this group should experience it. The issue is KNOWN to be numexpr 2.4.4 and on Windows only when using many cores, >16, the problem is that math errors occur due to a race condition. Initially I thought it was PANDAS 0.17 since I was NOT loading numexpr for use. It actually took a while and many error sessions to isolate because the race condition was only occurring about 1 to 1.4% of the time using the exact same input data. The failure always occurred in the first two pandas dataframe rows, values are set to x.x-e315. I learned that PANDAS autoloads any modules they support and autoenables capabilities like numexpr on ordinary expression like df[t]+=1.0 .... So even if you are not crafting numexpr vector operation strings, it will try and succeed for your code.

I could not produce the error with <16 cores. Which made the investigation less than fun.

2.4.6 is out and 'should' correct the issue. I will test soon, in the meantime I dropped back to 2.4.3
FYI
https://github.com/pydata/numexpr/issues/188

**Comment by nkeim** [comment]
Yikes! Thanks for the public service!
