### ISSUE TITLE
Non fatal issues

### ISSUE THREAD

**Issue by Resonanz** [soft-matter/trackpy#312]
I have come across these when using my slightly modified walkthrough code when running from the command line (rather than thru iPython notebook):

`/Users/resonanz/anaconda/lib/python3.4/site-packages/matplotlib/image.py:649: UserWarning: The backend (<class 'matplotlib.backends.backend_macosx.RendererMac'>) does not support interpolation='none'. The image will be interpolated with 'nearest' mode.
  "mode." % renderer.__class__)
/Users/resonanz/anaconda/lib/python3.4/site-packages/pandas/tools/plotting.py:3299: UserWarning: To output multiple subplots, the figure containing the passed axes is being cleared
  "is being cleared", UserWarning)`

`/Users/resonanz/anaconda/lib/python3.4/site-packages/trackpy/linking.py:496: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  features.sort(['particle', t_column], inplace=True)`

`/Users/resonanz/anaconda/lib/python3.4/site-packages/pandas/core/index.py:4281: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return np.sum(name == np.asarray(self.names)) > 1
/Users/resonanz/anaconda/lib/python3.4/site-packages/trackpy/motion.py:55: FutureWarning: icol(i) is deprecated. Please use .iloc[:,i]
  results['N'] = 2*disp.icol(0).count(level=0).div(Series(lagtimes))`

**Comment by danielballan** [comment]
Thanks for the report! We are aware of the second one (#299).

For the first, we should use `interpolation='nearest'`. For the third, we should follow the recommendations in that warning. Would you be able to take the time to make a pull request to address these issues?

**Comment by caspervdw** [comment]
The multiple subplots one was also fixed in #277.
