### ISSUE TITLE
batch question: empty frames

### ISSUE THREAD

**Issue by apiszcz** [soft-matter/trackpy#318]
In some data sets I have blank frames, is there a method to keep track of empty frames from the batch call? 
Perhaps using the 'meta' parameter?
I can probably handle this by creating a list of missing 'frame' numbers from the sequence.

**Comment by caspervdw** [comment]
You can get a list of all non-empty frames with `features.frame.unique()` and then check for missing ones.

**Comment by nkeim** [comment]
See also the discussion in #292 pertaining to linking.

**Comment by danielballan** [comment]
Building on @caspervdw's answer... if it isn't obvious, you could then use `set` and `np.arange` to make checking for missing ones easy.

I don't think we are going to add more complexity to `batch`. We could throw something in the docs about this though. Like the pandas cookbook, a collection of short, handy recipes would be nice to have.

**Comment by caspervdw** [comment]
I think this issue is solved as we are not going to give DataFrames metadata.
