### ISSUE TITLE
ENH: Store image size metadata with features

### ISSUE THREAD

**Issue by Resonanz** [soft-matter/trackpy#320]
I think it would be useful if the orientation of the video frames and the trajectory plots was the same.  At the moment on the walkthrough code that I have been using the plots can be confusing due to the flipping over of the trajectory plot wrt the video frame.  Also the trajectory plot is x and y trimmed to fit the tracked particles rather than left with the same dimensions as the video file.  This is especially noticeable when the video frame has a few particles near the middle of the frame.  In this case the two representations are barely recognisable, in my case at least.

**Comment by nkeim** [comment]
As for orientation: Are you using v0.3? This should be fixed. See #195.

You will need to set the plot limits manually; trackpy currently does not pass metadata from feature-finding to linking to plotting (via the DataFrames). I'll leave this open as a feature request.

**Comment by caspervdw** [comment]
Would be great to also have the calibration (microns-per-pixel, frames-per-second) as metadata on the DataFrame. I find myself quite often messing around with the units of the position columns.

**Comment by danielballan** [comment]
I remember discussions about DataFrame metadata. As with numpy array metadata, the difficulty is how to propagate it through various operations. Unfortunately, it was generally agreed that monkey-patching DataFrames with metadata is a bad idea.
