### ISSUE TITLE
Zenodo DOI does not seem to have been generated for 0.3.0

### ISSUE THREAD

**Issue by danielballan** [soft-matter/trackpy#326]
According to the release checklist and my recollection, this is supposed to happen automatically when releases are made on GitHub. Does anyone have time to look into this?

**Comment by tacaswell** [comment]
It might only be visible to @nkeim as he created the tag.

**Comment by caspervdw** [comment]
If it would only be visible for the author, it wouldn't make much sense to make the DOI anyway.... I think there is something wrong with either the github webhook or the zenodo settings.

**Comment by nkeim** [comment]
@danielballan , you will want to sign into Zenodo via GitHub OAuth, then look at the "GitHub" settings for your account. Is trackpy turned on? It is not in my account, but it should be in yours.

**Comment by danielballan** [comment]
It's off. I'm sure it was on previously, but it's been more than a year. Who knows. I added a note to the release checklist. I'll leave this issue open until one of us has time to manually upload the package to Zenodo and generate a DOI the non-automatic way.

**Comment by caspervdw** [comment]
I can do it. Who are we going to list as authors? Just the four of us or anyone that made a commit? I'm not sure on this one. I think the default is anyone that made a commit. But we could make a difference on writing 1 line and writing 60000 lines.

**Comment by nkeim** [comment]
Great question. My guess is that at least for the next few years, the list of contributors will not become completely unmanageable. And I'm not sure we want to exercise the authority required to just leave people off the list. On the other hand, some do deserve more credit than others.

Just brainstorming about it, I can think of 3 solutions:

1. List only the core contributors, plus any contributor we deem to have contributed a significant chunk of functionality. This is probably closest to authorship norms in soft matter physics.
2. List the "lead authors" (core contributors?) alphabetically, followed by everyone else, alphabetically. This is the standard used by some medium-sized collaborations. Hard for a reader to figure out, but it gives a way for the collaboration to recognize greater effort.
3. List everyone, in alphabetical order. If you have enough names, the alphabetical order will be obvious, and no one will make assumptions about who contributed more.

I think 2 and 3 are both good ideas. I like 2 more in the short- and medium-term.

**Comment by caspervdw** [comment]
Zenodo also offers a 'Contributors' field, next to the authors. I am not sure how exactly that will display, but it gives us the opportunity to acknowledge contributors while keeping the list of responsible authors short.

Following general guidelines about authorship (for instance http://www.pnas.org/site/authors/journal.xhtml, article 2), it would make more sense to only list the core contributors as authors, but we should acknowledge all contributors.

**Comment by danielballan** [comment]
I am comfortable with that. If anyone outside of the core contributors is reading along, please feel free to speak up.

**Comment by caspervdw** [comment]
Ok, I can get the names from the user profiles. 

@apiszcz if you'd like to be listed as a contributor, could you give us your name and affliation? As in https://zenodo.org/record/12255#

**Comment by caspervdw** [comment]
And @nkeim, @tacaswell, do you agree with this? Authors: core contributors ; Contributors: all others that pushed commits to trackpy

**Comment by nkeim** [comment]
Yes, for this release, major contributors = core contributors = people with write access to the repo.

**Comment by tacaswell** [comment]
:+1:

**Comment by apiszcz** [comment]
Al Piszcz, The Mitre Corporation

**Comment by caspervdw** [comment]
Thanks, I updated the readme.md and published the DOI on Zenodo: http://dx.doi.org/10.5281/zenodo.34028. Closing.

**Comment by danielballan** [comment]
@caspervdw Can you update the table in `introduction.rst`?

**Comment by caspervdw** [comment]
@danielballan Done
