### ISSUE TITLE
Anaconda Python 2.7 Trackpy 0.3 spyder problem

### ISSUE THREAD

**Issue by GerhardSchneider** [soft-matter/trackpy#327]
If you use conda create -n trackpy27 -c soft-matter trackpy spyder
spyder is not able to load the IPython console in spyder
import matplotlib.cbook as cbook   fails

conda create -n trackpy35 -c soft-matter python=3.5 trackpy spyder
the IPython console is working without problems

Is there a dependency problem?

Thank you in advance!

Gerhard Schneider

**Comment by danielballan** [comment]
The conda packages for 2.7 and 3.5 are built from the same recipe, and the recipe does not use any conditionals based on the version of Python. Are there any spyder users reading this who might know what to check?

**Comment by nkeim** [comment]
The way Anaconda includes the various pieces of The Package Formerly Known as IPython has changed since IPython 4.0, and there may be some edge cases. Do you have the same problem with `conda create -n test spyder`?

**Comment by GerhardSchneider** [comment]
No, that's the reason I wrote to that list.
Spyder with a larger amount of packages is working well, only with trackpy even the minimum installation is making troubles..

**Comment by GerhardSchneider** [comment]
Thank you!
As a workaround  
conda create -n trackpy27 -c soft-matter trackpy spyder matplotlib=1.4.3  
did the job.
matplotlib:       1.4.3-np110py27_2

**Comment by GerhardSchneider** [comment]
> You should probably take this up with the spyder folks.

They know it :(
https://github.com/spyder-ide/spyder/issues/2793
