### ISSUE TITLE
Documentation Links Error

### ISSUE THREAD

**Issue by apiszcz** [soft-matter/trackpy#328]
I am getting '404' errors on
http://soft-matter.github.io/trackpy/dev/tutorial/walkthrough.html
http://soft-matter.github.io/trackpy/

**Comment by danielballan** [comment]
That second one is bad! This was working recently and I have no pushed to
the repo since. Very confusing. Will investigate when J get to my desk.

**Comment by danielballan** [comment]
I added an empty commit to our docs repo and re-pushed. We are back. I don't think we were down for more than ~16 hours, when I last saw the docs.

Thanks for the quick alert, @apiszcz. I'm not sure what happened. We'll keep an eye on it.
