### ISSUE TITLE
Tests is failing on pandas 0.17.1

### ISSUE THREAD

**Issue by caspervdw** [soft-matter/trackpy#329]
I commited directly to master with the change of the Zenodo DOI ( #326 ) . That triggered Travis and the latest-version testcase failed because of the recent release of pandas.

Another reason why not commit to master directly. Sorry about that :S I will look into it today.

**Comment by caspervdw** [comment]
Closing through #330

**Comment by danielballan** [comment]
No worries. It's a right of passage to break master. :- )
