### ISSUE TITLE
Travis error: PyFFTW

### ISSUE THREAD

**Issue by caspervdw** [soft-matter/trackpy#339]
Travis is erroring on the PyFFTW download from anaconda:

    Error: MD5 sums mismatch for download: https://conda.anaconda.org/soft-matter/linux-64/pyfftw-0.9.2-np18py27_0.tar.bz2 (2898a378840ba43e6d120ce8cf3ec2e5 != 7f6b58a784abaa4df41e886637e6ebd5)

    Error: MD5 sums mismatch for download: https://conda.anaconda.org/soft-matter/linux-64/pyfftw-0.9.2-np19py34_0.tar.bz2 (2898a378840ba43e6d120ce8cf3ec2e5 != 83ce15739d67b01343e1ce3f6213f0b2)

Only on np18py27 and np19py34, others are fine. See #337

**Comment by caspervdw** [comment]
To be clear: this is an issue with our own builds on the soft-matter channel. 

A solution could be: stop supporting pyfftw builds from soft-matter, remove the dependency from travis builds. If users want to use the legacy bandpass function with pyfftw acceleration then they would need to build it themselves.

**Comment by tacaswell** [comment]
did one of us push up new versions or is someone man-in-the-middle attacking us?

@danielballan is sitting next to me and denies responsibility

**Comment by caspervdw** [comment]
I don't believe that I have write access to the conda channel.

**Comment by caspervdw** [comment]
Another one in https://github.com/soft-matter/pims/pull/220, ffmpeg :

    Error: MD5 sums mismatch for download: https://conda.anaconda.org/soft-matter/linux-64/ffmpeg-2.2.4-0.tar.bz2 (71d7a55d5ca8452ae4d402e19d093a8a != 0fcb9843d8b164ca6574f2a8bc8af2cc)

What's going on? Could the files be corrupted by some conda server error? If you look at the file dates at https://anaconda.org/soft-matter/pyfftw/files, then you see that there are no new versions uploaded.

**Comment by danielballan** [comment]
Must be. That is worrying. I will try re-pushing when I have the bandwidth to revisit this.

**Comment by tacaswell** [comment]
Are we doing any caching on travis?

**Comment by caspervdw** [comment]
The issue seemes to have solved itself, tests pass again.
