### ISSUE TITLE
Benchmark scipy 0.17 vs. 0.16

### ISSUE THREAD

**Issue by danielballan** [soft-matter/trackpy#340]
scipy 0.17 landed today with "[significant performance improvements in cKDTree](https://github.com/scipy/scipy/releases/tag/v0.17.0)". We should benchmark and make a note in the docs if we see a big speed increase.

**Comment by nkeim** [comment]
Great! I will check in a couple weeks to see if this release has made it to conda yet.

My hopes are not high — cKDTree is usually not a major driver of performance (or lack thereof). But it will be worth a look.

**Comment by apiszcz** [comment]
Interesting, I had a quick look at Ball Tree and KDTree in another regard, probably worth posting here.

@66million, BALL Tree gives 11% improvement in performance at 4.8% increase in memory requirement, finishing 7 minutes sooner than KD-Tree.

@6million BALL Tree is 23% faster.


BTW: On another issue I bumped in to photoutils, it 'may' have some utility for certain use cases wrt to trackpy, however frame to frame performance may be an issue.

**Comment by apiszcz** [comment]
BTW: I'm testing/running with PANDAS 0.18, no new issues from Trackpy 'so far'.

**Comment by caspervdw** [comment]
I think these benchmarks are not really going to happen anymore
