### ISSUE TITLE
Matplotlib artist.py deprecated

### ISSUE THREAD

**Issue by Resonanz** [soft-matter/trackpy#341]
I notice on Daniel's trackpy walkthru page that there is a warning with the MSD plotting as shown below.  I am also receiving this warning on my PC. Thanks.

```
/Users/dallan/miniconda/envs/py3/lib/python3.4/site-packages/matplotlib/artist.py:221: MatplotlibDeprecationWarning: This has been deprecated in mpl 1.5, please use the
axes property.  A removal date has not been set.
  warnings.warn(_get_axes_msg, mplDeprecation, stacklevel=1)
```

Thomas appears to have addressed this here: http://matplotlib.1069221.n5.nabble.com/MatplotlibDeprecationWarning-td46462.html

**Comment by tacaswell** [comment]
That particular warning might be fixed in 1.5.1, I missed an (obfuscated) internal call that is exercised by pandas plotting code.

**Comment by Resonanz** [comment]
I have just updated matplotlib as follows:

```
The following packages will be UPDATED:

    matplotlib: 1.5.0-np110py34_0 --> 1.5.1-np110py34_0
    numpy:      1.10.1-py34_0     --> 1.10.2-py34_0    
    openssl:    1.0.2d-0          --> 1.0.2e-0         
    pip:        7.1.2-py34_0      --> 8.0.1-py34_0     
    python:     3.4.3-2           --> 3.4.4-0          
    requests:   2.8.1-py34_0      --> 2.9.1-py34_0     
    setuptools: 18.5-py34_0       --> 19.4-py34_0      
    sqlite:     3.8.4.1-1         --> 3.9.2-0  
```

and the problem is still there.

Also a few lines earlier in trackpy is this code:

`em = tp.emsd(tm, micronsPerPixel, frameRate)`

which gives a deprecated warning:

```
/home/resonanz/anaconda3/lib/python3.4/site-packages/trackpy/motion.py:55: FutureWarning: icol(i) is deprecated. Please use .iloc[:,i]
  results['N'] = 2*disp.icol(0).count(level=0).div(Series(lagtimes))
```

**Comment by caspervdw** [comment]
This latter issue (with `emsd`) was fixed in #313; it is in the latest trackpy version (v0.3)

It might be a good idea to drop all pandas plotting routines and do it ourselves. In that way we have more control.

**Comment by Resonanz** [comment]
Mmmm, pretty sure I am running the latest trackpy...

**Comment by caspervdw** [comment]
To be sure, could you just print `trackpy.__version__` ? Because in v0.3, I cant find any `icol`.

**Comment by Resonanz** [comment]
Thanks for pointing that out.  I am on version 0.2.4 -- my bad :-(  I should try to figure out how to update trackpy...

**Comment by Resonanz** [comment]
IIRC I may have had problems installing 0.3.0 using conda so was using pip instead.  pip install --upgrade trackpy failed to correctly update to 0.3.0 today so I tried using conda install -c soft-matter trackpy again and this time it has installed 0.3.0 correctly which is really nice !!!  So thanks!!!

The new 0.3.0 version seems to be processing frames quite a lot faster than 0.2.4 (or am I imagining it?).

**Comment by nkeim** [comment]
Not your imagination! :smile:

You should probably check out the [release notes](http://soft-matter.github.io/trackpy/0.3.0/whatsnew.html) — there are a lot of changes.

**Comment by caspervdw** [comment]
What kind of errors did you get with the update?

**Comment by Resonanz** [comment]
Hi Casper, I don't remember now -- it was months ago.  But it seems to be all okay now :-)

Nathan, yes, certainly seems to be cranking thru the frames much faster than previously.  

I have read the release note, so thanks!

**Comment by caspervdw** [comment]
The deprecation warning is not a trackpy issue: closing
