### ISSUE TITLE
Upside down plotting

### ISSUE THREAD

**Issue by Resonanz** [soft-matter/trackpy#343]
I think that the trajectory plots flip my video frames so that the top is at the bottom and the bottom is at the top. e.g. [0,0] in the trajectory plot is bottom-left while [0,0] in my video frames is probably being taken as top-left.  This makes it confusing to follow which particles are doing what (yeah, sometimes this really is useful) so I am wondering if this is known or deliberate or just me? Thanks.

**Comment by caspervdw** [comment]
There was an inconsistency between `annotate` and `plot_traj` in 0.2.4, which was solved in 0.3. In 0.2.4, annotate displays upside-down (origin at bottom left) and plot_traj displays correctly (origin at top left).

Are you using 0.2.4 and does upgrading to 0.3 help?

If not, could you try something like this and see if this works out for you:

    import matplotlib.pyplot as plt
    import trackpy as tp    
    ax = plt.gca()
    tp.plot_traj(...., ax=ax)
    ax.invert_yaxis(True)

**Comment by caspervdw** [comment]
Closing through https://github.com/soft-matter/trackpy/pull/357
