### ISSUE TITLE
New particles are not tracked

### ISSUE THREAD

**Issue by leifmos** [soft-matter/trackpy#344]
To whom it may concern, 

I try to track particles that float into the field of view.
trackpy only tracks the particles that are present on the very first image.
particles that leave the field of view are done. - that's ok.
But particles that enter the field of view won't get a new trajectory ...

Is it meant to be this way?
Or am I doing it wrong?

Thanks in advance,
Mats

**Comment by tacaswell** [comment]
Can you provide an example?  It should be looking for new features in each frame.

**Comment by leifmos** [comment]
sorry, for my late response, 

while I was trying to provide you with more information I found out, that the indices after 
```
tracks=tp.link_df(df,MAX_DIST,memory=MAX_MEMORY)
tracks_minlength=tp.filter_stubs(tracks,MIN_TRACK_LENGTH)
```
are not continuous ... 

So i was just checking how many particles were found:
`number_of_cells=self.tracks_minlength['particle'].nunique()`

and than I assumed that the indices must be like:
`range(number_of_cells)`

Long story short: **Indices are are not continuous. ** In my eyes that can cause misunderstandings as in my case. Now my problem is solved. I get the indices by:
```
TTT=np.array(tracks_minlength)
INDICES=list(set(TTT[:,3])) 
```

I am sorry for that! I am not familiar with panda DataFrames - I use numpy arrays whenever possible.

Thanks for your support and this powerful tool!
Best, 
Ma

**Comment by tacaswell** [comment]
Closing this as there is not really a bug in trackpy.

I strongly suggest you learn to use pandas.  The results of feature tracking do map very well on to the tabular data structures that pandas provides.   It really does simplify many common operations (ex, getting new data frame with the average (x, y) of each track is a one liner) and is heavily used in trackpy intenals.

By 'indicies' here I think you mean 'particle id' (pandas has it's own idea of 'index').  It would be far _more_ confusing if a filter operation also re-labeled the tracks.
