### ISSUE TITLE
trackpy differences in results on Mac and PC

### ISSUE THREAD

**Issue by Resonanz** [soft-matter/trackpy#346]
I have python 3.5 installed on 3 machines: a windows 10 pc, a mac desktop and a mac laptop. The pc uses VMware Workstation + debian to run conda and trackpy.  The laptop has Parallels and debian to run conda and trackpy.  I have 3 setups to spread the processing for lots of files.

All of the machines have been set up using conda in a python 3.5 env and have trackpy 0.3.0.

Taking 500 frames of video (expt41, my ref.), identically on all three machines, the macs give the same results, and the pc slightly different. So far it appears that:
- loading video
- detecting particles on the first frame
- plotting the mass distribution for the first frame

are all identical.  The differences appear on the:
- sub pixel bias plots in which the macs are identical but slightly different to the pc.

Processing all frames results in an identical count of 17 trajectories.  Applying the ephemeral filter however has the mac on 40:27 (before:after) and 38:27 on the pc. The MSD fitting results are identical for all machines.

Next dataset (expt20, my ref.) shows similar differences with subpixel and trajectories 478:223 (before:after, mac) and 479:224 (pc).  The n and A values are identical when rounding to 3 s.f. -- there are slight differences between the macs and the pc and the macs are totally identical.

**Comment by tacaswell** [comment]
You should look into ipyparallel to help with job distribution.

These are 'modern' macs with intel chips? Are they all 64 bit?  what versions of numpy / scipy are you using everywhere?
