### ISSUE TITLE
Upgrading to Pandas 0.18.0 causes trackpy errors

### ISSUE THREAD

**Issue by vivarose** [soft-matter/trackpy#354]
My travis build (https://github.com/soft-matter/trackpy/pull/352#issuecomment-199969738) failed.

Pandas 0.16.2 works with trackpy. I'm not sure whether Pandas 0.17 works.

**Comment by caspervdw** [comment]
Thanks for the report! This is a pandas / numpy bug (https://github.com/pydata/pandas/issues/12600), luckily it doesn't break our code but only two of our tests: I think we can come up with a workaround for the tests.
