### ISSUE TITLE
Release 0.3.1

### ISSUE THREAD

**Issue by caspervdw** [soft-matter/trackpy#360]
There are some bugfixes that should be released in the near future. I marked them in the milestone. The only extra thing is writing the release notes.

Possibly, we should have a look at the automatic doc build (the sooner the better). I put out the issue on https://github.com/soft-matter/pims/issues/232, I am not really into encryption but it should be easy to get it running via a deploy key.

**Comment by danielballan** [comment]
We at BNL have been working on this on and off as well, and @ericdill is close to having a solution with the same pattern we want for soft-matter.

**Comment by danielballan** [comment]
^ RE: the auto-building docs, that is.

**Comment by caspervdw** [comment]
I thought the doc building has been solved already?

**Comment by danielballan** [comment]
<blink> Yep. Totally forgot about where we discussed this recently. My bad!

**Comment by caspervdw** [comment]
No problem! Let's finish this release soon :)

**Comment by caspervdw** [comment]
Done! Zenodo is lagging still, it should come up at https://zenodo.org/record/55143

**Comment by nkeim** [comment]
🎉 Thanks!!

**Comment by caspervdw** [comment]
@danielballan  can you do the conda packaging?

**Comment by caspervdw** [comment]
FYI I updated the release checklist with the Zenodo and doc changes.

**Comment by danielballan** [comment]
I uploaded conda packages to soft-matter/main for all platforms x Python versions 2.7, 3.3, 3.4, 3.5. I tested the 2.7 and 3.5 OSX packages manually, and all seems well.

Eventually we should direct our users to conda-forge, but I'd like to see that stabilize for a couple more months.
