### ISSUE TITLE
Anaconda Install?

### ISSUE THREAD

**Issue by apiszcz** [soft-matter/trackpy#369]
FYI

[anaconda3] C:\Users\a>conda install -c soft-matter trackpy
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: Could not connect to https://conda.anaconda.org/soft-matter/noarch/
Could not connect to https://conda.anaconda.org/soft-matter/win-64/
.Could not connect to https://repo.continuum.io/pkgs/pro/noarch/
.Could not connect to https://repo.continuum.io/pkgs/pro/win-64/
.Could not connect to https://repo.continuum.io/pkgs/free/noarch/
.Could not connect to https://repo.continuum.io/pkgs/free/win-64/
..
Solving package specifications: .
Error:  Package missing in current win-64 channels:
  - trackpy

You can search for this package on anaconda.org with

    anaconda search -t conda trackpy

**Comment by danielballan** [comment]
That looks like a connection problem on your system. The [win64 builds](https://conda.anaconda.org/soft-matter/win-64/) are all there.
