### ISSUE TITLE
Detection of objects via weighted center of brightness values of pixels

### ISSUE THREAD

**Issue by milenkorz** [soft-matter/trackpy#371]
Is it possible to detect objects with weighted center of brightness of pixels (“center of mass”)? This is often necessary, when the objects have another shape than Gaussian like?

**Comment by nkeim** [comment]
Do you mean a COM that is off-center? Is it possible to attach an image file?

**Comment by caspervdw** [comment]
Just for clarity, trackpy uses 'center of mass' subpixel refinement, not gaussian fits.
