### ISSUE TITLE
tp.scatter not defined

### ISSUE THREAD

**Issue by Resonanz** [soft-matter/trackpy#383]
Adding tp.scatter(f) to the walkthru code results in:

AttributeError: module 'trackpy' has no attribute 'scatter'

**Comment by caspervdw** [comment]
This function was introduced on v0.3.0. Which version are you on? (`trackpy.__version__`)

**Comment by caspervdw** [comment]
@Resonanz I also leave this to you to close if it is solved in v0.3.0 / v0.3.1
