### ISSUE TITLE
Irrelevant legends

### ISSUE THREAD

**Issue by Resonanz** [soft-matter/trackpy#386]
One some plots in the Walkthrough, small legends appear that are not really relevant to the plots (see attached). I think that these should be turned off by default. A similar legend appears on the mass-vs-size plot.

![frame 0 features filter-mass-size-ecc](https://cloud.githubusercontent.com/assets/6218191/17089118/2be0be42-5277-11e6-8794-7197bf011752.png)

**Comment by caspervdw** [comment]
I recall this has been fixed in 0.3.1. Could you confirm once you get it installed?
