### ISSUE TITLE
Tracking now fails in both 0.3.0 and 0.3.1 after recent Anaconda upload

### ISSUE THREAD

**Issue by kmdouglass** [soft-matter/trackpy#389]
Hi everyone,
I have a set of unit tests in my software for checking that tracking is performed correctly. These tests were working without problems with trackpy 0.3.0 for a couple of months until yesterday when the 0.3.1 build was pushed onto the Anaconda Cloud. Now they fail, seemingly because particles in different frames are not being merged onto the correct trajectories. The really crazy thing is that forcing Anaconda to use trackpy 0.3.0 *also* causes the tests to fail now. Am I making some kind of stupid mistake, or is tracking now broken in both versions?

# Expected behavior
An assertion error is not raised in the following code. This would mean that the two distinct particle trajectories were correctly identified.

```
import pandas as pd
import trackpy as tp

df = pd.DataFrame({'x' : [10, 20, 0, 100, 0, 110, 90, 90, 20, 110], 'y' : [10, 20, 20, 100, 0, 110, 110, 90, 0, 90], 'frame' : [0, 1, 2, 2, 3, 3, 4, 5, 6, 6]})

mergedDF = tp.link_df(df, 25, memory = 2)

# There should be only two distinct values in the particles column: 0 and 1
assert mergedDF['particle'].max() == 1
```

# Actual behavior
The assertion fails because mergedDF['particle'].max() is 9. Every point is considered a distinct particle.

Thanks!

**Comment by kmdouglass** [comment]
I am attaching a diff output of `conda list` for my two different conda environments. The DataSTORM environment is working as expected whereas the tp30 environment is raising the assertion seen above.

(My apologies that DataSTORM has a lot more packages installed than tp30.)

[diff.txt](https://github.com/soft-matter/trackpy/files/385543/diff.txt)

**Comment by danielballan** [comment]
Thanks for the thorough report.

I can reproduce your problem. Downgrading pandas to <0.18 (and, with it, scipy and numpy) restores correct behavior. The conda packages aren't the issue; it is reproducible with conda- or pip- or source-installed trackpy. Given where it occurs, I suspect pandas is to blame. I will keep digging.

We *are* testing on pandas v0.18.1 on Travis ([see here where the 0.3.1 tag passed](https://travis-ci.org/soft-matter/trackpy/jobs/146454556#L602)) and I would sure hope that our test suite is sufficient to catch a bug this important.

**Comment by kmdouglass** [comment]
Just to clarify, did you downgrade to Pandas less than 0.18.0, or did pandas == 0.18.0 work as well?

I tried only specifying Pandas 0.18.0 when I built a new conda environment just now but still get the incorrect behavior.

I also performed a `conda list` on the very last environment I installed on one of our lab machines where everything is working properly. The output is attached. You can see that it's using pandas 0.18.1.

What a headache... :/

[working_env.txt](https://github.com/soft-matter/trackpy/files/388195/working_env.txt)

**Comment by danielballan** [comment]
I downgraded to less than 0.18.0. It's possible that one of the other deps (scipy, numpy, numba) is to blame, but downgrading pandas to `<0.18.0` got the right set of deps, whatever that is.

**Comment by caspervdw** [comment]
Is there any chance that #356 describes this issue? In pandas 0.18.0, `np.round` errors on a dataframe or series object. In the travis test we dont test 0.18.0 for that reason. Still, the code should work, only the tests trigger the pandas bug.

**Comment by danielballan** [comment]
I can reproduce on 0.18.1.

**Comment by caspervdw** [comment]
Ah that's right, should have read more carefully.

I *think* the issue is caused by scipy 0.18.0. I am currently in the process of publishing my code for tracking overlapping features and similar linking tests do not pass on scipy 0.18.0 and do pass on scipy 0.17.1. No clue why, also after a quick glance at the [release notes](http://docs.scipy.org/doc/scipy/reference/release.0.18.0.html).

**Comment by danielballan** [comment]
Thanks again for the report, @kmdouglass.
