### ISSUE TITLE
The v0.3.1 conda packages are ~136 MB

### ISSUE THREAD

**Issue by danielballan** [soft-matter/trackpy#390]
This might be due to a known conda bug or maybe we're just shipping our test data and we shouldn't be. Note to self to look into this and rebuild v0.3.1 yet again.

**Comment by caspervdw** [comment]
The problem is in `info\recipe` : it contains all the other compiled packages. This grows with a factor 5 at each python version: Py33 contains 5 Py27 packages, Py34 contains 5 Py33, containing in total 25 Py27 packages.

**Comment by danielballan** [comment]
Odd! This is the build script I used for 0.3.1 and (just now) for 0.3.2.

```bash
#!/bin/sh
VERSIONS="27 33 34 35"

for VERSION in $VERSIONS; do
    conda build . --python=$VERSION;
    TARBALL_PATH=$(conda build . --python=$VERSION --output);
    TARBALL_NAME=$(basename $TARBALL_PATH);
    conda convert $TARBALL_PATH --platform=all;
    binstar upload win-32/$TARBALL_NAME -u soft-matter;
    binstar upload win-64/$TARBALL_NAME -u soft-matter;
    # binstar upload osx-64/$TARBALL_NAME -u soft-matter;
    binstar upload linux-32/$TARBALL_NAME -u soft-matter;
    binstar upload linux-64/$TARBALL_NAME -u soft-matter;
done
```

The accumulation problem is still there, though for whatever reason less severe:
```
$ du -h ~/miniconda/conda-bld/osx-64/trackpy-0.3.2*
108K	/Users/dallan/miniconda/conda-bld/osx-64/trackpy-0.3.2-py27_0.tar.bz2
648K	/Users/dallan/miniconda/conda-bld/osx-64/trackpy-0.3.2-py33_0.tar.bz2
3.8M	/Users/dallan/miniconda/conda-bld/osx-64/trackpy-0.3.2-py34_0.tar.bz2
 23M	/Users/dallan/miniconda/conda-bld/osx-64/trackpy-0.3.2-py35_0.tar.bz2
```

conda just put out a new major release of conda-build (2.0.0). When the dust settles from that release I'll revisit the question.

**Comment by caspervdw** [comment]
Hmm maybe a temporary solution would be emptying the `info\recipe` folder in the loop?

**Comment by caspervdw** [comment]
Or try the `--no-include-recipe` switch at `conda build`!

**Comment by danielballan** [comment]
Solution was to move the recipe into a subdir. New v0.3.2 packages (with incremented build number that should always take precedence over old ones) are uploaded. They are all 108-109 KB.

**Comment by caspervdw** [comment]
Nice! Thanks @danielballan
