### ISSUE TITLE
Test suite broken for v0.3.1 (Archlinux)

### ISSUE THREAD

**Issue by sciunto** [soft-matter/trackpy#392]
Hi,

I'm trying to upgrade the archlinux package for trackpy. The test suite doesn't pass, python 2.7 or 3.5, same struggle.
I also tried in a venv (all the dependencies must be up-to-date).
```
pip install numpy scipy pandas six matplotlib pyyaml pims
python setup.py develop
nosetests trackpy
```

Here is the output: http://pastebin.com/nDuZH714

I can provide more details if needed. I have not tried to downgrade some dependencies or to investigate more... actually, I'm a bit surprised to see all these failure whereas you test your code thoroughly with travis.

**Comment by caspervdw** [comment]
Thanks for the report @sciunto. Sorry for the late response, I guess many of us are or have been on a summer break. 

This is indeed very strange indeed, as the travis tests pass. I suspect pandas or the way we are implementing pandas. Which pandas version did you use? The newest that was tested is 0.18.1, which passed on travis [here](https://travis-ci.org/soft-matter/trackpy/jobs/146454556). Also something to consider: we always test with numba present.

The linking tests that are failing in your report are also present in v0.3.0. Do they pass there for you? If so, then it would narrow down the source of the issue greatly.

**Comment by caspervdw** [comment]
@sciunto , I reproduced your test report, the culprit was the recent scipy 0.18.0. See the referenced PR for a workaround.

**Comment by sciunto** [comment]
Thanks @caspervdw I'm waiting for your new release to upgrade the package.

**Comment by sciunto** [comment]
thanks @caspervdw @danielballan 0.3.2 is packaged for archlinux :)

**Comment by danielballan** [comment]
Thanks, @sciunto
