### ISSUE TITLE
Walkthrough code error?

### ISSUE THREAD

**Issue by Resonanz** [soft-matter/trackpy#395]
Something in the Walkthrough code that has struck me as odd for quite a while is that the filtering code eventually gets to the following, with the result in t2:

```
condition = lambda x: ((x['mass'].mean() > 250) & (x['size'].mean() < 3.0) &
                       (x['ecc'].mean() < 0.1))
t2 = tp.filter(t1, condition)  # a wrapper for pandas' filter that works around a bug in v 0.12
```

Yet all the imsd, emsd, n and A, etc. after the code above uses the unfiltered t1 rather than t2.  Is this an oversight or deliberate?  Why go to the effort of filtering only to use the unfiltered particle data to produce the final results?

Thanks !

**Comment by Resonanz** [comment]
Also, this seems to be broken, and the n and A value are no longer displayed in the Walkthrough.

```
/Users/dallan/miniconda/envs/py3/lib/python3.4/site-packages/matplotlib/artist.py:221: MatplotlibDeprecationWarning: This has been deprecated in mpl 1.5, please use the
axes property.  A removal date has not been set.
  warnings.warn(_get_axes_msg, mplDeprecation, stacklevel=1)
```

**Comment by nkeim** [comment]
These problems seem to have been fixed by the time of https://github.com/soft-matter/trackpy-examples/pull/44 . I'm closing this issue.
