### ISSUE TITLE
question (or feature request?)

### ISSUE THREAD

**Issue by alexlib** [soft-matter/trackpy#397]
what shall I do to plot the position of the tracked particles versus time, e.g. 2D plot of t['x'] vs t['frame'] with color coded (and maybe labeled) trajectories? 

would be a feature to develop?

**Comment by caspervdw** [comment]
Thanks for your question! I think this is something that can be done with `matplotlib`, without need of any complicated functions. You will need to group your trajectories by particle, and then separately plot the trajectories. Every new plot will be given a unique color by default.

    import matplotlib.pyplot as plt
    for index, particle in t.groupby('particle'):
        plt.plot(particle['frame'], particle['x'], label=index)
    plt.legend()

If you are new to matplotlib, [this](http://matplotlib.org/users/pyplot_tutorial.html#pyplot-tutorial) is a useful point to start.

**Comment by alexlib** [comment]
thanks

**Comment by caspervdw** [comment]
You're welcome!
