### ISSUE TITLE
Default value of smoothing_size

### ISSUE THREAD

**Issue by caspervdw** [soft-matter/trackpy#401]
The boxcar background subtraction introduces a bias for features that are closer than `smoothing_size` + feature diameter together. This is described in my paper on [arXiv](http://arxiv.org/abs/1607.08819), page 11, top paragraph.

In the crocker-grier paper, the boxcar size is defined as `2w+1`, in which w is one pixel larger than the feature radius. The same as our `diameter`. However, we use `2 * diameter + 1` as a default value for the boxcar subtraction. This is a clear difference with the CG algorithm.

I am not sure if this was a choice, or if this is just a programming bug. If we choose to change it, the bandpass function (over [here](https://github.com/soft-matter/trackpy/blob/master/trackpy/preprocessing.py#L59)), needs to be changed.

@nkeim do you know what the matlab code does exactly?

**Comment by nkeim** [comment]
In the Blair-Dufresne MATLAB code, boxcar is done with a 1D kernel of size 2`lobject`+1, where

```
%               lobject: (optional) Integer length in pixels somewhat 
%                       larger than a typical object. Can also be set to 
%                       0 or false, in which case only the lowpass 
%                       "blurring" operation defined by lnoise is done,
%                       without the background subtraction defined by
%                       lobject.  Defaults to false.
```

The default is to not do the boxcar at all. So that example is no help.

**Comment by caspervdw** [comment]
Then I am :+1: on sticking to the Crocker Grier paper. We absolutely need background subtraction, but the current value introduces a bias in closely spaced features.

**Comment by nkeim** [comment]
This sounds like a good idea, but ideally this should be grouped with other major changes. 0.4 or 0.5?

**Comment by caspervdw** [comment]
I think that together with the adapted gray dilation, the new linker, and the modular approach to `locate`, we are already heading for that. That would be v0.4.

**Comment by nkeim** [comment]
Right! Thanks. Assigning that milestone now.

**Comment by caspervdw** [comment]
Thanks!
