### ISSUE TITLE
Appveyor continuous testing

### ISSUE THREAD

**Issue by caspervdw** [soft-matter/trackpy#402]
Do you think it would be worthwhile to cover Windows use with tests using Appveyor? And it seems that OSX is supported by Travis?

I looked into Appveyor for the PyAV Windows build, so I now know more or less how it works.

On the other hand, we don't have nopython extensions except numba so things _should_ be pretty OS-independent.

**Comment by tacaswell** [comment]
It is worthwhile, but I would not say it is a high priority.
