### ISSUE TITLE
Travis is failing on Py3.5

### ISSUE THREAD

**Issue by caspervdw** [soft-matter/trackpy#403]
As the tests also fail in master, I am moving this to a separate issue.

@tacaswell  Do you understand why matplotlib is failing in the Py3.5 test? Is there something wrong in the conda dependencies?

    ImportError: No module named 'PyQt4'

https://travis-ci.org/soft-matter/trackpy/jobs/161115162

**Comment by tacaswell** [comment]
This is a packaging issue introduced upstream by contiuum, see https://github.com/ContinuumIO/anaconda-issues/issues/1068

**Comment by caspervdw** [comment]
Thanks. I guess we just have to rerun travis as soom as the issue is solved.
