### ISSUE TITLE
FYI: OVITO Trajectories

### ISSUE THREAD

**Issue by apiszcz** [soft-matter/trackpy#408]
http://ovito.org/manual/howto.visualize_particle_trajectories.html

FYI:
OVITO can visualize trajectory lines of individual particles as shown in the example movie on the right. A trajectory object is created using the Create trajectory lines utility as described in the following.

Procedure

Figure 10. The Create trajectory lines utility.

The Create trajectory lines utility.

The user interface of the utility (Figure 10) lets you select the set of particles for which to create trajectory lines (all or selected ones) and the time span over which the trajectory lines should be generated. The Unwrap trajectories option is useful when particles cross the boundaries of a periodic simulation cell.

Once you have made all settings, press the Create trajectory lines button. OVITO will now load each simulation frame one after another, sample the particle positions, and generate the trajectory lines. They are stored in a Particle trajectories object by OVITO, which is a new object added to the scene. The new trajectories object is automatically selected in the modification panel.

Figure 11. The trajectory display settings.

The trajectory display settings.

You can switch back and forth between the Trajectories and the Particles object using the scene object selector box (marked by a red circle in Figure 11). Alternatively, you can simpy click on a particle or on a trajectory line in the viewports to select the corresponding object.

The trajectory object is linked to the particles object it was created from. You may use the Regenerate trajectory lines button to update the trajectories if necessary, e.g., if the input simulation data has changed.

Procedure summary: You first use the Create trajectory lines utility to create a new trajectory object from the currently loaded simulation time series. You may then adjust the display settings for the newly created trajectory object as shown in Figure 11. Finally, you can switch back to the Particles object to continue working with the particles data, apply modifiers etc. The trajectory object is not affected by any changes made to the particles data unless you press the Regenerate trajectory lines button of the trajectory object.

Notes

**Comment by tacaswell** [comment]
Thanks.

Closing as there does not seem to be anything that needs to be done.
