### ISSUE TITLE
? Distance

### ISSUE THREAD

**Issue by apiszcz** [soft-matter/trackpy#417]
Has anyone considered adding a distance attribute between detections for a given particle?
Presumably this available during the nearest neighbor or other search result.
Thanks.

**Comment by caspervdw** [comment]
Do you mean the displacement distance of a particle between consecutive frames? That is indeed calculated inside the linking code.

**Comment by apiszcz** [comment]
Yes, I noticed the calculations, wondering if it could be considered for an
optional attribute in the output dataframe.

**Comment by nkeim** [comment]
It's complicated: that calculation measures the distance from the best guess, not the previous location. When prediction is enabled, those are different things. Nonetheless I think this would be valuable as part of the Linking Diagnostics feature.

For the true distance value, could we add a post-processing function that operates on the output of `link_df_iter()`? That way we could avoid adding an option to the linking functions. Pandas makes this operation relatively simple and efficient.

**Comment by apiszcz** [comment]
This is what I'm doing with pandas (post tracking) .shift() operator. I was
wondering if true distance was already available.

**Comment by caspervdw** [comment]
@apiszcz I think this issue is solved. Would be great if you could make a PR with a function that computes the displacements using `.shift()`
