### ISSUE TITLE
Unsatisfiable Error

### ISSUE THREAD

**Issue by Danilar** [soft-matter/trackpy#420]
I get this error when following the tutorial:

> (C:\Users\Intel\Anaconda3) C:\Users\Intel>conda update conda
> Fetching package metadata ...........
> Solving package specifications: .
> 
> # All requested packages already installed.
> # packages in environment at C:\Users\Intel\Anaconda3:
> #
> conda                     4.3.9                    py36_0
> 
> (C:\Users\Intel\Anaconda3) C:\Users\Intel>conda install -c soft-matter trackpy
> Fetching package metadata .............
> Solving package specifications: .
> 
> UnsatisfiableError: The following specifications were found to be in conflict:
>   - python 3.6*
>   - trackpy -> numba 0.12.2 -> llvmpy 0.12.3 -> python 2.6*
> Use "conda info <package>" to see the dependencies for each package.
> 
> (C:\Users\Intel\Anaconda3) C:\Users\Intel>

Any solution to that?

**Comment by caspervdw** [comment]
We don't support python 3.6 at the soft-matter channel, sorry about that. We have recently migrated to the conda-forge channel, but I believe even there 3.6 is unsupported. (You could give ``conda install -c conda-forge trackpy`` a try)

I recommend either using python 3.5, or if you really need 3.6, compiling packages yourself from PyPI (``pip install trackpy``)

**Comment by Danilar** [comment]
Hi,

Thanks for the rapid answer. Installing anaconda 3-4.0.0 (3.5) solved the issue.
