### ISSUE TITLE
Release for python 3.6?

### ISSUE THREAD

**Issue by sciunto** [soft-matter/trackpy#435]
Hi, 

This fix https://github.com/soft-matter/trackpy/commit/249629756bfcde2025cd173fef6cc7808b2feb71 is crucial for python 3.6. Otherwise, it craches...
I think it deserves a release.

**Comment by caspervdw** [comment]
Thanks for the heads up @sciunto. Tagging @nkeim @tacaswell @danielballan.

A next release will be a major one, for sure, as there are many significant output changes and API breaks in the current master. Before a next release, we should at least:

 - fix the conda-forge Py36 builds (#434).
 - add some `DeprecationWarnings` were applicable
 - be very clear in the docs about the API breaks

I'd prefer #414 to be finished before v0.4, but that could take another month or two so we could possibly go with the current master for v0.4 and put the rebased linkers in a next release.

**Comment by sciunto** [comment]
Thanks! I'm looking forward discovering this new version.

**Comment by danielballan** [comment]
What would you think about applying the patch highlighted by @sciunto above to v0.3.2 and release v0.3.3 with py3.6 conda packages? Then we can wait for #414 before v0.4.

**Comment by caspervdw** [comment]
Oh that's a good option too. I am not sure how to handle that (git-wise) but if you tag than I can distribute it this week.

**Comment by danielballan** [comment]
I have a branch at `danielballan:py36` with the back-ported patch and an updated .travis.yml to test against py3.6. Travis is down at the moment, so I'll have to revisit this later.

**Comment by caspervdw** [comment]
We need to get pims up and running for py36 first. I am working on that at https://github.com/conda-forge/pims-feedstock/pull/1

**Comment by danielballan** [comment]
Trackpy v0.3.3 tagged, "released" on GitHub, and available on PyPI. I leave the conda packages to you, @caspervdw. Thanks for wrangling slicerator and pims also.

**Comment by danielballan** [comment]
@sciunto Thanks again for highlighting this. Can we count on you for a new batch of arch packages? :-D

**Comment by sciunto** [comment]
sure! :)

**Comment by caspervdw** [comment]
@danielballan Thanks! You put a source wheel on Pypi? Conda will need a .tar.gz.

**Comment by danielballan** [comment]
@caspervdw Oops. Done.

**Comment by sciunto** [comment]
Arch updated as well. I close the issue :) Many thanks.

**Comment by caspervdw** [comment]
@danielballan PR is there for conda-forge

I updated the PKG-INFO at pypi, also. Remember next time to install pypandoc before doing a release ;)

**Comment by danielballan** [comment]
Yeah, I realized a second too late.

**Comment by caspervdw** [comment]
NP, thanks for the fast release!

Do you think we should make a new Zenodo tag? I personally think it is not necessary.

**Comment by danielballan** [comment]
Maybe we should do one Zenodo tag per minor release. On one hand it's good to let people cite exactly the version of the code they produced their results on; on the other it's nice to consolidate the citations a bit.

**Comment by caspervdw** [comment]
@danielballan  Agreed, for scientific purposes, a citation only needs to be precise up to updates that adapt core functionality or (quantitative) output.
Conversely, we will need to tag a minor release whenever we change one of those.
