### ISSUE TITLE
Suppressing warning for velocity field?

### ISSUE THREAD

**Issue by apiszcz** [soft-matter/trackpy#440]
I disabled the logging ( i hope ) and use -Wignore to start python.
I was thinking the the logger level would control what is emitted.

However this announcement still appears

lib\trackpy\predict.py:151: UserWarning: Could not generate velocity field for prediction: no tracks
  warn('Could not generate velocity field for prediction: no tracks')

predict.py : 151
            else:
                # Sadly, the 2 most recent frames had no points in common.
                warn('Could not generate velocity field for prediction: no tracks')

**Comment by nkeim** [comment]
That is odd. Logging should have nothing to do with whether you see the warning; the logging and warning subsystems are independent (unless you tie them together [like this](https://docs.python.org/3.6/library/logging.html#integration-with-the-warnings-module)). Nonetheless, using `-Wignore` should have suppressed the warning you are seeing. Is there any other code you are running (IPython?) that might be re-enabling warnings?

You can try [this pattern](https://docs.python.org/3.6/library/warnings.html#temporarily-suppressing-warnings) to be certain that warnings will be ignored.

I don't think this issue should require any changes to trackpy; in most contexts it would be unexpected to have zero tracks.

**Comment by apiszcz** [comment]
-Wignore was not in my active, shell , sorry for that , all set.
