### ISSUE TITLE
TypeError of compute_drift

### ISSUE THREAD

**Issue by pinghanchu** [soft-matter/trackpy#453]
Hi, Thanks for nice tutorial and package. It is very useful. 
However, I've run this walkthrough and found one doesn't work:

```python
d = tp.compute_drift(t1)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-36-2822576c24b1> in <module>()
----> 1 d = tp.compute_drift(t1)

.../anaconda/lib/python2.7/site-packages/trackpy/motion.pyc in compute_drift(traj, smoothing, pos_columns)
    265     del delta['frame']
    266     delta.reset_index('particle', drop=True, inplace=True)
--> 267     delta.reset_index('frame', drop=False, inplace=True)
    268     #delta.reset_index('frame', drop=True)
    269     dx = delta.groupby('frame').mean()

.../anaconda/lib/python2.7/site-packages/pandas/core/frame.pyc in reset_index(self, level, drop, inplace, col_level, col_fill)
   3053                 # to ndarray and maybe infer different dtype
   3054                 level_values = _maybe_casted_values(lev, lab)
-> 3055                 if level is None or i in level:
   3056                     new_obj.insert(0, name, level_values)
   3057 

TypeError: coercing to Unicode: need string or buffer, int found
```

--
I download the notebook from http://nbviewer.jupyter.org/github/soft-matter/trackpy-examples/tree/master/notebooks/

Thanks.
pinghan

**Comment by nkeim** [comment]
Thanks for the report. What versions are you using? You can find out with

```
import trackpy
import trackpy.diag

print trackpy.__version__
print trackpy.diag.dependencies()
```

**Comment by pinghanchu** [comment]
Thanks. Here is my version:

0.3.3

OrderedDict([(u'six', '1.10.0'), (u'numpy', '1.12.1'), (u'scipy', '0.19.0'), (u'matplotlib', '2.0.2'), (u'pandas', u'0.20.1'), (u'scikit-image', None), (u'pyyaml', None), (u'pytables', None), (u'numba', '0.33.0+0.ge79330a.dirty'), (u'pyfftw', None), (u'python', u'2.7.13')])

**Comment by danielballan** [comment]
What does `t1` look like?

**Comment by pinghanchu** [comment]
it looks the same as the tutorial.
![screen shot 2017-09-19 at 3 08 54 pm](https://user-images.githubusercontent.com/10731275/30615560-83d0dd28-9d4c-11e7-85e6-2cef116d849c.png)

**Comment by pinghanchu** [comment]
same as tutorial
![screen shot 2017-09-19 at 3 15 47 pm](https://user-images.githubusercontent.com/10731275/30615872-8230d71a-9d4d-11e7-92b2-b1f09eecfa7e.png)

**Comment by danielballan** [comment]
Hmm. Can you show us `t1.columns` and `t1.head()`?

**Comment by pinghanchu** [comment]
It looks okay.
![screen shot 2017-09-20 at 9 18 38 am](https://user-images.githubusercontent.com/10731275/30652125-cb030d40-9de4-11e7-8cdb-01cb80a3e1a0.png)

**Comment by danielballan** [comment]
I'm not sure what to make of that without being able to dig into it interactively. Can you export that `t1` DataFrame into some file format and share it here?

**Comment by pinghanchu** [comment]
I put the csv file as well as my code in my github:
https://github.com/pinghanchu/Particle_Tracking/blob/master/TrackPy/notebooks/walkthrough.ipynb
https://github.com/pinghanchu/Particle_Tracking/blob/master/TrackPy/notebooks/t1.csv

Basically, it is the example code.  I guess it's the setup or version I use is different now.

pinghan

**Comment by caspervdw** [comment]
Sorry for my late response. This issue is the same as #446 and is caused by pandas 0.20.1. Either upgrade pandas or checkout the latest dev version of trackpy and the issue should go away.

**Comment by pinghanchu** [comment]
great! it works now. thanks very much.

**Comment by danielballan** [comment]
Oh, great. Thanks Casper.
