### ISSUE TITLE
Trackpy-force

### ISSUE THREAD

**Issue by caspervdw** [soft-matter/trackpy#454]
I have published some code that I wrote for 'extracting forces from trajectories of Brownian particles'. I have taken the liberty to name the package trackpy-force (`tpforce`), as it is a typical particle tracking analysis.

It also goes with some unittests that are tested on Travis and a tutorial notebook, over [here](https://nbviewer.jupyter.org/github/caspervdw/trackpy-force/blob/master/tutorial/Trackpy%20-%20force%20tutorial.ipynb).

We may in time decide to merge this code into trackpy, however, as the code is rather extensive I guess it is better to let it evolve a bit on a seperate repo and then (maybe) merge it.

Tagging @rbnvrw as he is (most probably) the only other user of this code.

**edit**: the link to the repo is https://github.com/caspervdw/trackpy-force

**Comment by danielballan** [comment]
Very cool. I agree that a separate home makes sense so that trackpy-force can iterate quickly. Would you like to put in a PR linking it from the trackpy documentation? A section of "related projects" or something could make sense on the main page.
