### ISSUE TITLE
Pixel Datatype: float32

### ISSUE THREAD

**Issue by swarnak25** [soft-matter/trackpy#481]
```frames
Out[11]: 
<Frames>
Source: C:\Users\swarnak\TrackingWithPython\trackpy-examples-master\sample_data\bulk_water\*.png
Length: 300 frames
Frame Shape: (424, 640, 4)
Pixel Datatype: float32
```
a few days ago I got uint8 same as yours.Now I am getting this.How do I fix this?

**Comment by swarnak25** [comment]
images = (255 * np.array(frames)).round().astype(np.uint8)

**Comment by caspervdw** [comment]
This has to do with a change of the scikit-image `imread` backend of PIMS. Nothing we can do about it, but the following indeed converts a normalized float image to `unit8`. The pipeline trick makes the function evaluate lazily.
```
import pims

@pims.pipeline
def convert_to_uint8(image):
    return (image * 255).astype(np.uint8)

images = convert_to_uint8(frames)
```
