### ISSUE TITLE
0.4 enable_numba KeyError

### ISSUE THREAD

**Issue by apiszcz** [soft-matter/trackpy#485]
0.4, KeyError: 'trackpy.subnetlinker'

```
>>> import trackpy as tp
>>> tp_.__version__
'0.4'
>>> tp.enable_numba()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib\trackpy\try_numba.py", line 126, in enable_numba
    f.point_to_compiled_func()
  File "lib\trackpy\try_numba.py", line 86, in point_to_compiled_func
    setattr(sys.modules[self.module_name], self.func_name, self.compiled)
KeyError: 'trackpy.subnetlinker'
```

0.3.3, no error

```
>>> import trackpy as tp
>>> tp.__version__
'0.3.3'
>>> tp.enable_numba()
>>>
```

FYI
```
>>> import numba
>>> numba.__version__
'0.37.0'
>>> import llvmlite
>>> llvmlite.__version__
'0.22.0'
```

With 0.4 we have a linking folder, and the relative path to the module_name is 'trackpy.linking.subnetlinker'. However the path in self.module_name is 'trackpy.subnetlinker'.

```
(Pdb) self.module_name
'trackpy.subnetlinker'
(Pdb) sys.modules[self.module_name]
*** KeyError: 'trackpy.subnetlinker'
(Pdb) sys.modules['trackpy.linking.subnetlinker']
<module 'trackpy.linking.subnetlinker' from 'lib\\trackpy\\linking\\subnetlinker.py'>
```

Not sure, this appears to be missing the 'linking' folder in the path. However I tried adding 'linker' to the join statement, now center_of_mass is the keyerror as follows since it is in the root folder of trackpy

```
> c:\g\test\lib\trackpy\try_numba.py(70)__init__()
-> module_name = '.'.join(['trackpy', module_name])
(Pdb) module_name
'subnetlinker'
(Pdb) n
> c:\g\test\lib\trackpy\try_numba.py(71)__init__()
-> self.module_name = module_name
(Pdb) module_name
'trackpy.subnetlinker'

```

```
Traceback (most recent call last):
  File "tpntest.py", line 4, in <module>
    tp.enable_numba()
  File "lib\trackpy\try_numba.py", line 129, in enable_numba
    f.point_to_compiled_func()
  File "lib\trackpy\try_numba.py", line 89, in point_to_compiled_func
    setattr(sys.modules[self.module_name], self.func_name, self.compiled)
KeyError: 'trackpy.linking.center_of_mass'
```

**Comment by nkeim** [comment]
Interesting! What installation method for trackpy, and what version of numba?

On Apr 6, 2018, 2:18 AM -0700, apiszcz <notifications@github.com>, wrote:

VERSION 0.4`

``

import trackpy as tp
import trackpy.predict
from trackpy import diag as tpdiag
tp.enable_numba()
Traceback (most recent call last):
File "", line 1, in
File "lib\trackpy\try_numba.py", line 126, in enable_numba
f.point_to_compiled_func()
File "lib\trackpy\try_numba.py", line 86, in point_to_compiled_func
setattr(sys.modules[self.module_name], self.func_name, self.compiled)
KeyError: 'trackpy.subnetlinker'


0.3.3, no error


import trackpy as tp
tp.version
'0.3.3'
import trackpy.predict
from trackpy import diag as tpdiag
tp.enable_numba()

**Comment by apiszcz** [comment]
1. python setup.py build
2. COPY the build trackpy folder to a lib folder. (same processed used for
0.3.3)

**Comment by caspervdw** [comment]
Is `python setup.py install` a working solution for you?  You won’t need to copy manually then.

**Comment by apiszcz** [comment]
I normally 'copy' to install on various platforms, it seems like something may have changed between 0.3.3 and 0.4 on the path discovery.

**Comment by apiszcz** [comment]
If i install with setup.py i get the same error:
I am running on Windows.

>>> import trackpy as tp
>>> tp.enable_numba()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\g\test\lib\python\lib\site-packages\trackpy-0.4-py3.5.egg\trackpy\try_numba.py", line 126, in enable_numba
    f.point_to_compiled_func()
  File "C:\g\test\lib\python\lib\site-packages\trackpy-0.4-py3.5.egg\trackpy\try_numba.py", line 86, in point_to_compiled_func
    setattr(sys.modules[self.module_name], self.func_name, self.compiled)
KeyError: 'trackpy.subnetlinker'

**Comment by nkeim** [comment]
@apiszcz Would you mind trying #486? Either pull that branch or just copy and paste the new code.

**Comment by apiszcz** [comment]
YAML was due to a copy/paste, ignore that remark.

Tracking
Interesting, tracking is taking forever and now I have no status, so not sure how long it will take. 
I wonder if numba is actually enabled.

**Comment by nkeim** [comment]
We tried to restore status updates in a previous PR, but maybe we missed one. Which linking function are you calling?

**Comment by apiszcz** [comment]
dft = pd.concat(pred.link_df_iter(f_iter,

**Comment by nkeim** [comment]
OK, that calls `linking.link_df_iter`, which calls `linking.link_iter`, which outputs a status message on `linking.py` line 96. I use the same method and I do see status messages.

If you think you've found a bug (make sure you're not using `trackpy.quiet()` or otherwise doing something special with the logging configuration), it would be great if you could open a new issue. Please report whether it is IPython console, notebook, etc.

**Comment by apiszcz** [comment]
It is me on the status, I used tp.ignore_logging() on. Testing again.

**Comment by caspervdw** [comment]
@apiszcz If you are using `link_df_iter`, it might improve performance if you specify `pos_columns=[‘x’, ‘y’]`.

**Comment by apiszcz** [comment]
Yes on link_df_iter, add pos_columns and test

```
                    dft = pd.concat(pred.link_df_iter(f_iter,
                                                      search_range=ld['d'],
                                                      memory=ld['m'],
                                                      adaptive_stop=ld['astop'],
                                                      adaptive_step=ld['astep'],
                                                      pos_columns=['x','y']
                                                      ))
```
