### ISSUE TITLE
Linking performance 0.4 vs 0.3.3

### ISSUE THREAD

**Issue by apiszcz** [soft-matter/trackpy#487]
My observations for the same input data and link parameters indicate a performance difference in 'linking' between 0.3.3 and 0.4. 0.4 takes ~12.25x longer to complete than 0.3.3.

0.3.3: 2m31s (7082 trajectories)
0.4: 30m38s, (7060 trajectories)

**Comment by nkeim** [comment]
What's the output of

```
from trackpy.diag import dependencies
dependencies()
```

**Comment by apiszcz** [comment]
```
(Pdb) pp(dependencies())
OrderedDict([('six', '1.11.0'),
             ('numpy', '1.14.2'),
             ('scipy', '1.0.1'),
             ('matplotlib', '2.2.2'),
             ('pandas', '0.22.0'),
             ('scikit-image', None),
             ('pyyaml', None),
             ('pytables', None),
             ('numba', '0.37.0'),
             ('pyfftw', None),
             ('python', '3.5.4')])
```

**Comment by caspervdw** [comment]
This is very odd! We ran reproducibility tests and linking should not change between 0.3.3 and 0.4 (at least for the numba subnetljnker; there was a bug in the pure python one). Also @nkeim measured a slight performance *increase* for the linking. 

I suspect this to be an OS-related issue. For linking, `cKDTree` from `scipy` and of course `numpy`, `numba`, and maybe `pandas` are likely culprits. Are you sure that these dependencies were compiled correctly? Did you observe any warnings at some point? Are you using Windows? If so, I really recommend the conda binaries in isolated environments for reproducible results.

I am curious to see the output of a profiler. In IPython, this is easily done with `%prun tp.link(...)`

**Comment by apiszcz** [comment]
Libraries: Let's think about this, the same libraries work fine with 0.3.3.
Warnings: none.
Windows 10/64, again 0.3.3 is fine.
Thanks for giving more options to consider, in the mean time I'll stick with 0.3.3, and test 0.4 when possible,

**Comment by caspervdw** [comment]
Thanks, that helps to isolate the problem! Next thing: is it possible to try the new `link_iter`? This is for sure better tested than the `link_df_iter`, which is a quite new reimplementation. `link_iter` takes iterables of numpy arrays.

In this way we could isolate any issues associated with `pandas`.

Something like: 

```
# transform to numpy iterable, in memory
coords_iter = [f[['x', 'y']].values for f in f_iter]

particle_ids = []
for t, ids in link_iter(coords_iter, ...):
    particle_ids.append(ids)
```

I hope your dataset fits in memory for this test.

Just for clarity: the v0.4 `link_iter` works different from the v0.3.3 one.

**Comment by apiszcz** [comment]
Will run this next, may be tomorrow.
Waiting for the pos_columns=['x','y'] test to finish.
Data set should easily fit into memory.

**Comment by apiszcz** [comment]
Waiting for the pos_columns=['x','y'] test to finish.
Data set should easily fit into memory.
Added pos_columns=['x','y'] test using existing API call. (no effect)
dft = pd.concat(pred.link_df_iter(f_iter, ...., pos_columns=['x','y'] ))

v0.4: 31 minutes runtime.

**Comment by apiszcz** [comment]
Profile results for trackpy 0.3.3 and 0.4 indicate subnetlinker and associated calls for the ~12x difference in runtime.

The tottime values > 1.0 seconds.

```

ncalls | tottime | cumtime | function | location | trackpy
-- | -- | -- | -- | -- | --
27691 | 1532.577995 | 1532.577995 | _numba_subnet_norecur | test\lib\trackpy\linking\subnetlinker.py:241 | 0.4.0
34035 | 61.01552 | 61.01552 | _numba_subnet_norecur | test\lib\trackpy\linking.py:1481 | 0.3.3
282855 | 12.738602 | 17.852528 | split_subnet | test\lib\trackpy\linking\subnet.py:265 | 0.4.0
14188 | 11.626817 | 80.673701 | _assign_links | test\lib\trackpy\linking.py:1117 | 0.3.3
310546 | 5.368935 | 1542.591195 | numba_link | test\lib\trackpy\linking\subnetlinker.py:177 | 0.4.0
1879079 | 4.973451 | 6.903911 | <method 'sort' of 'list'   objects> | ~:0 | 0.4.0
4632268 | 3.716055 | 4.258542 | assign_subnet | test\lib\trackpy\linking\subnet.py:238 | 0.4.0
45862 | 2.154564 | 64.573143 | numba_link | test\lib\trackpy\linking.py:1426 | 0.3.3
380148 | 2.124229 | 1551.877445 | subnet_linker_numba | test\lib\trackpy\linking\subnetlinker.py:431 | 0.4.0
7131 | 2.072594 | 2.072594 | <built-in method nt.stat> | ~:0 | 0.4.0
31650729 | 1.947707 | 1.947707 | <method 'append' of 'list'   objects> | ~:0 | 0.4.0
6805 | 1.93753 | 1.93753 | <built-in method nt.stat> | ~:0 | 0.3.3
27437178 | 1.930337 | 1.930337 | <lambda> | test\lib\trackpy\linking\subnetlinker.py:444 | 0.4.0
26906061 | 1.776155 | 1.776155 | <method 'discard' of 'set'   objects> | ~:0 | 0.3.3
380148 | 1.771126 | 1571.694532 | adaptive_link_wrap | test\lib\trackpy\linking\linking.py:264 | 0.4.0
27297282 | 1.66515 | 1.666959 | <method 'add' of 'set'   objects> | ~:0 | 0.3.3
2363 | 1.510934 | 90.707462 | link | test\lib\trackpy\linking.py:974 | 0.3.3
536779 | 1.234133 | 1.255261 | <built-in method   numpy.core.multiarray.array> | ~:0 | 0.3.3
991630 | 1.209836 | 1.209836 | <listcomp> | test\lib\trackpy\linking\subnetlinker.py:198 | 0.4.0
483266 | 1.106066 | 1.109713 | <built-in method   numpy.core.multiarray.array> | ~:0 | 0.4.0
4446 | 1.079094 | 1.250469 | <method 'query' of   'scipy.spatial.ckdtree.cKDTree' objects> | ~:0 | 0.3.3
4446 | 1.034578 | 1.188207 | <method 'query' of   'scipy.spatial.ckdtree.cKDTree' objects> | ~:0 | 0.4.0


```

**Comment by caspervdw** [comment]
It is hard to compare the two implementations, because they really changed a lot. However, the numba subnetlinker was not touched at all. So either there are much more calls to it, or the time per call increased drastically. Are you able to distinguish that in your profiler results? 

I am very curious how this would compare on a Linux or OSX box. Could you maybe share your dataset and used parameters so that I and/or @nkeim can study the performance decrease?

**Comment by apiszcz** [comment]
The number of calls, total and cumulative time.


![image](https://user-images.githubusercontent.com/1430861/38454036-aae0a78a-3a2d-11e8-8c7d-ca40d41211bd.png)

**Comment by apiszcz** [comment]
Numba test shows Numba is working, ~183x faster on a mandlebrot function

Python: 8.42 s ± 807 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
Python+numba: 45.8 ms ± 2.64 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

**Comment by caspervdw** [comment]
@apiszcz   I removed some of our old numba-logic  in #488. If you checkout my branch `fix-numba-win` (which builds onto @nkeim s earlier fix) this will hopefully solve the issue.

**Comment by apiszcz** [comment]
I'd like to test, however I may need assistance:
git clone -b fix-numba-win https://github.com/soft-matter/trackpy.git
fatal: Remote branch fix-numba-win not found in upstream origin

**Comment by caspervdw** [comment]
OK Thanks for all the testing @apiszcz  . I will rerun the benchmarks (they support only linux) and report on the results. It might be that one of the latest commits deteriorated the performance . If not, I will need a sample of your dataset to investigate further.

**Comment by apiszcz** [comment]
Testing a new data set 0.3.3 finished successfully in 225 seconds.

0.4 stack trace with
`SubnetOversizeException: search_range (aka maxdisp) too large for reasonable performance on these data (particle has 201 forward candidates)`

**Comment by apiszcz** [comment]
Created a new TEST data set.
0.3.3: 26 seconds
0.4: 35.9 seconds

**Comment by apiszcz** [comment]
```
# 0.3.3
import time
import trackpy as tp
import trackpy.predict
import pandas as pd
print(tp.__version__)
tp.linking.Linker.MAX_SUB_NET_SIZE = 30 # 30
tp.linking.Linker.MAX_SUB_NET_SIZE_ADAPTIVE = 16 # 15
pred = trackpy.predict.NearestVelocityPredict(span=20)
number_of_frames=df.frame.nunique()
f_iter = (frame for fnum, frame in df.groupby('frame'))
t0=time.time()
dft = pd.concat(pred.link_df_iter(f_iter,
                                  search_range=0.002,
                                  memory=6,
                                  adaptive_stop=0.0000001,
                                  adaptive_step=0.95,
                                  number_of_frames=number_of_frames))
et=time.time()-t0
print(tp.__version__,et)
```

```
# 0.4
import time
import trackpy4 as tp
from trackpy4 import predict as tpp
import pandas as pd
print(tp.__version__)
tp.linking.Linker.MAX_SUB_NET_SIZE = 30
tp.linking.Linker.MAX_SUB_NET_SIZE_ADAPTIVE = 16
pred = tpp.NearestVelocityPredict(span=20)
f_iter = (frame for fnum, frame in df.groupby('frame'))
t0=time.time()
dft = pd.concat(pred.link_df_iter(f_iter,
                                  search_range=0.002,
                                  memory=6,
                                  adaptive_stop=0.0000001,
                                  adaptive_step=0.95))
et=time.time()-t0
print(tp.__version__,et)

```

**Comment by apiszcz** [comment]
FYI: In my scenarios 0.3.3 behavior is much faster and works with more noise in data. I'm wondering if there is anyway to keep the legacy 0.3.3 linker and the newer variant.

**Comment by nkeim** [comment]
@apiscz or anyone out there who uses Windows: Is there a way to install trackpy v0.4 using `setup.py` or pip in a separate environment? Putting it in a directory called `trackpy4` seems like it could cause problems. I don't know that it is actually against the rules; I just don't know of anyone else who does it that way.

If you are using anaconda you can tell `conda create` to clone your favored environment; then just install trackpy v0.4 via the normal `conda` instructions. I think our top priority is finding out whether this is truly a Windows problem, or just something that arises with certain configurations.

**Comment by caspervdw** [comment]
I reran the benchmarks and I confirmed @nkeim earlier findings that the linking performance increases significantly: on the dense numba linking test from 4.3 to 2.8 s. @apiszcz report really puzzles me. Could it be the adaptive linking?

I happen to just have installed trackpy with git on a new windows laptop. `python setup.py` works absolutely, as long as it doesn't pull in stuff that you have to compile. The trick is installing `trackpy` with conda, then uninstalling it, then installing from source.

 - install Anaconda
 - `conda update conda`
 - `conda config --append channels conda-forge`
 - `conda create -n trackpy_env python=3.5 nb_conda numba trackpy=0.4`
 - `conda activate trackpy_env`
 - `conda uninstall trackpy`  
 - `git clone git@github.com:soft-matter/trackpy.git` (assuming you have git and ssh configured)
 - `git checkout v0.4`
 - `python setup.py develop`

**Comment by apiszcz** [comment]
1. The reason I manage packages with my own lib format is exactly what you have experienced, and it gets worse with dependencies, side effects with Anaconda causes all kinds of upgrades and downgrades (with other non trackpy) packages. Very annoying.

2. I understand that it may be an environment issue, however I've been using the same setup for a few years now with 0.3.3 and earlier. The big changes came with 0.4.  Hopefully the sample data set will let you see some (not as dramatic) but 0.4 has issues when compared with 0.3.3.

Is this for a common set of features data, or are you having each version of trackpy do the feature-finding separately?

Yes common, actual data is more challenging. I am only showing the 0.4 output for evaluation purposes, it is not ready to run on my data sets in its current form, my environment or my understanding. Same parameters as 0.3.3 causes stack trace with 0.4.

I am hoping you can reproduce the python notebook results above to validate that this is not just me. Thank you.

**Comment by nkeim** [comment]
Thanks for providing the test data. I'm able to reproduce the problem on linux. It's weird because my workload uses adaptive linking heavily, so you'd think I would have already found the problem. I'm going to look into it.

**Comment by apiszcz** [comment]
Perhaps a search range of .002 is unrealistic, 

Incorporated the new subnet.py change #489.

Search range: 0.002
Trackpy 0.3: 235 seconds
Tracpy 0.4: stack trace
SubnetOversizeException: search_range (aka maxdisp) too large for reasonable performance on these data (particle has 196 forward candidates)

Search range: 0.001
Trackpy 0.3: 25.38s
Tracpy 0.4: 33.24s

**Comment by apiszcz** [comment]
Created a more challenging synthetic data set:
Trackpy 0.3: 2590 seconds
Tracpy 0.4: TBD seconds

**Comment by nkeim** [comment]
Yes, please try again. On your previous synthetic dataset, v0.4 is now about 3.5x faster than v0.3.

**Comment by apiszcz** [comment]
is subnetlinker the only file i need ?

**Comment by apiszcz** [comment]
got it, thanks. https://github.com/soft-matter/trackpy/pull/489/files

**Comment by apiszcz** [comment]
I may have messed up getting a file

C:\g\via\lib\trackpy\linking\subnetlinker.py in <module>()
     14 
     15 from .utils import SubnetOversizeException
---> 16 from ..try_numba import try_numba_autojit
     17 
     18 

ImportError: cannot import name 'try_numba_autojit'

**Comment by nkeim** [comment]
@apiszcz You can go to https://github.com/nkeim/trackpy/tree/fix-adaptive-pruning and click "Clone or download" for options.

**Comment by apiszcz** [comment]
Thank you, i did the download and replace and am getting the following on import

  File "lib\trackpy\linking\subnetlinker.py", line 241, in <module>
    @try_numba_autojit(nopython=True)
NameError: name 'try_numba_autojit' is not defined

**Comment by apiszcz** [comment]
tp.enable_numba()
  File "C:\g\test\lib\trackpy\try_numba.py", line 126, in enable_numba
    f.point_to_compiled_func()
  File "C:\g\test\lib\trackpy\try_numba.py", line 86, in point_to_compiled_func
    setattr(sys.modules[self.module_name], self.func_name, self.compiled)
KeyError: 'trackpy.subnetlinker'
 4:49:13.62

**Comment by caspervdw** [comment]
Great @apiszcz ! We'll figure your numba related question out in #485  or #488.
