### ISSUE TITLE
Remove dependency on PIMS

### ISSUE THREAD

**Issue by caspervdw** [soft-matter/trackpy#491]
I noticed some code in `api.py` that imports pims. I think it would be good to really drop PIMS as a dependency of trackpy. It pulls is a significant amount of packages that are not necessary for `trackpy` and adds significant overhead to trackpy.

**Comment by apiszcz** [comment]
+1 concur on this. For people only using the linker PIMS is unnecessary dependency drama.

**Comment by nkeim** [comment]
Agreed. Do you think we should do something like [this](https://github.com/soft-matter/trackpy/blob/fdd8acac9f422f31cf0cf889980d960809d353ce/trackpy/motion.py#L591) for v0.4.1?

**Comment by nkeim** [comment]
Oops, we already do issue a warning!

I still think we should wait until v0.5. We would have to revise the installation instructions.

**Comment by tacaswell** [comment]
:+1:

**Comment by caspervdw** [comment]
As there has been a DeprecationWarning for some time now, I would be in favour of dropping it altogether for v0.4.1.

**Comment by nkeim** [comment]
Sounds good. It won't affect existing users because they (must) already have pims. I will make a PR.

**Comment by apiszcz** [comment]
Congrats on dependency reduction, i look forward to testing 0.4.1 when ready.

**Comment by magsol** [comment]
Just came across TrackPy--absolutely love the work you've done and are continuing to do!

As I've been navigating through the Jupyter notebooks, and I see that you're planning to deprecate PIMS in the next version, I'm curious how you're going to have users instantiate 2D or 3D image stacks? For example, what will replace `pims.ImageSequenceND`?

**Comment by nkeim** [comment]
For recordkeeping purposes I renamed this issue. Thanks @magsol — it's awesome to have a new user taking interest in development. Please keep it up! 😃

**Comment by magsol** [comment]
Ahhh, that actually highlights the exact point of tension @nkeim @caspervdw. Thanks for the clarification!

**Comment by caspervdw** [comment]
Done, release v0.4.1 is on PyPI and conda will follow in the next couple of days!

**Comment by apiszcz** [comment]
Passes my standard performance test on Windows 10/64. Thank you.

**Comment by nkeim** [comment]
🎉 Thank you, @caspervdw for pushing this out, and thank you, @apiszcz for your testing and feedback!
