### ISSUE TITLE
pims.Video issue

### ISSUE THREAD

**Issue by alex-amvdor** [soft-matter/trackpy#502]
I am attempting to open a .avi video file using pims.Video. I know the code is right and I have the file location correct, but i am continually getting the error:

TypeError: list indices must be integers or slices, not av.video.stream.VideoStream

Please advise

**Comment by nkeim** [comment]
Thanks for the error report! Could you please paste the complete traceback?

**Comment by alex-amvdor** [comment]
I am a complete novice, and am frankly unsure how to do that. I'm using trackpy for a school program, but they threw us in the deep end on the programming stuff, never taught us how to do anything.

**Comment by nkeim** [comment]
The traceback is all the extra output that you see above and below that error message.

Maybe more important is the code that causes the error. How do you open the file, and how do you try to access an image?

**Comment by alex-amvdor** [comment]
I have imported all the necessary modules, i.e. pims, cv2, etc.
The actual code I'm using is as follows:

`frames = pims.Video('C:\\Users\\alexa\\Documents\\College\\Physics\\Physics 25L\\Boltzmann_video_2.avi')`

The complete traceback is then:

'Traceback (most recent call last):

  File "<ipython-input-3-78fdf028d61d>", line 1, in <module>
    frames = pims.Video('C:\\Users\\alexa\\Documents\\College\\Physics\\Physics 25L\\Boltzmann_video_2.avi')

  File "C:\Users\alexa\Anaconda3\lib\site-packages\pims\pyav_reader.py", line 139, in __init__
    frame = next(_gen_frames(demuxer, self._stream.time_base))

  File "C:\Users\alexa\Anaconda3\lib\site-packages\pims\pyav_reader.py", line 54, in _gen_frames
    for packet in demuxer:

  File "av/container/input.pyx", line 88, in demux

  File "av/container/streams.pyx", line 50, in _flatten

TypeError: list indices must be integers or slices, not av.video.stream.VideoStream'

I am able to open the video using pims.open(), but from the documentation, I think if I can get pims.Video to work, it'd be better for my purposes.

Thanks!

**Comment by apiszcz** [comment]
FYSA, separate topic, but may be of interest

http://www.scikit-video.org/stable/

**Comment by nkeim** [comment]
@alex-amvdor That is interesting. Why do you prefer `Video` if `open` works? And, what kind of reader object is returned when you use `open`? You can find out with

```python
reader = open(your filename)
print(type(reader))
```

**Comment by alex-amvdor** [comment]
It turns out that `open` does not work for my purposes, the program tells me that my frames are completely black when I try to use `open`. Here is what comes back when I do what you said.



`reader = pims.open('C:\\Users\\alexa\\Documents\\College\\Physics\\Physics 25L\\Boltzmann_video_2.avi')

C:\Users\alexa\Anaconda3\lib\site-packages\pims\api.py:191: UserWarning: <class 'pims.pyav_reader.PyAVReaderTimed'> errored: list indices must be integers or slices, not av.video.stream.VideoStream
  warn(message)

print(type(reader))
<class 'pims.pyav_reader.PyAVReaderIndexed'>`

Sorry for the bad formatting on the code.

**Comment by caspervdw** [comment]
Could you raise this issue at [pims](https://github.com/soft-matter/pims/issues)? Not sure whether this is a PyAv or a pims issue anyway. A way to find out would be using the basic PyAv []([example](https://mikeboers.github.io/PyAV):)

```
import av

container = av.open(path_to_video)

for frame in container.decode(video=0):
    frame.to_image().save('frame-%04d.jpg' % frame.index)
```
