### ISSUE TITLE
create subplot using tp.annotate objects

### ISSUE THREAD

**Issue by daviddoji** [soft-matter/trackpy#504]
I´m trying to create a set of subfigures using tp.annotate objects, but the following code:

`f, axs = plt.subplots(2,2,figsize=(15,15))

 tp.annotate(f_sample1, sample1[0])
tp.annotate(f_sample2, sample2[0])
tp.annotate(f_sample3, sample3[0])
tp.annotate(f_sample4, sample4[0])`

produces a set of 4 subplots (OK), but only the last one corresponds to a tp.annotate object (the first one). The others appear just below the subplots.

**Comment by nkeim** [comment]
`annotate` allows you to specify an axis as an argument; check the trackpy documentation. You will need to tell the first command to draw on `axs[0]`, the second command to draw on `axs[1]`, etc. The matplotlib documentation has more info about using subplots.
