### ISSUE TITLE
Issue with writing to hdf5 file

### ISSUE THREAD

**Issue by kevinkayaks** [soft-matter/trackpy#518]
I apologize in advance-- it's difficult to describe this bug as I have no clue what's going on at this level in the trackpy code. After iteratively detecting features and writing them to an HDF5 file, eventually I get this problem: 

```
---------------------------------------------------------------------------
HDF5ExtError                              Traceback (most recent call last)
~/anaconda3/lib/python3.6/site-packages/tables/node.py in __init__(self, parentnode, name, _log)
    265             if new:
--> 266                 self._v_objectid = self._g_create()
    267             else:

tables/hdf5extension.pyx in tables.hdf5extension.Group._g_create (tables/hdf5extension.c:11589)()

HDF5ExtError: HDF5 error back trace

  File "H5G.c", line 314, in H5Gcreate2
    unable to create group
  File "H5Gint.c", line 194, in H5G__create_named
    unable to create and link to group
  File "H5L.c", line 1638, in H5L_link_object
    unable to create new link to object
  File "H5L.c", line 1882, in H5L_create_real
    can't insert link
  File "H5Gtraverse.c", line 861, in H5G_traverse
    internal path traversal failed
  File "H5Gtraverse.c", line 596, in H5G_traverse_real
    can't look up component
  File "H5Gobj.c", line 1156, in H5G__obj_lookup
    can't locate object
  File "H5Gstab.c", line 907, in H5G__stab_lookup
    not found
  File "H5B.c", line 362, in H5B_find
    can't lookup key in subtree
  File "H5B.c", line 362, in H5B_find
    can't lookup key in subtree
  File "H5B.c", line 340, in H5B_find
    unable to load B-tree node
  File "H5AC.c", line 1262, in H5AC_protect
    H5C_protect() failed.
  File "H5C.c", line 3574, in H5C_protect
    can't load entry
  File "H5C.c", line 7954, in H5C_load_entry
    unable to load entry
  File "H5Bcache.c", line 136, in H5B__load
    can't read B-tree node
  File "H5Fio.c", line 120, in H5F_block_read
    read through metadata accumulator failed
  File "H5Faccum.c", line 214, in H5F__accum_read
    driver read request failed
  File "H5FDint.c", line 207, in H5FD_read
    addr overflow, addr = 9800235584, size=544, eoa=9622249177

End of HDF5 error back trace

Can't create the group Frame_115323.

During handling of the above exception, another exception occurred:

HDF5ExtError                              Traceback (most recent call last)
/media/kpierce/Data/steadyspt4.1-rectified/analysis/stereo-analysis-codes/toolbox.py in detection(rawvid, outdir, lr, minmass, diameter, thresh, lim, start)
    125             features['frame'] = t #add a column as required by tp.PandasHDFStoreBig()
--> 126             file.put(features) # put the features into the container
    127             del D, mask, F, features #keep memory as clean as possible

~/anaconda3/lib/python3.6/site-packages/trackpy/framewise_data.py in put(self, df)
    199         self._invalidate_cache()
--> 200         super(PandasHDFStoreBig, self).put(df)
    201 

~/anaconda3/lib/python3.6/site-packages/trackpy/framewise_data.py in put(self, df)
    136             pass
--> 137         self.store.put(key, df, format='table')
    138 

~/anaconda3/lib/python3.6/site-packages/pandas/io/pytables.py in put(self, key, value, format, append, **kwargs)
    865         kwargs = self._validate_format(format, kwargs)
--> 866         self._write_to_group(key, value, append=append, **kwargs)
    867 

~/anaconda3/lib/python3.6/site-packages/pandas/io/pytables.py in _write_to_group(self, key, value, format, index, append, complib, encoding, **kwargs)
   1318                 if group is None:
-> 1319                     group = self._handle.create_group(path, p)
   1320                 path = new_path

~/anaconda3/lib/python3.6/site-packages/tables/file.py in create_group(self, where, name, title, filters, createparents)
    947         return Group(parentnode, name,
--> 948                      title=title, new=True, filters=filters)
    949 

~/anaconda3/lib/python3.6/site-packages/tables/group.py in __init__(self, parentnode, name, title, new, filters, _log)
    234         # Finally, set up this object as a node.
--> 235         super(Group, self).__init__(parentnode, name, _log)
    236 

~/anaconda3/lib/python3.6/site-packages/tables/node.py in __init__(self, parentnode, name, _log)
    280             # since it might never be called anyway.
--> 281             self._f_close()
    282             raise

~/anaconda3/lib/python3.6/site-packages/tables/group.py in _f_close(self)
    920         # open until the very end.
--> 921         self._g_close()
    922 

~/anaconda3/lib/python3.6/site-packages/tables/group.py in _g_close(self)
    887             #   Close HDF5 group.
--> 888             self._g_close_group()
    889 

tables/hdf5extension.pyx in tables.hdf5extension.Group._g_close_group (tables/hdf5extension.c:13066)()

HDF5ExtError: HDF5 error back trace

  File "H5G.c", line 812, in H5Gclose
    not a group

End of HDF5 error back trace

Problems closing the Group Frame_115323

During handling of the above exception, another exception occurred:

HDF5ExtError                              Traceback (most recent call last)
<ipython-input-8-cad2042661e4> in <module>()
      1 # analyze features in the left video
----> 2 box.detection(Lc,outdir='../trajectories/left-features.h5',lim=None,start=115323)

/media/kpierce/Data/steadyspt4.1-rectified/analysis/stereo-analysis-codes/toolbox.py in detection(rawvid, outdir, lr, minmass, diameter, thresh, lim, start)
    126             file.put(features) # put the features into the container
    127             del D, mask, F, features #keep memory as clean as possible
--> 128             print('frame %d of %d complete...'%(t+1,lim),end='\r')
    129     print('done. The results are in ' + outdir) #bam done
    130 

~/anaconda3/lib/python3.6/site-packages/trackpy/framewise_data.py in __exit__(self, type, value, traceback)
     84 
     85     def __exit__(self, type, value, traceback):
---> 86         self.close()
     87 
     88 KEY_PREFIX = 'Frame_'

~/anaconda3/lib/python3.6/site-packages/trackpy/framewise_data.py in close(self)
    225             _ = self.frames # Compute cache
    226             self._flush_cache()
--> 227         super(PandasHDFStoreBig, self).close()
    228 
    229 

~/anaconda3/lib/python3.6/site-packages/trackpy/framewise_data.py in close(self)
    159 
    160     def close(self):
--> 161         self.store.close()
    162 
    163 

~/anaconda3/lib/python3.6/site-packages/pandas/io/pytables.py in close(self)
    618         """
    619         if self._handle is not None:
--> 620             self._handle.close()
    621         self._handle = None
    622 

~/anaconda3/lib/python3.6/site-packages/tables/file.py in close(self)
   2672 
   2673         # Close all loaded nodes.
-> 2674         self.root._f_close()
   2675 
   2676         self._node_manager.shutdown()

~/anaconda3/lib/python3.6/site-packages/tables/group.py in _f_close(self)
    913         # this is not an explicit close issued by the user.
    914         if not (self._v__deleting or self._v_objectid is None):
--> 915             self._g_close_descendents()
    916 
    917         # When all the descendents have been closed, close this group.

~/anaconda3/lib/python3.6/site-packages/tables/group.py in _g_close_descendents(self)
    877 
    878         node_manager = self._v_file._node_manager
--> 879         node_manager.close_subtree(self._v_pathname)
    880 
    881 

~/anaconda3/lib/python3.6/site-packages/tables/file.py in close_subtree(self, prefix)
    541             if path.startswith(prefix) and '/_i_' not in path
    542         ]
--> 543         self._close_nodes(paths, cache.pop)
    544 
    545         # Close everything else (i.e. indices)

~/anaconda3/lib/python3.6/site-packages/tables/file.py in _close_nodes(nodepaths, get_node)
    514                     # closed by this loop.
    515                     if hasattr(node, '_f_get_child'):
--> 516                         node._g_close()
    517                     else:
    518                         node._f_close()

~/anaconda3/lib/python3.6/site-packages/tables/group.py in _g_close(self)
    886             # hdf5extension operations:
    887             #   Close HDF5 group.
--> 888             self._g_close_group()
    889 
    890         # Close myself as a node.

tables/hdf5extension.pyx in tables.hdf5extension.Group._g_close_group (tables/hdf5extension.c:13066)()

HDF5ExtError: HDF5 error back trace

  File "H5G.c", line 812, in H5Gclose
    not a group

End of HDF5 error back trace

Problems closing the Group Frame_115323
```

**Comment by kevinkayaks** [comment]
A more minimal error is here: 

The code is 
```

with tp.PandasHDFStoreBig('../trajectories/left-features.h5') as file:
    arr = file.dump()
```

and this kicks the error 


---------------------------------------------------------------------------
HDF5ExtError                              Traceback (most recent call last)
~/anaconda3/lib/python3.6/site-packages/tables/node.py in __init__(self, parentnode, name, _log)
    265             if new:
--> 266                 self._v_objectid = self._g_create()
    267             else:

tables/hdf5extension.pyx in tables.hdf5extension.Group._g_create (tables/hdf5extension.c:11589)()

HDF5ExtError: HDF5 error back trace

  File "H5G.c", line 314, in H5Gcreate2
    unable to create group
  File "H5Gint.c", line 194, in H5G__create_named
    unable to create and link to group
  File "H5L.c", line 1638, in H5L_link_object
    unable to create new link to object
  File "H5L.c", line 1882, in H5L_create_real
    can't insert link
  File "H5Gtraverse.c", line 861, in H5G_traverse
    internal path traversal failed
  File "H5Gtraverse.c", line 641, in H5G_traverse_real
    traversal operator failed
  File "H5L.c", line 1725, in H5L_link_cb
    unable to create new link for object
  File "H5Gobj.c", line 600, in H5G_obj_insert
    unable to insert entry into symbol table
  File "H5Gstab.c", line 338, in H5G__stab_insert
    unable to insert the name
  File "H5Gstab.c", line 291, in H5G__stab_insert_real
    unable to insert entry
  File "H5B.c", line 607, in H5B_insert
    unable to insert key
  File "H5B.c", line 957, in H5B_insert_helper
    can't insert maximum subtree
  File "H5B.c", line 957, in H5B_insert_helper
    can't insert maximum subtree
  File "H5B.c", line 957, in H5B_insert_helper
    can't insert maximum subtree
  File "H5B.c", line 968, in H5B_insert_helper
    can't insert maximum leaf node
  File "H5Gnode.c", line 651, in H5G_node_insert
    unable to protect symbol table node
  File "H5AC.c", line 1262, in H5AC_protect
    H5C_protect() failed.
  File "H5C.c", line 3574, in H5C_protect
    can't load entry
  File "H5C.c", line 7954, in H5C_load_entry
    unable to load entry
  File "H5Gcache.c", line 169, in H5G_node_load
    bad symbol table node signature

End of HDF5 error back trace

Can't create the group _Frames_Cache.

During handling of the above exception, another exception occurred:

HDF5ExtError                              Traceback (most recent call last)
<ipython-input-6-0aa417f3016d> in <module>()
      1 with tp.PandasHDFStoreBig('../trajectories/left-features.h5') as file:
----> 2     arr = file.dump()

~/anaconda3/lib/python3.6/site-packages/trackpy/framewise_data.py in __exit__(self, type, value, traceback)
     84 
     85     def __exit__(self, type, value, traceback):
---> 86         self.close()
     87 
     88 KEY_PREFIX = 'Frame_'

~/anaconda3/lib/python3.6/site-packages/trackpy/framewise_data.py in close(self)
    224         if self.store.root._v_file._iswritable():
    225             _ = self.frames # Compute cache
--> 226             self._flush_cache()
    227         super(PandasHDFStoreBig, self).close()
    228 

~/anaconda3/lib/python3.6/site-packages/trackpy/framewise_data.py in _flush_cache(self)
    217                 and self.store.root._v_file._iswritable()):
    218             self.store[self._CACHE_NAME] = pd.DataFrame({'dummy': 1},
--> 219                                                         index=self._frames_cache)
    220             self._cache_dirty = False
    221 

~/anaconda3/lib/python3.6/site-packages/pandas/io/pytables.py in __setitem__(self, key, value)
    484 
    485     def __setitem__(self, key, value):
--> 486         self.put(key, value)
    487 
    488     def __delitem__(self, key):

~/anaconda3/lib/python3.6/site-packages/pandas/io/pytables.py in put(self, key, value, format, append, **kwargs)
    864             format = get_option("io.hdf.default_format") or 'fixed'
    865         kwargs = self._validate_format(format, kwargs)
--> 866         self._write_to_group(key, value, append=append, **kwargs)
    867 
    868     def remove(self, key, where=None, start=None, stop=None):

~/anaconda3/lib/python3.6/site-packages/pandas/io/pytables.py in _write_to_group(self, key, value, format, index, append, complib, encoding, **kwargs)
   1317                 group = self.get_node(new_path)
   1318                 if group is None:
-> 1319                     group = self._handle.create_group(path, p)
   1320                 path = new_path
   1321 

~/anaconda3/lib/python3.6/site-packages/tables/file.py in create_group(self, where, name, title, filters, createparents)
    946         _checkfilters(filters)
    947         return Group(parentnode, name,
--> 948                      title=title, new=True, filters=filters)
    949 
    950 

~/anaconda3/lib/python3.6/site-packages/tables/group.py in __init__(self, parentnode, name, title, new, filters, _log)
    233 
    234         # Finally, set up this object as a node.
--> 235         super(Group, self).__init__(parentnode, name, _log)
    236 
    237     def _g_post_init_hook(self):

~/anaconda3/lib/python3.6/site-packages/tables/node.py in __init__(self, parentnode, name, _log)
    279             # We do *not* rely on ``__del__()`` doing it later,
    280             # since it might never be called anyway.
--> 281             self._f_close()
    282             raise
    283 

~/anaconda3/lib/python3.6/site-packages/tables/group.py in _f_close(self)
    919         # be loaded during the closing process; thus this node must be
    920         # open until the very end.
--> 921         self._g_close()
    922 
    923     def _g_remove(self, recursive=False, force=False):

~/anaconda3/lib/python3.6/site-packages/tables/group.py in _g_close(self)
    886             # hdf5extension operations:
    887             #   Close HDF5 group.
--> 888             self._g_close_group()
    889 
    890         # Close myself as a node.

tables/hdf5extension.pyx in tables.hdf5extension.Group._g_close_group (tables/hdf5extension.c:13066)()

HDF5ExtError: HDF5 error back trace

  File "H5G.c", line 812, in H5Gclose
    not a group

End of HDF5 error back trace

Problems closing the Group _Frames_Cache

**Comment by nkeim** [comment]
Whoa, that is an impressive traceback!

My first guess is that the file is somehow effectively read-only. Are you absolutely sure it is not?

Does PandasHDFStore work instead?

**Comment by kevinkayaks** [comment]
Hi nkeim-- I'm just going to close since the traceback is giant / confusing. I did not resolve the issue, but I did circumvent the issue.
