### ISSUE TITLE
poetry failing to install trackpy because of version "unkown" in PyPI's release history

### ISSUE THREAD

**Issue by lagru** [soft-matter/trackpy#523]
I want to bring https://github.com/sdispater/poetry/issues/735 to your attention. Sadly I believe it isn't possible to remove a release from PyPI if I'm not mistaken. That would have been an easy fix at least for my situation.

Please feel free to close this issue if you don't have any comments or thoughts to add. :slightly_smiling_face:

**Comment by nkeim** [comment]
Thanks. Even though this is a bug in poetry that will hopefully get fixed, it would be nice to have a properly versionsed release history! It *looks* like it's possible to [remove a single release from PyPI](https://stackoverflow.com/a/43603029). Flagging @danielballan in case he has a moment to do it.

**Comment by nkeim** [comment]
Closing — even though we have not done anything, it's no longer a problem and the related issue was closed.
