### ISSUE TITLE
characterizing drifting vs non-drifting (automotive) particles

### ISSUE THREAD

**Issue by mluerig** [soft-matter/trackpy#528]
I have implemented your package as part of a program I am writing (https://github.com/mluerig/phenopype/tree/tracking => tracking functionality is not yet published). There I use a foreground-background subtractor to detect moving animals (water bugs and fish) in videos and send the coordinates to trackpy. In the example video below there is some detritus floating on top of the water, it creates the zig-zag trajectories that look clearly different from the bugs, more scattered (see pink markup in the picture)

I may have missed it in the documents, but does trackpy contain a function to distinguish a drifting/floating particle vs non-drifting particles? 

source video: https://vimeo.com/283075068

![6_fid14 mp4_isopod_trajectories](https://user-images.githubusercontent.com/15648068/52797929-34684180-3077-11e9-9700-ff2732a3832c.png)

**Comment by rbnvrw** [comment]
@mluerig that looks very interesting! I realize that this reply is late, but I hope it's still useful.

I don't think there is a built-in function that would achieve what you want, that is a bit too specific for your use case I'd say.

A few things you could try:
- The overall distance travelled by the detritus seems smaller compared to the other trajectories. Maybe you can filter it out based on that?
- If that doesn't work: probably the detritus follows a random walk and the animals do not. In that case, the MSD of the detritus is linear and of the animals not per se. You can calculate the MSD with trackpy (for an example, see the [walkthrough](http://soft-matter.github.io/trackpy/dev/tutorial/walkthrough.html)) and then filter your data based on the linearity (slope on a log-log scale).

Hope this helps!

**Comment by mluerig** [comment]
@rbnvrw thanks for your reply (I saw it, forgot it, and now rediscovered it) - I will have a look at it.
