### ISSUE TITLE
tracking colloidal particles

### ISSUE THREAD

**Issue by assiou** [soft-matter/trackpy#532]
Hi,
we'vebeen studying brownian motion and the movement of colloidal particles in glycerol but we've been dealing with some problems following trackpy walhthrough tutorial though (https://soft-matter.github.io/trackpy/v0.3.2/tutorial/walkthrough.html)

%matplotlib inline
import matplotlib.pyplot as plt
imagenames = 'C:\\Users\\user\\Documents\\40bis\\'
import numpy as np
import pandas as pd
from pandas import DataFrame, Series  # for convenience
import pims
import trackpy as tp
mpl.rc('figure',  figsize=(10, 6))
mpl.rc('image', cmap='gray')
frames = pims.ImageSequence(imagenames, as_grey=True)

it stops here with this error 

Exception AttributeError: "'ImageSequence' object has no attribute '_is_zipfile'" in <object repr() failed> ignored

TypeErrorTraceback (most recent call last)
<ipython-input-597-2032aa7e1c80> in <module>()
----> 1 frames = pims.ImageSequence(imagenames, as_grey=True)

TypeError: __init__() got an unexpected keyword argument 'as_grey'

we've tried switching C:\\Users\\user\\Documents\\40bis\\ to C:\Users\user\Documents\40bis\*.tif but i think the problems comes from the "grey command"

**Comment by tacaswell** [comment]
We deprecated `as_gray` from pims.

You will either have to down-grade pims or drop the `as_grey` kwarg (see https://github.com/soft-matter/pims/pull/250 for reasoning and alternatives).

**Comment by nkeim** [comment]
Thanks @assiou and @tacaswell . The walkthrough needs some attention and we (the maintainers) would really welcome someone contributing an updated version.

The way to convert to grayscale in newer versions of pims is an example in the [pipelines documentation](http://soft-matter.github.io/pims/v0.4.1/pipelines.html). Depending on how new your version is, you may also find that `pims.as_gray()` is built into pims.
