### ISSUE TITLE
Walkthrough code issues

### ISSUE THREAD

**Issue by Resonanz** [soft-matter/trackpy#534]
Hi guys, I'm running Python 3.6.8 on a Mac and get the following when running the Walkthrough code:

`im = tp.imsd(tm, 1/13.88, 73)  # microns per pixel = 100/285., frames per second = 24`

/anaconda3/lib/python3.6/site-packages/mkl_fft/_numpy_fft.py:158: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  output = mkl_fft.fft(a, n, axis)

And ditto for this line:

`em = tp.emsd(tm, 1/13.88, 73) # microns per pixel = 100/285., frames per second = 24`

**Comment by nkeim** [comment]
Now fixed for development version on recent Anaconda.
