### ISSUE TITLE
Distinction between DriftPrediction and drift subtraction after linking

### ISSUE THREAD

**Issue by danielballan** [soft-matter/trackpy#539]
I was asked this question via an email from a trackpy user. I will answer it here so that the answer is public, available for other users to discover or comment on.

> What is the difference between normally linking (trackpy.link_df(), without using the prediction framework) the particles between frames and subtracting the drift through the compute_drift and subtract_drift functions and linking the particles between frames through predict.DriftPredict() and then subtracting the drift through the same previous methods?

If there is low drift, plain `link_df()` and `DriftPredict()` should produce the same results. But if there is significant drift, `link_df()` will begin to get confused and produce poorer results. It looks for a feature within some radius of where it was last seen. `DriftPredict()` looks for a feature within some radius of a position _offset_ from where the feature was last seen, accounting for the component of its movement that is due to an overall drift.

Thus, unless the drift is very low, `DriftPredict()` is the more accurate tool.

**Comment by nkeim** [comment]
Resolved by https://github.com/nkeim/trackpy-examples/commit/d8e9f41d93235ce458caff9ffe8a686d6b683d6a
