### ISSUE TITLE
Updating the Walkthrough (minmass / diameter)

### ISSUE THREAD

**Issue by Resonanz** [soft-matter/trackpy#541]
I'm trying to understand this page:

[http://soft-matter.github.io/trackpy/dev/generated/trackpy.minmass_v04_change.html](url)

I think it is describing a new function in version 0.40 for calculating "minmass"? From my testing of the particles in water sample, the minmass value has to be set between 0 and 1 to make a difference, yet in the Walkthrough code the value is set at 200.

**Comment by nkeim** [comment]
This is probably related to the specific image-reading backend that pims is using. The default Anaconda install seems to give gray values in [0, 255], but it's possible to have them in [0, 1] instead. @Resonanz is that consistent with what you see? I don't know exactly which packages need to be installed to get that result.

I'm currently revising the walkthrough and am adding a caveat about this. Thanks!
