### ISSUE TITLE
Tidying up / clarifying "trackpy.locate" documentation

### ISSUE THREAD

**Issue by Resonanz** [soft-matter/trackpy#542]
On this page:

[http://soft-matter.github.io/trackpy/dev/generated/trackpy.locate.html#trackpy.locate](url)

we see an `optional` label beside "minmass"

`minmass : float, optional`

It seems that there are lots of other optional arguments in the locate method, so should these also be labeled "optional" to improve the documentation?

**Comment by caspervdw** [comment]
Hi,
We try to follow the numpydoc conventions. So we should not display “optional” as that is apparent from the function signature.
We however do not have the bandwidth to fix this. If you have time, please open a PR with your suggestions. After review, it will get into the next release.
