### ISSUE TITLE
ValueError for 'frame' (used as label and index)

### ISSUE THREAD

**Issue by Resonanz** [soft-matter/trackpy#544]
I getting the following message when I run this code:

```
plt.savefig("computeDrift.png")
d = tp.compute_drift(t1)
d.plot()
plt.close()
```

`ValueError: 'frame' is both an index level and a column label, which is ambiguous.`

**Comment by nkeim** [comment]
Thanks! This is the same problem as #529 ; it is addressed in #538 .
