### ISSUE TITLE
trackpy 0.4.1, different results with identical input.

### ISSUE THREAD

**Issue by apiszcz** [soft-matter/trackpy#548]
Using the same input parameters I'm getting different associations.
Is this due to some 'random' number in trackpy?
In this animated GIF below you'll notice the different particle labels, the only difference is updating the notebook cell, all input the same.

![SNEZVZHu0j](https://user-images.githubusercontent.com/1430861/57927268-82a9fe00-787b-11e9-8d43-2541dda960c6.gif)

**Comment by caspervdw** [comment]
Thanks for the report. From the images I cannot really conclude which solution is best. Could it be that the two displayed solutions are two valid solutions?

If so then there is indeed some randomness, probably because of floating point inaccuracy. In real applications you almost never have integers. My guess is that if you add a random small number (order 1e-7) to the coordinates, there is only one solution, and the two trackpy versions give the same results. Could you maybe test that?

**Comment by apiszcz** [comment]
1. I have three straight line trajectories, so the solution is that is a single 'straight' or diagonal of the same color is correct.
2. I appreciate the n-dimension message about color, I may explore ways of scaling other values to see if they support improved association.
3. I'm creating an interactive notebook with widgets to explore this further, will test some variance (minor) to the coordinate data.
4. When is 0.4.2 likely ? this fall or?
Thanks.

x,y,frame

                 [1.0,3.0,0],
                 [2.0,3.0,1],
                 [3.0,3.0,2],
                 [4.0,3.0,3],
                 [5.0,3.0,4],
                
                 [1.0,1.0,0],
                 [2.0,2.0,1],
                 [3.0,3.0,2],
                 [4.0,4.0,3],
                 [5.0,5.0,4],
    
                 [3.0,5.0,0],
                 [3.0,4.0,1],
                 [3.0,3.0,2],
                 [3.0,2.0,3],
                 [3.0,1.0,4],

**Comment by apiszcz** [comment]
Is it possible for the plot_traj to use the following to create larger notebook plots?

import ctypes,matplotlib
user32 = ctypes.windll.user32
screensize = user32.GetSystemMetrics(0), user32.GetSystemMetrics(1)
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
matplotlib.rcParams['figure.figsize'] = (20.0, 20.0)
%matplotlib inline

**Comment by caspervdw** [comment]
Indeed you would expect the velocity predictor to get this right. What version gives the wrong results? Maybe @nkeim could take a closer look

**Comment by apiszcz** [comment]
FYI the issue was the 'singularity location) 3,3 it was really causing the issues, using slightly different x values for each trajectory cleaned up the results.  At 3,3 all three converged at the same exact time with identical coordinates.

**Comment by nkeim** [comment]
That makes sense! My guess is that this apparent randomness (maybe just a fluke of memory allocation) is inherent in the cKDTree algorithm that trackpy uses to identify candidates for linking. You could add a sorting step to guarantee a certain outcome, but that does not seem worth the hit to performance across-the-board.

If this is a serious problem for your application, I agree with @caspervdw that breaking the degeneracy in your data, either by perturbing the coordinates, or giving each particle a small random z coordinate, is better than changing the code.

The window that had opened for v0.4.2 has unfortunately closed for me. I'm afraid it will be at least a month. But maybe someone can create a PR before then using the instructions in the wiki.
