### ISSUE TITLE
Related package PtvPy

### ISSUE THREAD

**Issue by lagru** [soft-matter/trackpy#549]
Dear devs, during my work at university I have developed [PtvPy](https://gitlab.com/tud-mst/ptvpy) which is a command line tool for particle tracking velocimetry. It's still in its early stages but I was recently allowed to open-source it. 

PtvPy relies heavily on your excellent library and therefore I felt that it would be good to involve you guys early on. I mention and link trackpy prominently at several places. Please let me know if you see any issues with that or the way I'm doing that. And of course, feedback and suggestions are welcome. :slightly_smiling_face:

**Comment by caspervdw** [comment]
Hi, good to see that you integrated trackpy in your package! And thanks for putting it in the docs so prominently.

I am not sure if we can contribute (the trackpy devs all have different priorities now) but if you feel you have some functionality or improvement that could be relevant for other trackpy users, I would really appreciate that input.

**Comment by lagru** [comment]
Sure, I'll keep it in mind. :wink:
