### ISSUE TITLE
A detailed explanation of the algorithm

### ISSUE THREAD

**Issue by tomchor** [soft-matter/trackpy#550]
I'm planning on using Trackpy in a scientific publication soon and I intend to cite the package properly. However, I also have to describe what the package does (a description of the algorithm it implements) and explain what each of the parameters mean exactly. 

I have read the docs and, while they're enough to use the package after trial-and-error, I don't think it's detailed enough for description in a scientific publication (the only description is a link to an [IDL page](http://www.physics.emory.edu/~weeks/idl/tracking.html)). Is there any paper that describes the algorithm and what the parameters mean exactly? I plan on citing this other publication (if it exists) along with the zenodo record.

Thank you.

**Comment by nkeim** [comment]
Hi! Thanks for raising this issue. Kudos for citing the software you use! A description of the core feature-finding and linking algorithms is published in this widely-cited paper:

Crocker, J. C., & Grier, D. G. (1996). Methods of Digital Video Microscopy for Colloidal Studies. J. Colloid Interf. Sci., 179(1), 298–310. http://doi.org/10.1006/jcis.1996.0217

Where possible/practical we have tried to be faithful to that original specification. I’m afraid that the trackpy documentation/source code are the only good references for some aspects of trackpy. A few of us were writing a paper at one point but that fell by the wayside; the incomplete manuscript is out of date at this point, anyhow.

For specific features of trackpy there are sometimes additional references, e.g. Savin and Doyle.

In my own publications I have cited the Crocker-Grier paper and the Zenodo record.

On May 26, 2019, at 8:17 PM, T. Chor <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm planning on using Trackpy in a scientific publication soon and I intend to cite the package properly. However, I also have to describe what the package does (a description of the algorithm it implements) and explain what each of the parameters mean exactly.

I have read the docs and, while they're enough to use the package after trial-and-error, I don't think it's detailed enough for description in a scientific publication (the only description is a link to an IDL page<http://www.physics.emory.edu/~weeks/idl/tracking.html>). Is there any paper that describes the algorithm and what the parameters mean exactly? I plan on citing this other publication (if it exists) along with the zenodo record.

Thank you.

**Comment by tomchor** [comment]
@nkeim thanks for the reply! That's already helpful and I'll cite both that paper and the zenodo entry. 

I suggest including that paper in the beginning of the documentation, as it might be helpful to more users. Furthermore it might provide insight into the nature of the parameters Trackpy uses for users that are unfamiliar with particle tracking. (For example I could never figure out the difference between mass and raw_mass, or if the diameter used is an upper-bound or the approximate size of the features the algorithm looks for.)

Thanks!

**Comment by nkeim** [comment]
Good point. I just created #551 to (mostly) address these issues.
