### ISSUE TITLE
Tracking on a spherical surface?

### ISSUE THREAD

**Issue by w-k-jones** [soft-matter/trackpy#556]
Hi all,

The trackpy documentation has an image of what appears to be tracks on the surface of a sphere (3rd image from the left on the landing page). Is it possible to track objects on a sperical, rather than euclidean surface using trackpy? If so, how should I go about doing this? So far I've only been able to find a reference to radial coordinates with the 'to_eucl' parameter

Many thanks

**Comment by caspervdw** [comment]
Hi,
Yes that is certainly possible. Citing from the docstring of `link`:

```
dist_func : function, optional
        a custom distance function that takes two 1D arrays of coordinates and
        returns a float. Must be used with the 'BTree' neighbor_strategy.
```

So you will have to devise a function that computes distance in your custom metric and supply that.

By the way, if your images are dilute or displacements are small, you might get exactly the same results if you use Euclidean coordinates. This is what I ended up doing in my PhD for tracking particles attached to the surface of a spherical membrane. Performance will be better.
