### ISSUE TITLE
adaptive linking 'diagnostics' parameter

### ISSUE THREAD

**Issue by apiszcz** [soft-matter/trackpy#558]
In the notebook cell 16 the diagnostics parameter is shown, yet the same keyword is not in the API documentation. Is it still supported?

If link_df is  deprecated it may not relevant in this tutorial example.

notebook cell 16
http://soft-matter.github.io/trackpy/v0.4.1/tutorial/adaptive-search.html

**Comment by nkeim** [comment]
Thanks for pointing this out! We dropped diagnostics in v0.4, so it should not be mentioned.
