### ISSUE TITLE
linewidth in plot_traj

### ISSUE THREAD

**Issue by Arkajyoti** [soft-matter/trackpy#561]
Hi,

I am newly starting trackpy and was wondering if there is any way to increase the thickness of plotted trajectories. I saw in the documentation of plt_traj the option of plotstyle={} but do not know if that is the correct keyword or if so how to use it. I have tried options like tp.plot_traj(df,plotstyle={'linewidth':60}) or tp.plot_traj(df, linewidth=60}) but to no avail. Please help me out here. Thanks in advance

**Comment by nkeim** [comment]
Interesting. `tp.plot_traj(df, plot_style={'linewidth':60})` should have the desired effect. In your original posting it is `plotstyle`, not the required `plot_style`. Could that be the problem?

**Comment by Arkajyoti** [comment]
Hello, @nkeim Thank you for your reply. You were exactly right. Making it 'plot_style' instead of 'plotstyle' works like a charm. Do not know how it got overlooked. Thanks a lot again.
