### ISSUE TITLE
ValueError: 'frame' is both an index level and a column lable, which is ambiguous.

### ISSUE THREAD

**Issue by Zhhjll** [soft-matter/trackpy#564]
Hi there,

I have installed the anocanda3 on my Mac and trackpy v0.4.1 while running the walkthrough I receive this error that I do not how to figure it out.
ValueError: 'frame' is both an index level and a column lable, which is ambiguous.

I was wondering of you can please help me with it it is very urgent...

**Comment by Arkajyoti** [comment]
Would you mind posting the code? I can have a look

**Comment by Zhhjll** [comment]
hi @Arkajyoti and thanks for checking it.
here is the code : 

from __future__ import division, unicode_literals, print_function  # for compatibility with Python 2 and 3

import matplotlib as mpl
import matplotlib.pyplot as plt

# the following line only works in an IPython notebook
#%matplotlib notebook

# Optionally, tweak styles.
mpl.rc('figure',  figsize=(10, 6))
mpl.rc('image', cmap='gray')

import numpy as np
import pandas as pd
from pandas import DataFrame, Series  # for convenience

import pims
import trackpy as tp

#images = pims.open('/⁨Users⁩ ▸ ⁨Zohreh⁩ ▸ ⁨Desktop⁩ ▸ ⁨Hamad⁩ ▸ Images⁩/*.png')
frames = pims.ImageSequence('/Users/zjalilvand/Desktop/SL/3/Images/*.tif', as_grey=True)#/Users/zjalilvand/Desktop
frames
print(frames[0])
frames[0]
plt.imshow(frames[0])
f = tp.locate(frames[0], 45, invert=True)
f.head() # shows the first few rows of data
plt.figure()  # make a new figure
tp.annotate(f, frames[0])
fig, ax = plt.subplots()
ax.hist(f['mass'], bins=20)

# Optionally, label the axes.
ax.set(xlabel='mass', ylabel='count')
f = tp.locate(frames[0], 45, invert=True, minmass=10000)
plt.figure()
tp.annotate(f, frames[0])
f = tp.batch(frames[:200], 45, minmass=10000, invert=True)
t = tp.link_df(f, 5, memory=3)
t1 = tp.filter_stubs(t, 50)
# Compare the number of particles in the unfiltered and filtered data.
print('Before:', t['particle'].nunique())
print('After:', t1['particle'].nunique())
plt.figure()
tp.mass_size(t1.groupby('particle').mean())
t2 = t1[((t1['mass'] > 40000) & (t1['size'] > 9.0) &
         (t1['ecc'] < 1))]
plt.figure()
tp.annotate(t2[t2['frame'] == 0], frames[0])
plt.figure()
tp.plot_traj(t1)
d = tp.compute_drift(t1)
plt.figure()
d.plot()
tm = tp.subtract_drift(t1.copy(), d)
plt.figure()
ax = tp.plot_traj(tm)
im = tp.imsd(tm, 0.2347, 10)
fig, ax = plt.subplots()
ax.plot(im.index, im, 'k-', alpha=0.1)  # black lines, semitransparent
ax.set(ylabel=r'$\langle \Delta r^2 \rangle$ [$\mu$m$^2$]',
       xlabel='lag time $t$')
ax.set_xscale('log')
ax.set_yscale('log')
em = tp.emsd(tm, 0.2347, 10)
ig, ax = plt.subplots()
ax.plot(em.index, em, 'o')
ax.set_xscale('log')
ax.set_yscale('log')
ax.set(ylabel=r'$\langle \Delta r^2 \rangle$ [$\mu$m$^2$]',
       xlabel='lag time $t$')
ax.set(ylim=(1e-2, 10));
plt.figure()
plt.ylabel(r'$\langle \Delta r^2 \rangle$ [$\mu$m$^2$]')
plt.xlabel('lag time $t$');
tp.utils.fit_powerlaw(em)
print(tp.utils.fit_powerlaw(em))

===========================

The error 


  File "<ipython-input-2-999c9bdc4d3d>", line 1, in <module>
    runfile('/Users/zjalilvand/Desktop/SL/3/diffusivitySL.py', wdir='/Users/zjalilvand/Desktop/SL/3')

  File "/Users/zjalilvand/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/Users/zjalilvand/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Users/zjalilvand/Desktop/SL/3/diffusivitySL.py", line 59, in <module>
    d = tp.compute_drift(t1)

  File "/Users/zjalilvand/anaconda3/lib/python3.7/site-packages/trackpy/motion.py", line 277, in compute_drift
    f_sort = pandas_sort(traj, ['particle', 'frame'])

  File "/Users/zjalilvand/anaconda3/lib/python3.7/site-packages/trackpy/utils.py", line 313, in _pandas_sort_post_017
    return df.sort_values(*args, by=by, **kwargs)

  File "/Users/zjalilvand/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 4711, in sort_values
    for x in by]

  File "/Users/zjalilvand/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 4711, in <listcomp>
    for x in by]

  File "/Users/zjalilvand/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 1701, in _get_label_or_level_values
    self._check_label_or_level_ambiguity(key, axis=axis)

  File "/Users/zjalilvand/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 1655, in _check_label_or_level_ambiguity
    raise ValueError(msg)

ValueError: 'frame' is both an index level and a column label, which is ambiguous.

===========================

Thanks again!

**Comment by nkeim** [comment]
Thanks. This was fixed by #538 and is due to a change in Pandas ( #529 ). For now, you should use the development version. I think we can release v0.4.2 this month, but no guarantees. You can see the status of this release at https://github.com/soft-matter/trackpy/milestone/8 .

**Comment by nkeim** [comment]
Thanks also to @Arkajyoti for replying earlier!! It really helps.
