### ISSUE TITLE
Feature request: allow suppressing output from tp.link

### ISSUE THREAD

**Issue by weinberz** [soft-matter/trackpy#575]
Hello,

Thank you so much for this excellent package! I'm using it for tracking in an academic project and it was so nice to have a drop-in solution for particle tracking.

As I'm using this in part of a larger package, it would be nice to be able to wrap my own status messages. Right now, particle tracking will output the current frame and the number of particles detected in it. Would it be possible to add a flag to suppress this display?

Thanks!

**Comment by nkeim** [comment]
Hi! Yes, try tp.quiet().

Trackpy uses the standard Python logging framework so you have lots of other options too.

On Oct 1, 2019, at 3:45 PM, Zara Weinberg <notifications@github.com> wrote:

﻿

Hello,

Thank you so much for this excellent package! I'm using it for tracking in an academic project and it was so nice to have a drop-in solution for particle tracking.

As I'm using this in part of a larger package, it would be nice to be able to wrap my own status messages. Right now, particle tracking will output the current frame and the number of particles detected in it. Would it be possible to add a flag to suppress this display?

Thanks!

**Comment by nkeim** [comment]
Hi @weinberz ! Did this solution work for you?

**Comment by weinberz** [comment]
Yes, thanks so much! You were very helpful and informative :)
