### ISSUE TITLE
How does TrackPy deal with local background?

### ISSUE THREAD

**Issue by komodovaran** [soft-matter/trackpy#578]
I couldn't find anything about it in the docs, so now I'll ask here.

Take an image like this for example:
![myplot](https://user-images.githubusercontent.com/20357875/66902492-091c6480-f001-11e9-9426-00751b34e9e6.png)
![myplot2](https://user-images.githubusercontent.com/20357875/66902497-0ae62800-f001-11e9-88df-d4fdcaac3dd3.png)

There's a higher background near the center (because they're fluorescent particles inside a cell), and the background will also vary depending on the "bleed" from a high local concentration.

How does TrackPy deal with this? The intensity "mass" sounds like just integrating everything inside a circle.

What I'm currently doing is using the track coordinates to draw adjustable masks for each frame to get signal and local background and subtract that. Am I better or worse off by doing this? TrackPy intensities just seem way noisier.

![myplot](https://user-images.githubusercontent.com/20357875/66904541-8dbcb200-f004-11e9-8317-bacf01802376.png)

**Comment by rbnvrw** [comment]
Hi @komodovaran, I'm assuming your using the `locate` or `batch` function of Trackpy. 
From the documentation (see http://soft-matter.github.io/trackpy/v0.4.2/generated/trackpy.locate.html#trackpy.locate):

> Preprocess the image by performing a band pass and a threshold.

This is the only preprocessing that is done as far as I know and it can be controlled using the `smoothing_size` and `threshold` keywords.

If you need to do other background corrections, you can implement these yourself using Pipelines (see for example http://soft-matter.github.io/pims/v0.4.1/pipelines.html)

I hope this helps!

**Comment by rbnvrw** [comment]
I'll close this question now due to inactivity.
