### ISSUE TITLE
Need help with tracking for this dataset

### ISSUE THREAD

**Issue by Arkajyoti** [soft-matter/trackpy#584]
Is there any way to do custom feature detection and tracking for this kind of datasets? 
video link: https://drive.google.com/file/d/1gxJzJz0IuoHYHnzf_I6kIRdEumH21pW5/view?usp=sharing
I tried to follow the custom track tutorial but for identifying features but could not replicate for this dataset. I am also new to image analysis so any help will be appreciated.
Thank you in advance

**Comment by speedymcs** [comment]
Disclaimer: I'm only a Trackpy user myself. 
In general you can either give Trackpy the image data and use the built-in feature detection, or you come up with a custom feature detection yourself and feed only the coordinates into Trackpy. Extracting features from the video you posted is, in my opinion, a difficult task:

- First, you need to know which pixels make up an object. In the video, it's hard to tell single objects apart from each other. If I can't do it with my own eyes, it will be even harder to teach the computer to do it. Of course your eyes might be better trained for this, then you could maybe label some data manually and train an AI for segmentation.
- The objects are very elongated and at times bent, which raises the question how the location should be defined via a single XY coordinate that is needed for tracking. Using the centroid, as in the Trackpy custom feature detection example, you may well end up with a coordinate that's outside of the object:

![sausage_centroid](https://user-images.githubusercontent.com/15879839/67561848-e2a3ab00-f71d-11e9-8c7d-b847a19cce51.png)

- The objects are constantly changing size and splitting as well, so for every existing coordinate there might be new ones popping up left and right and possibly lead to mismatches when they are close. 

Can you maybe get better data, e.g. with higher magnification, contrast or sharpness? In [this similar video](https://www.youtube.com/watch?v=9jYUesQvAqo), telling the cells apart is somewhat easier.

**Comment by Arkajyoti** [comment]
@speedymcs Thank you very much for your input. 
1) I am not familiar with machine learning so I am unable to train AI for segmentation. I know that segmentation is the most important challenge in this case. I am looking to learn machine learning tools for this module
2) As you mentioned, custom feature detection does not take into account the wide alteration in size and curvature. Also for each frame, the amount of time my computer takes for detection is (inexplicably) very large. Ps: Is this the zoomed image of a single feature or the overall image?
3)Do you think it is possible to track particles if the video quality is like the one on youtube?  I have something similar in quality and would like to try out tracking on them.

**Comment by speedymcs** [comment]
> custom feature detection does not take into account the wide alteration in size and curvature

It is important to note that _custom feature detection_ is not the name of the technique used to extract coordinates from bubbles in the Trackpy tutorial. It is something you still have to come up with, tailored to the data you work with! :) So you somehow have to find a way to take into account the size differences, curvature etc. 
It should not be too hard once you get the correct region for each cell. You could take some screen shots from the Youtube video and play around with the threshold in ImageJ, see if you find a value where each cell is its own region. Or even try the Weka segmentation which is included in Fiji, that one has a very straight forward AI interface. 

The image I posted was only to illustrate why the centroid is not a good measure for the location in this context, I drew it myself.

May I ask why you want to track cells that behave like this? They don't seem to move at all, just reproduce. Maybe you're good with just counting them? 

Have a good weekend!

**Comment by Arkajyoti** [comment]
> It is important to note that custom feature detection is not the name of the technique used to extract coordinates from bubbles in the Trackpy tutorial.
I understand that the process/technique falls under image segmentation. I will try to use Weka or maybe learn AI-based segmentation (hopefully :-P). 
Counting is not the issue here. I am more interested in getting an estimate of velocity at the aggregate level as well as at the single-cell level. 
I just wanted an expert opinion on whether it is possible to so for this dataset without AI or if I am missing something. Also, most of the actual data looks similar to what is seen on the youtube video with a wide range (and lots of) motion. I was hoping as long as the density was low, to extract velocity using PTV. [This is just a sample dataset that does not look too good]

Thanks for your views though. Have a good weekend too.
