### ISSUE TITLE
predictor example with link_partial?

### ISSUE THREAD

**Issue by apiszcz** [soft-matter/trackpy#595]
Is there an example pattern set the predictor function?
The following fails. I also need to pass in a span value.
Thank you.

pred = trackpy.predict.NearestVelocityPredict

```

trackpy.link_partial(df,
                                    search_range = 100,
                                    link_range = [0, 100],
                                    pos_columns = ['x', 'y'],
                                    memory =1,
                                    t_column = 'frame',
                                    predictor=pred
                                )
```

**Comment by speedymcs** [comment]
By span value do you mean link_range? If so, maybe you could use 
`
pred = trackpy.predict.NearestVelocityPredict()
pred.link_df(df[df.frame<=100, search_range = 100)
`

**Comment by apiszcz** [comment]
Thank you for the reply, I'm trying to use link_partial... and the normal approach is throwing an error.

```
pred = trackpy.predict.NearestVelocityPredict(span=1)
pred.link_partial(df,...)

AttributeError: 'NearestVelocityPredict' object has no attribute 'link_partial'
```

**Comment by nkeim** [comment]
Because prediction generally depends on history, implementing it for link_partial is non-obvious. So unfortunately I don’t think it is supported. What sort of application did you want to use it for?

**Comment by apiszcz** [comment]
Reading a data set in as a stream of frames and then applying linking to
the last 'n' frames.
I realize there will be a patch 'join' issue at the boundary of where I
start the partial link at.

I did get the h5 example working, streaming there means from a store on
disk, though I had hopes it might support something similar to partial.

**Comment by apiszcz** [comment]
I am trying to produce the example for link_partial `http://soft-matter.github.io/trackpy/dev/generated/trackpy.link_partial.html`

**Comment by apiszcz** [comment]
I set the link range to 1,3 (assume it stops at 2) and now have the intended result. Should this example replace http://soft-matter.github.io/trackpy/dev/generated/trackpy.link_partial.html ?


![2020-03-23T114556_913_1235](https://user-images.githubusercontent.com/1430861/77313486-df780f80-6cfb-11ea-9874-411959575f15.png)

**Comment by apiszcz** [comment]
Achieved success with partial linking test.
