### ISSUE TITLE
Combining trajactories

### ISSUE THREAD

**Issue by MirSA93** [soft-matter/trackpy#600]
Hello All,

I have been trying to track capped particles by detecting the dark/shaded part of the particle, I am not an expert in how I can modify the feature detecting parameters and this way worked quite well before, so i kept using it. But for some reason the detection of particles seems to get lost at certain frames and new trajectories are assigned for the same particle, even while trying to detect single particles. is there a way to combine different trajectories into one track? 

thank you

**Comment by rbnvrw** [comment]
That is certainly possible! Checkout the walkthrough, step 3: http://soft-matter.github.io/trackpy/v0.4.2/tutorial/walkthrough.html#Step-3:-Link-features-into-particle-trajectories

You'll want to tune the `memory` parameter as explained there. Good luck!
