### ISSUE TITLE
Add note about tracks sorting to release notes

### ISSUE THREAD

**Issue by nkeim** [soft-matter/trackpy#601]
This is a follow-up to #597 . The release notes should make it very clear that the assigned track numbers may have changed when running trackpy with identical parameters on the same data, even though the tracks themselves should be identical. Of course, the release notes should also make it clear that the linking algorithm is now significantly faster!

**Comment by danielballan** [comment]
Do you think it's worth bumping the minor version over this, releasing as 0.5.0? My general guideline for this is, "Would the results change in a way that isn't unambiguously fixing an error?"

**Comment by apiszcz** [comment]
FYSA: I grabbed the latest trackpy from the repo and ran my standard linking task.
The new arrangement appears to be slower for my use case.

```
0.4.2  00:17:46 - 00:19:03  1m 17s
0.4.2+ 00:22:50 - 00:24:15 1m 25s
```

**Comment by anntzer** [comment]
I can try having a look if you can provide your data.

**Comment by nkeim** [comment]
I'm preparing release notes for this issue (about not sorting tracks in #597 ) and would like to resolve an ambiguity. Does this change mean that

> although particle numbers may be different than in the previous release (v0.4.2), as long as the input features are identical, particle numbers will be stable from run to run.

or, 

> particle numbers are now unstable from run to run, just as the ordering of `set` and `dict` objects is unstable.

If it's the latter, I'm a bit concerned about reproducibility. For instance, I might write down a trajectory number in my lab notebook as being noteworthy (or invalid). I could be confident that as long as I didn't change any particle tracking parameters and kept my Python environment the same, that identifier would be valid, even if I lost the trackpy output or gave my scripts to someone else to run.

Does that sound like a realistic scenario? I suppose that in all cases, the much more correct thing for me to do would be to write down "the trajectory beginning with the particle at (*x*, *y*) in frame *t*." Maybe we should have a convenience function to do that? 😉

**Comment by nkeim** [comment]
Just to clarify: if we really do think that not sorting tracks presents too high a barrier to reproducibility, all we have to do is make it optional. I still think it's a good addition to trackpy!

**Comment by anntzer** [comment]
No guarantees, but my guess is that you'll still get stable results by setting PYTHONHASHSEED to enforce dict ordering.

**Comment by nkeim** [comment]
Ah! OK, that makes sense. An environment variable is not an ideal solution for people using JupyterHub or other setups where python isn't started from the command line. I think it would be better to have a "hidden" (but documented) option, akin to `trackpy.linking.Linker.MAX_SUB_NET_SIZE`.

We don't have to add this option soon but it's worth noting as a feature request that may be very important to some.

For now, the relevant release notes text in #605 reads

> - During linking, particles are not sorted before assigning new
  trajectories. This greatly speeds up linking under certain conditions.
  The actual coordinates and linked trajectories are not affected by this
  change, but the unique number assigned to a trajectory (the "particle"
  column) may change from run to run. The most reproducible way to identify a
  specific particle is still the particle's coordinates at an instant in time.
  To revert to the previous behavior, set the "PYTHONHASHSEED" environment
  variable before starting Python.
  (:issue:`597`, :issue:`601`)

**Comment by anntzer** [comment]
In recent (>=3.6) pythons you could also get away if you don't use sets but only dicts (e.g. simulating sets as {key: None, ...} dicts), taking advantage of the preservation of dict insertion order.

**Comment by anntzer** [comment]
Actually, I guess that another solution would be to sort all trajectories by lexicographical order of their (first-frame, first-x, first-y) *after* all the linking has been done -- so a single sort operation at the end, which should be relatively cheap.

**Comment by nkeim** [comment]
Thanks @anntzer ! Yes, I'd like to think about this a bit more. Unfortunately, because trackpy supports streaming (writing each new linked frame to disk instead of accumulating them in memory), sorting new particle IDs still has to be implemented for each frame.

I think I've identified a mainstream use case where not sorting could really confuse or frustrate a user: tracking smallish data sets in a Jupyter notebook, especially if you're a novice. For example, if I were examining individual trajectories in a movie with only 5 particles, the particle IDs would seem like the best way to identify trajectories—I could keep {0, 1, 2, 3, 4} in the working memory of my brain. I would probably ignore any advice to use other ways of identifying them, and I would probably still be annoyed if the IDs ever changed — especially if they changed when I zipped up the entire data set (perhaps just tens of MB) and sent it to a colleague.

What about adding a `sort=True` argument, that could be overridden for extra speed? Alternately, this could be added as a global option, much like `MAX_SUBNET_SIZE`.

**Comment by anntzer** [comment]
Fair points.  Per the above, another strategy, if you're willing to restrict yourself to Py3.6+ (which is already more lenient than what https://numpy.org/neps/nep-0029-deprecation_policy.html suggests), would be to replace all uses of `set`s by `{key: None}` dicts, which maintain insertion order.  Adding a parameter to tweak this slightly obscure setting doesn't appeal to me much (few people will realize it's here), but it's a design choice for you to make.

**Comment by nkeim** [comment]
@caspervdw Unfortunately this has to go back in the v0.5 milestone… the change in the implementation has already been committed and we need to inform users.

If v0.5 is strictly a maintenance release then we should roll back the #597 PR. But I get the sense that since it's v0.5, we are OK with minor breakage in some workflows.

I'll see if I can resolve this today.

**Comment by nkeim** [comment]
I've meditated on this and coded up a "least-bad" possible solution in #657. At this moment, I don't think it is worth the extra lines of code.

@anntzer 's idea of using dicts instead of sets to maintain assertion order is a good one, but sets seem to be better optimized for what we do, so we would have to test performance carefully.

I'm closing this issue for now, and I'll close #657 soon.
