### ISSUE TITLE
Make multiprocessing the default for `batch()`

### ISSUE THREAD

**Issue by nkeim** [soft-matter/trackpy#605]
As of #602 , the default for `locate_brightfield_ring()` is `processes=‘auto’` (use all available CPUs), while for `batch()` it’s `processes=1` (no parallelization; see #499 ). It seems like it should be `auto` for both—a non-expert user would expect trackpy to just run as fast as possible on the available hardware. If the user is doing their own parallelization and wants to keep trackpy on one CPU, presumably they would be expert enough to change that option. And I’m sure there are edge cases in which multiprocessing slows down these computations, but it seems like those would be rare. 

Any thoughts before I submit a PR?

**Comment by danielballan** [comment]
That sounds sensible to me.
