### ISSUE TITLE
trackpy.motion.direction_corr fails on Pandas > 1.0 with NotImplementedError GH27198

### ISSUE THREAD

**Issue by damiandn** [soft-matter/trackpy#608]
trackpy.motion.direction_corr will fail with NotImplementedError GH27198 on Pandas > 1.0

Steps to replicate:
1) Install trackpy in fresh conda environment using conda install -c conda-forge trackpy
2) Load or generate a track dataframe
3) Run trackpy.motion.direction_corr on that dataframe

Expected behavior: 
direction_corr returns motion correlation DataFrame

Actual behavior:
Trackpy crashes with NotImplementedError GH27198

This seems to be related to this removal in Pandas 1.0:
"The ‘outer’ method on Numpy ufuncs, e.g. np.subtract.outer operating on Series objects is no longer supported, and will raise NotImplementedError (GH27198)"

Rolling back to Pandas 0.25.3 and installing trackpy with pip fixes the error on the same DataFrame, however the following warning message is displayed:

`C:\Users\dalledam\AppData\Local\Continuum\anaconda3\envs\tracking\lib\site-packages\trackpy\motion.py:492: FutureWarning: outer method for ufunc <ufunc 'subtract'> is not implemented on pandas objects. Returning an ndarray, but in the future this will raise a 'NotImplementedError'. Consider explicitly converting the Series to an array with '.array' first.
  cosine = np.cos(np.subtract.outer(j.direction, j.direction))`

Full error message below:

ipython-input-14-5c2fcc8ce9ec> in <module>
----> 1 trackpy.motion.direction_corr(tracks_subset, 1, 2)

~\AppData\Local\Continuum\anaconda3\envs\tracking\lib\site-packages\trackpy\motion.py in direction_corr(t, frame1, frame2)
    490     """
    491     j = relate_frames(t, frame1, frame2)
--> 492     cosine = np.cos(np.subtract.outer(j.direction, j.direction))
    493     r = np.sqrt(np.subtract.outer(j.x, j.x)**2 +
    494                 np.subtract.outer(j.y, j.y)**2)

~\AppData\Local\Continuum\anaconda3\envs\tracking\lib\site-packages\pandas\core\series.py in __array_ufunc__(self, ufunc, method, *inputs, **kwargs)
    703             return None
    704         else:
--> 705             return construct_return(result)
    706 
    707     def __array__(self, dtype=None) -> np.ndarray:

~\AppData\Local\Continuum\anaconda3\envs\tracking\lib\site-packages\pandas\core\series.py in construct_return(result)
    692                 if method == "outer":
    693                     # GH#27198
--> 694                     raise NotImplementedError
    695                 return result
    696             return self._constructor(result, index=index, name=name, copy=False)

NotImplementedError:

**Comment by nkeim** [comment]
@damiandn could you please verify that #613 fixes this? (The failed tests there appear to be unrelated.)

**Comment by damiandn** [comment]
@nkeim Tested and I can verify that #613 fixes this issue on pandas 1.0.

Thanks!
