### ISSUE TITLE
formulae for edge handling in trackpy.static.pair_correlation_3d

### ISSUE THREAD

**Issue by MaartenBransen** [soft-matter/trackpy#611]
When calculating the radial distribution function using `trackpy.pair_correlation_3d` with `handle_edge=True`, it calls a subroutine that calculates the part of the surface area of the spherical shell around a particle which lies inside of the boundaries of the bounding box. It does so by calculating the area of  the sphere, then subtracting the area of a spherical cap cut off by one of the sides (given by `sphere_cap_area`). In case one sphere overlaps with multiple sides, it subtracts all caps and then adds back the area which is counted double along the edges (`sphere_edge_area`) and in the corners of the box (`sphere_corner_area`).

The formulae in these functions appear to be exact, but I have not found such a method for edge correction in the literature. I am interested in this because I am trying to do something similar for related project. The formula for the surface area of a spherical cap is well known, but the other two for the area of a section cut off by two or three perpendicular planes, are, at least to me, not trivial to derive. I have also been unable to find these (or other) formulae for this problem elsewhere. To the best of my knowledge no reference is given in the trackpy documentation either.

I am therefore wondering the following things:
- Is it indeed an exact solution that is used? (the changelog of static.py does seem to indicate so)
- Does anyone still know the reference where these expressions came from, or did someone 'do the math' for this themselves?

I believe it was @caspervdw who wrote the current version of `pair_correlation_3d`, perhaps he still knows?

**Comment by caspervdw** [comment]
Hi, Yes I did these derivations back in my PhD. They didn’t end up in my thesis but for sure I have them laying around somewhere. I’ll look them up for you.

**Comment by caspervdw** [comment]
Found it and put the LaTeX source on overleaf. You can view via https://www.overleaf.com/read/ghybhzwwjjbj

**Comment by MaartenBransen** [comment]
That's great, thank you!
