### ISSUE TITLE
BLD: CI tests aren't running on Python 2.7

### ISSUE THREAD

**Issue by nkeim** [soft-matter/trackpy#614]
For some reason, only the Python 3.5 environments in Travis are actually running unit tests anymore. Logs from the Python 2.7 environments end with `Ran 0 tests in 0.000s`. [Here is an example run](https://travis-ci.org/github/soft-matter/trackpy/builds/702510159).

**Comment by caspervdw** [comment]
As Python 2.7 has reached its end of life, I am :+1: on dropping the tests in that env altogether. Most projects are moving on, some are even constraining to 3.6+.

We leave the six package in, so it will probably keep working under 2.7, but stop giving guarantees about it.

**Comment by nkeim** [comment]
The fix for this issue turned out to be very simple; see #615 . 

That is a good point about Python 2.7! EOL is the end of this year, so I think we shouldn't feel compelled to drop support before then. But we should drop it sooner if maintaining compatibility takes any significant resources. 

I'm ashamed to say that my tracking workflow is still not 100% on Python 3; my group and I have updated parts of our custom software, but it's been a low priority.

**Comment by rbnvrw** [comment]
I think according to this: https://www.python.org/doc/sunset-python-2/ the "official" date of Python 2 EOL has already passed (Jan 1st, 2020). So I think it would be more than fair to remove the tests for 2.7 as well :+1:

**Comment by nkeim** [comment]
Oops! For some reason I thought it was the end of *this* year. In that case it makes sense for trackpy v0.5 to be officially supported on Python 3 only.

I will create a new issue since there are other things we must do besides just dropping the CI environments.
