### ISSUE TITLE
Average Radius of Gyration of a particle from its complete trajectory

### ISSUE THREAD

**Issue by talha1369** [soft-matter/trackpy#617]
Hi, I have a movie with several particles which last for different numbers of frames aka trajectory lengths e.g. particle 1 can last for 17 frames while particle 2 might last for 5 frames and so on. Trackpy.batch and trackpy.link_df gives the radius of gyration "frame-wise" for each particle, but I am interested in finding the average radius of gyration for a particle. Is there a simple and easy way to calculate the average radius of gyration of a particle for its complete trajectory?

**Comment by nkeim** [comment]
Happily, Pandas was made for this! Look at [documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html?highlight=groupby#pandas.DataFrame.groupby) and examples for `groupby`.

**Comment by nkeim** [comment]
The [Pandas User Guide](https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html) is also helpful on this point.
