### ISSUE TITLE
 any way to select points for  fit_powerlaw?

### ISSUE THREAD

**Issue by khoroshyy** [soft-matter/trackpy#623]
Hi. 
Is there a way to limit points used in fit_powerlaw(em1).
Lets say use the first 90%?
Thanks.
Petro

**Comment by rbnvrw** [comment]
Hi Petro, you can filter the DataFrame before passing it to the `fit_powerlaw` function:
```
em1 = em1.head(10)  # selects the first 10 rows
```
Have a look here: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html
Good luck!
