### ISSUE TITLE
physical meaning of returned parameters

### ISSUE THREAD

**Issue by Mattyboi123** [soft-matter/trackpy#625]
Hello,

I'm really enjoying using this library its incredible useful. I'm wondering what the returned parameters for features mean, specifically signal and size. I'm guessing that the signal is related to how diffuse the intensity is across the feature and that size is the number of particles within the feature? I only ask to be sure before drawing conclusions in data interpretation based on perhaps false assumptions on my part. Apologies for the perhaps obvious nature of the question

**Comment by nkeim** [comment]
Good question! There's a paragraph near the bottom of the ['locate' documentation](http://soft-matter.github.io/trackpy/v0.4.2/generated/trackpy.locate.html#trackpy.locate) that gives some details about the return values. There is also a [tutorial on uncertainty estimation](http://soft-matter.github.io/trackpy/v0.4.2/tutorial/uncertainty.html) which has to do with the "signal" value. However, if there's a clear written description of the eccentricity calculation, it seems we've lost it. See #554 for the discussion.

Please follow up if something's still unclear or you'd like to suggest a change to the documentation!

**Comment by Mattyboi123** [comment]
Many thanks, that is clear.

I have another question, perhaps its a feature request in fact? Is there a
functionality in trackpy already that returns tiff stacks of each track
where the located features are aligned  as per the track connectivity?

Best

Matt

**Comment by nkeim** [comment]
Hi! That functionality would be helpful but it isn't in trackpy. Feel free to create a new issue with the feature request. If you can also post some sample code, I'm sure there are others out there who would find it useful and suggest improvements!
