### ISSUE TITLE
3D Point Spread Function

### ISSUE THREAD

**Issue by b2jia** [soft-matter/trackpy#627]
Regarding ```trackpy.locate```, there is a brief discussion of the different resolution x, y, and z. In fluorescence microscopy there's also the problem of a 3D point spread function that does not resemble a 3D Gaussian. Is there support to pass the point spread function as a parameter for object localization?

I realize it is easy to implement a matched filter to detect objects with a N-dimensional PSF. However, it is not so trivial to get sub-pixel resolution that trackpy does so well! Thank you

**Comment by nkeim** [comment]
Unfortunately trackpy does not perform any deconvolution or take a PSF into account.

If the particle is spherical, you could try generating an artificial image of a particle and using it as a convolution kernel. This should give you a roughly Gaussian output that has the same center as the actual particle, at subpixel resolution.

There may also be other Python packages to do exactly what you want before your images are passed to trackpy — hopefully someone else will chime in.
