### ISSUE TITLE
Trackpy sub-pixel bias

### ISSUE THREAD

**Issue by praptibajaj28** [soft-matter/trackpy#635]
I am using trackpy to locate and link particles in the attached raw image (cropped) . As you can see, the particle diameter is 3 pixels. The region of major interest is the one with very high density of particles. When I use particle size of 5 (for the full raw image and not cropped), trackpy finds reliable particle positions in high density region but it has terrible sub-pixel bias. When I use particle size of 7, trackpy doesn't find many particles in high density region and the ones found are also wrongly located. However, the sub-pixel resolution is good for particle size 7. Is there a method to improve the sub-pixel resolution in trackpy except changing the particle size? 

For reference, I am also uploading images showing difference in the particles found using particle size 5 and particle size 7 with the same minmass value. The one with more particle labelled is made with particle size 5. 

Thank you. 
![raw_sc01fr0_200_300_120_160_251120](https://user-images.githubusercontent.com/54531209/100244292-0ba4f980-2f37-11eb-941c-6ec3a7626fe6.png)
![SPB7_sc01fr0_251120](https://user-images.githubusercontent.com/54531209/100244358-1d869c80-2f37-11eb-902d-67957ff44ff8.png)
![SPB5_sc01fr0_251120](https://user-images.githubusercontent.com/54531209/100244373-237c7d80-2f37-11eb-88e0-c0e461400fd9.png)
<img width="944" alt="p_size5_minmass15_PIDlabelled" src="https://user-images.githubusercontent.com/54531209/100623781-e8a58b80-3322-11eb-8265-14726ac6cf49.PNG">
<img width="942" alt="p_size7_minmass15_PIDlabelled" src="https://user-images.githubusercontent.com/54531209/100623790-ec391280-3322-11eb-9f1c-36ee659d7dc9.PNG">

**Comment by rbnvrw** [comment]
Thank you for your question. In general, the radius that you use should match the feature size. However, in your case, the features are very small (only 2 to 3 pixels). Trackpy is not meant to track features that are this small. It uses the assumption that your features are Gaussian blobs, which does not apply here. You could write your own custom algorithm that detects 2x2 (?) pixel squares and use Trackpy for linking, as in the bubble tutorial: http://soft-matter.github.io/trackpy/dev/tutorial/custom-feature-detection.html But it is doubtful whether you can even get subpixel accuracy from these tiny features. Let me know if this helps!

**Comment by praptibajaj28** [comment]
@rbnvrw Thank you very much for your reply. I did make it work for my particles with these parameters : particle_size=5, minmass=15, invert=False, max_iterations=100000, separation=2, characterize=True, noise_size=0.5, threshold=5. I arrived at these results after reading a few papers from my field about sub-pixel bias and then trying different parameters to reach the ideal conditions. And here you can see that the sub-pixel bias is negligible and the particles are also tracked quite well. I think the parameter "separation" was important to reach these results as for smaller particles with such high density, this could be an important parameter. 
![sc01_fr0_subpx_021220](https://user-images.githubusercontent.com/54531209/113886324-e10a5d80-97c0-11eb-8bf9-5c21f8fa01b6.png)
