### ISSUE TITLE
Cannot find docs on reconnect_traj_patch.

### ISSUE THREAD

**Issue by loomcode** [soft-matter/trackpy#647]
Hello and thank you for the project!  It's been very helpful.  I'd like to run tracking in parallel and the **trackpy.link_partia**l documentation says: _The description for A dataset can be divided into several patches (time intervals) and linked separately with this function, for e.g. parallel processing. The results can then be stitched back together with reconnect_traj_patch()._  The issue is that the link to reconnect_traj_patch is broken and I can't find any documentation for how to use it.  I also can't find a reference to the function in my copy (version 0.4.2).  Any guidance would be great.  Thank you.

**Comment by nkeim** [comment]
Thanks! You should be able to get more information (including the documentation text for `reconnect_traj_patch()` from the [source code](https://github.com/soft-matter/trackpy/blob/master/trackpy/linking/partial.py). I'll leave this open so that we fix the online documentation.

**Comment by loomcode** [comment]
Awesome!  I'll try it out tomorrow.  Thanks!

**Comment by jackyko1991** [comment]
This issue seems still not fixed after an year.

**Comment by nkeim** [comment]
Thanks for noting this @jackyko1991 . The related PR #648 was made when our automated build system was in flux; now it just needs a rebase before we can merge it. I added it to the 0.6 milestone.
