### ISSUE TITLE
Query about link table fields

### ISSUE THREAD

**Issue by Jeff-Gui** [soft-matter/trackpy#651]
Hi, I wonder if optional fields other than coordinates & frames in a link table, like signal intensity, roundness etc., should follow some standard format.

Thanks.

**Comment by nkeim** [comment]
After feature-finding is done (with `locate()` etc.), I don't think any other function in trackpy uses that information, so the standard format is just what is implemented by the feature-finding functions. All the other functions ignore and/or preserve that information, in case you have a use for it later. If you want to strip it out to save space, should not be any unintended consequences.

**Comment by Jeff-Gui** [comment]
Just to check if my understanding is correct, only x, y and frame columns are useful in `link()`, not anything else? (The screenshot is from the walkthrough tutorial). Since I'm using some external source of the object features, it would be helpful to know how much features are allowed to include.
<img width="981" alt="截屏2021-03-09 23 26 13" src="https://user-images.githubusercontent.com/48266970/110494848-f000e000-812e-11eb-8324-d21346e1c020.png">

**Comment by Jeff-Gui** [comment]
Thanks! It helps a lot.
