### ISSUE TITLE
Can a new version be released to make it easier to take advantage of developments?

### ISSUE THREAD

**Issue by tomchor** [soft-matter/trackpy#652]
Hi, thanks for the really cool package.

I've used this package in the past to track some features in fluid dynamics simulations and I'm coming back to it now to resume that tracking. I noticed there's been some significant development since the latest release (which was in 2019) but that didn't make it's way into pypi. 

I wonder if you'd consider releasing a new version to make it easier to use and to keep track of those changes. I know the user can always clone the repo and install the latest version locally, but that makes it hard to keep track of which version of the package you're using for your application and can thus have reproducibility implications.

Thanks!

**Comment by caspervdw** [comment]
@tomchor Thanks for urging us to make a release. I’d like to first get the test passing again, after that, we’ll do a release.

**Comment by caspervdw** [comment]
Version v0.5.0 is now on PyPI. Conda-forge will follow soon.

**Comment by tomchor** [comment]
Great! Thanks!

I'm closing this issue since this resolves it.
