### ISSUE TITLE
Silencing print statments in link_df

### ISSUE THREAD

**Issue by loomcode** [soft-matter/trackpy#662]
I'm running a multiprocessing pool where trackpy is called and the link_df function logger prints a line for each frame.  This adds up to several thousand print calls in my code.  It would be nice if there were a verbose=False argument to turn this off.  For now I'll just find the line and comment it.  Thanks.

**Comment by nkeim** [comment]
Have you tried `trackpy.quiet()`?

**Comment by loomcode** [comment]
Perfect.  Thanks!
