### ISSUE TITLE
How to eliminate overlapped objects?

### ISSUE THREAD

**Issue by yongshuo-Z** [soft-matter/trackpy#665]
Hi,

Thanks for the great work!! 

When I use `tp.locate` and `tp.annotate` functions to track objects. I find that there are many objects overlapped, which can be false-positive. If I want to eliminate overlapped objects with central distances less than the picking diameter, what functions could I use? 

I've read the examples, but still not come up with a good idea. Any advice? Thanks a lot!

**Comment by nkeim** [comment]
Have you tried the `separation` argument?
