### ISSUE TITLE
Color-coded trajectories tangling together

### ISSUE THREAD

**Issue by annezhou94** [soft-matter/trackpy#669]
Hi, 
I am using this package for protein tracking in TIRF experiments. When it generates the trajectories I noticed that some spots have multiple trajectories tangling together. I am wondering if that means two spots coming to together or is it for some other reasons. Thanks!
![tangled](https://user-images.githubusercontent.com/71746653/126592864-3a9742af-227c-40a2-a751-3ec4c77bacae.png)

**Comment by caspervdw** [comment]
It is hard to judge from this image whether these are multiple objects tangling together, or just a single one that “blinks” in and out of the image and consequently is identified by trackpy as multiple ones.

I would suggest inspecting the dataframe and plotting for instance the number of particles per timeframe.

**Comment by caspervdw** [comment]
As this question is not related to trackpy itself, but to interpreting the trajectories, I’ll close the issue. If you have any questions about the usage of trackpy please don’t hestitate to reopen this or open a new issue.
