### ISSUE TITLE
how to connect trackpy-examples with trackpy, what is the hierarchy ?

### ISSUE THREAD

**Issue by besbesmany** [soft-matter/trackpy#670]
I put my custom dataset in folder trackpy-examples\sample_data

\notebooks\walkthrough.ipynb is not working 

how to connect trackpy-examples folder with trackpy folder 

what is the hierarchy of folders of the 2 githubs

**Comment by BptGrm** [comment]
Did you change anything in the notebook after transferring the files ? If so, please show an example of your code.

Notebooks are meant to teach you how to use TrackPy, it's probably better for you to write code specific to your needs rather than reuse something else.

**Comment by besbesmany** [comment]
I will fix jupyter lab connection then check again trackpy code
thank you
