### ISSUE TITLE
Filter spurious trajectories shows After: 0

### ISSUE THREAD

**Issue by besbesmany** [soft-matter/trackpy#671]
this makes all next code of walkthrough.ipynb not working

what should I do

![1](https://user-images.githubusercontent.com/35992924/127037171-cf24f2bf-8e42-4a75-9fd2-0b046613c052.png)

**Comment by BptGrm** [comment]
`filter_stubs` probably filtered all of your trajectories. Try changing the length cutoff to something lower than 25.

**Comment by besbesmany** [comment]
thank you
