### ISSUE TITLE
I want get car motion trajectory like next figure

### ISSUE THREAD

**Issue by besbesmany** [soft-matter/trackpy#672]
I have dataset for car
I want to get this figure from prediction.ipynb

where should I add dataset in this file to get this chart

![2](https://user-images.githubusercontent.com/35992924/127037667-b0ce1190-4105-407c-8ecc-174f0396350a.png)

**Comment by caspervdw** [comment]
What you probably need is a guide for using matplotlib. Please consult the great documentation and examples over there.
