### ISSUE TITLE
Trajectory overlay on video

### ISSUE THREAD

**Issue by alix-pham** [soft-matter/trackpy#682]
Hello Trackpy team!

I have been trying to check how accurate is the tracking algorithm from TrackPy, and for this, I would like to have the overlay of the trajectory (e.g. the one given by plot_traj) over the whole timelapse. This way I could see and validate the accuracy of the tracking. I have tried making an animation of the plot_traj output, but it doesn't work; I also tried to download each plot_traj with superimposing each frame and then fetching them to make a video out of them, but it takes a while; I have tried to download the plot_traj output as an image to overlay on each frame but I can't manage to align it properly on my images (even using plt.axis('off'), plt.margins(0) and fig.tight_layout())

Can you think of a not-too-long, easy-to-manipulate way of seeing the trajectory overlay on a video/timelapse/tif file of all the frames, in order to validate the tracking? Did I miss something?

Thank you very much in advance.

**Comment by stevenvanuytsel** [comment]
Hi,

I’m not part of the trackpy team but I wrote a function that simply plots the tracks on top of the stack using matplotlib, and implemented a slider that allows me to navigate through the frames. I’d be happy to share the code if you'd want it. 

Cheers,
Steven

**Comment by alix-pham** [comment]
Thank you very much, I will try your code! However, my data is 1500x1500 px with approx. 400 frames, and 50 to 200 tracks...

Thanks again,
Best,

Alix
