### ISSUE TITLE
ChannelPredict flow_axis

### ISSUE THREAD

**Issue by gui-miotto** [soft-matter/trackpy#689]
I was playing around with `ChannelPredict` and I noticed something weird: it accepts any value for `flow_axis`. Here is a bit of my code (a modified walkthrough):

```python
features = tp.batch(
    frames=dataset,
    diameter=11,
)

pred = tp.predict.ChannelPredict(
    bin_size=1.,
    flow_axis="foo",  # ?
)

tracks_0 = pred.link_df(
    features,
    search_range=10,
    memory=1,
    )
```

I was expecting this crash due to an invalid value for `flow_axis`, but it doesn't. It just do business as usual. So, my questions are:
1. Is there something wrong with my code?
2. If not, is this the intended behavior (to not raise an exception)?
3. What are the actual valid values for `flow_axis`? Can I use something like "-y"?

**Comment by nkeim** [comment]
This should be fixed by #710.
