### ISSUE TITLE
tp.locate metrics not used in linking?

### ISSUE THREAD

**Issue by reventropy** [soft-matter/trackpy#697]
In terms of the number of successfully tracked (linked) objects, it doesn't seem to matter whether I provide metrics from tp.locate (mass, size, ecc, etc.), or just the x,y positions.  I thought these measurements would be leveraged to improve tracking but that's not what I'm seeing.  Is this true, or am I doing something wrong?  Thanks!

**Comment by nkeim** [comment]
Sorry for not replying sooner! This is possible but you have to specify it. Check out #470 and #651 .
