### ISSUE TITLE
Confidance evaluation of the tracking

### ISSUE THREAD

**Issue by Ciro1990** [soft-matter/trackpy#714]
Dear all,

I would like to ask if trackpy computes any metrics that describes the confidence/uncertainty of a specific assignment

Ideally, I would like to know if, in any frame, the assigned track ID has crossed a certain threshold, in order to raise a flag for me to correct that assignment manually.

Thanks!
Ciro

**Comment by maxwellbowser** [comment]
Hi Ciro, 

I don't believe that there is any way to get this output, do you mean like what is the confidence that the located object is actually an object?

**Comment by maxwellbowser** [comment]
I believe that the returned ep column is what you're looking for, it can be used as an estimation of uncertainty, where a larger number is a lower confidence!
Source: http://soft-matter.github.io/trackpy/dev/tutorial/uncertainty.html

**Comment by nkeim** [comment]
Thanks for asking, @Ciro1990 , and thanks for your answer, @maxwellbowser !
