### ISSUE TITLE
level keyword argument was removed in pandas>2.0

### ISSUE THREAD

**Issue by Pawelbure** [soft-matter/trackpy#746]
Thanks for this very helpful library! 
When I run `tp.emsd` function I run into the following TypeError:
`TypeError: mean() got an unexpected keyword argument 'level'`

I try to compute it on the following data frame:
<img width="812" alt="output_trackpy" src="https://github.com/soft-matter/trackpy/assets/10000305/e4a9cb2c-c7af-4db5-b29f-f9571de1d3e9">

It seems that pandas has removed the `level` keyword argument from the mean function? Or could I have somehow used the function wrong?

**Comment by caspervdw** [comment]
Thanks @Pawelbure for your report. This issue was fixed in https://github.com/soft-matter/trackpy/pull/740 and will be released shortly
